Cutter docs update
rizinorg/cutter pull request #2259
Opened 2020-06-21 02:07 UTC by Surendrajat

**Your checklist for this pull request**move building errors to troubleshooting section
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
This PR continues #2238.

**Test plan (required)**
Build and run docs.

**Closing issues**
Partially closes #744

2020-06-27 13:10 UTC, Surendrajat commented
I've added a widget page with few moving screenshots(WIP). Let me know what you think.

2020-06-27 13:46 UTC, karliss commented
I would be much happier if documentation was moved to separate repository before adding a bunch of screenshots for all the widgets and dialogs. Those could quickly cause bloat.

2020-06-27 13:51 UTC, XVilka commented
It can be made a submodule to keep the old structure.

On Sat, Jun 27, 2020, 21:46 karliss <notifications@github.com> wrote:

> I would be much happier if documentation was moved to separate repository
> before adding a bunch of screenshots for all the widgets and dialogs. Those
> could quickly cause bloat.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radareorg/cutter/pull/2259#issuecomment-650563261>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRT7MVWMXNXH3J64I7G2DRYXZ2ZANCNFSM4ODUP3LA>
> .
>

2020-06-27 14:17 UTC, Surendrajat commented
I see #2056 open for just this. If it's done I can move things there.
As for submodule, I think it'll add additional commits to this repo on each update to docs, which will probably be better if avoided. How about splitting API docs and other docs and leave API docs here?

2020-07-18 10:39 UTC, ITAYC0HEN commented
You might want to consider adding the `:menuselection:` and `:guilabel:` to the docs as part of this or another PR. @karliss found these features just recently

https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html

2020-07-21 16:47 UTC, Surendrajat commented
@karliss I've removed the widget intro part and will open another PR to continue work on that until we decide if to split repo or not.

2020-07-21 17:19 UTC, karliss commented on docs/source/index.rst
> +`here <contributing.html>`_
Please don't do that. Sphinx can't check if link is valid if you use html urls. Use the sphinx/rst builtin mechanisms for referencing documents or headers.

2020-07-21 17:24 UTC, Surendrajat commented on docs/source/index.rst
> +`here <contributing.html>`_
Not sure how it's working in docs but not locally. Will check again and fix.

2020-07-21 18:17 UTC, karliss commented on docs/source/index.rst
> +`here <contributing.html>`_
If it doesn't work for you locally version without extension is likely also wrong.

2020-07-21 18:47 UTC, ITAYC0HEN commented on docs/source/index.rst
> +`here <contributing.html>`_
Also, I prefer to write the full description and not "here".

For example "take a look at our contribution guidelines" or "take a look at our guidelines for new contributors" or "read our tutorials for contributors" etc

2020-07-22 12:52 UTC, ITAYC0HEN requested changes
Fantastic work!

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +make sure it is in the sync with upstream **Cutter** repo. Simply run:
```suggestion
make sure it is in sync with upstream **Cutter** repo. Simply run:
```

or

```suggestion
make sure it is synced with upstream **Cutter** repo. Simply run:
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +Environment* section in Qt Creator. See the screenshot below should you
Only Qt Creator?

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +   version and if radare2 was installed like the submodule)
What is this "modern version"? Maybe should be more specific (e.g for versions newer than 1.2.3.4, ....)

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +   version and if radare2 was installed like the submodule)
Would rephrase "was installed like the submodule" because the meaning isn't that clear

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +Or radare2 libs could be installed to ``/usr/lib/pkgconfig/``, so you
I'd rephrase the opening "or" and the "could be" here. I am not sure about the meaning of the sentence. Maybe "If radare2 libs can be installed to..." or "It is possible that radare2 libs..."

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +can add variable ``PKG_CONFIG_PATH`` with value ``/usr/lib/pkgconfig/``
```suggestion
can add a variable ``PKG_CONFIG_PATH`` with the value ``/usr/lib/pkgconfig/``
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/building.rst
> +On macOS, QT5 apps fail to build on QtCreator if you have the ``libjpeg``
```suggestion
On macOS, QT5 apps fail to build on QtCreator if you have the ``libjpeg``
```
```suggestion
On macOS, Qt5 apps fail to build on QtCreator if you have the ``libjpeg``
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +  This is also used when the output is complex and does not get parsed correctly in ``cmdRaw``.
```suggestion
  This is also used when the output is complex and is not parsed correctly in ``cmdRaw``.
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
>  version of them to Cutter.
```suggestion
the radare2 submodule or the others, to push their most recent
version to Cutter.
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/user-docs/command-line.rst
> +CommandLine Options
```suggestion
Command-Line Options
```
or
```suggestion
Command-line Options
```
or
```suggestion
Command Line Options
```

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/user-docs/common-issues.rst
> +`#579 <https://github.com/radareorg/cutter/issues/579>`__
Seems like this weird number is just thrown there out of no-where. Try to add an opening sentence to introduce the number. "For a detailed explanation see issue #1234"

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/disassembly-context-menu.rst
> +UnDefine a Function
```suggestion
Undefine a Function
```

The capital `D` is not needed. Undefine, Unbelievable , Undo, Unconventional, Unfamiliar

2020-07-22 12:52 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/disassembly-context-menu/debug-context-menu.rst
> +**Description:** Set the Program Counter of the debugger to the current offset. For example, on a Intel 64bit program, Cutter will set the value of the RIP register to the current address.  *This opt
The "debuggee" here is intentional -> https://wikidiff.com/debugger/debuggee

2020-07-22 13:57 UTC, Surendrajat commented on docs/source/building.rst
> +Environment* section in Qt Creator. See the screenshot below should you
I copied it from common-errors :(

2020-07-25 17:44 UTC, ITAYC0HEN commented
is there anything left to do?

2020-07-25 17:57 UTC, Surendrajat commented
> is there anything left to do?

Yes. Finishing right away. :P

2020-07-25 20:32 UTC, ITAYC0HEN approved these changes
Looks good! I love this pr :)

2020-07-26 04:56 UTC, merged