Draft for release procedure.
rizinorg/cutter pull request #2325
Opened 2020-07-23 18:56 UTC by karliss

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2020-07-27 07:55 UTC, xarkes commented on docs/source/contributing/code/release-procedure.rst
> +   * Start debuging
debugging*

2020-08-12 05:59 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    2. Place the archive in folder and run the script, see cutter-translations for instructions
mention its name `build.sh`.
What instructions are available ion the repo?
make it linkable

2020-08-12 06:22 UTC, ITAYC0HEN requested changes
That's good we have such a release procedure.
I expected something a little more detailed, but I guess this is better than nothing and you mentioned that it is not exhaustive.

In terms of the writing, the English isn't fantastic here as it was written as side notes you took while doing the release and wasn't meant for really describing the steps, but only noting them.

I guess it's good enough for now. You can leave it open if you wish to update more things now that you do the bug-fix release

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +2. If there is desire to keep working in the master, create branch for the release and do all the following work there.
```suggestion
2. If there is a desire to keep working in the master branch, create branch for the release and do all the following work there.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +3. Lock r2ghidra and r2dec versions downloaded by packaging scripts. Specify a tag or commit hash.
how? where?

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +4. Update version
```suggestion
4. Update the version of Cutter by bumping the strings and configurations that are stating the version
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    #. ``git tag push origin v1.11.0-rc1``
Why specific to v1.11?

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    #. To be safe search for the previous version number.
```suggestion
    #. To be safe, search the code base for the previous version number.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +6. Create a GitHub release, mark it as pre-release save draft, set the tag to v1.11.0-rc1
Specific tag is used

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +7. Wait for packages to build
"Because we already pushed the new tag, GitHub knows to automatically start a building process for the packages and place them as artifacts in the release. Wait for the packages to be built."

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +9. If any major problems are found fix them. If a release branch is used fix them in master and cherry pick into release branch. If the amount of changes is sufficiently large repeat from step 3. inc
```suggestion
9. If any major problems are found, open an issue and fix them. If a release branch is used fix them in master and cherry pick into release branch. If the amount of changes is sufficiently large repeat from step 3. increasing rc number by one.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +10. Update version to 1.11.0
specific version

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +10. Update version to 1.11.0
remind them to remove the release candidate part from the version

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +11. Create tag
Duplicate the code example you showed before (for `rc`), it is useful

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    * Fill the release notes, preparing release notes can be started earlier. Compare current master or release branch against previous release to find all the changes. Choose the most important ones
```suggestion
    * Fill the release notes in the Release description. Preparing release notes can begin earlier. Compare current master or release branch against previous release to find all the changes. Choose the most important ones. Don't duplicate the commit log. Release notes should be a summary for people who don't want to read whole commit log. Group related changes together under titles such as "New features", "Bug Fixes", "Decompiler", "radare2" and similar.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +13. Announcement
```suggestion
13. Prepare announcement tweets and messages to send in the Telegram group, reddit, and others.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +14. Close milestone if there was one
Maybe open a new one as well?

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +This isn't intended as exhaustive testing process, just some simple steps to make sure everything isn't badly broken.
```suggestion
This isn't intended as exhaustive testing process, just some simple steps to make sure nothing is badly broken.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +* Open simple executable like /bin/ls or calc.exe
```suggestion
* Open a simple executable like ``/bin/ls`` or ``calc.exe``
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +* Make sure upgraded layout isn't completely broken
```suggestion
* Make sure that the upgraded layout isn't completely broken
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +* Disassembly shows something
```suggestion
* The Disassembly widget shows proper disassembly.
```

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +   * Open r2dec in decompiler widget, make sure it shows code
Check multiple functions and see that they are not causing a crash.

we had the situation in which r2dec crashed for some functions

2020-08-12 06:22 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +* Test that sample python plugin works
what about sample Cpp plugin?

2020-08-12 06:30 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +    #. ``git tag push origin v1.11.0-rc1``
It seemed easier to explain using a specific examples.

2020-08-12 06:36 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +* Test that sample python plugin works
Currently  cpp plugins can't be properly built against release package after it has been built. After some of the CMake refactoring is finished it should be more feasible.

2020-08-12 06:46 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    #. ``git tag push origin v1.11.0-rc1``
I think it is more confusing. For example, here it's harder to imaging patch-version upgrade as the patch-version is `0`. Best solution in my opinion is to give give several examples as this can only be 

Current version: `x.y.z`
New tag: `x.y.[z+1]-rc1` or `x.[y+1].0-rc1` or `[x+1].0.0-rc1`


What I suggest is something like this:
```
5. Create a tag for the release candidate. For example, for the `v1.11.0` release you'd do something like this:
    #. ``git tag v1.11.0-rc1``
    #. ``git tag push origin v1.11.0-rc1``
```

2020-08-12 07:11 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +This isn't intended as exhaustive testing process, just some simple steps to make sure everything isn't badly broken.
You have higher requirements :smile:

2020-08-12 08:20 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +   * Open r2dec in decompiler widget, make sure it shows code
That could be a general note for any of the steps in testing procedure. Try a few times with different functions or offsets.|

2020-08-13 17:06 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +   * Open r2dec in decompiler widget, make sure it shows code
Added

2020-08-13 17:07 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +    #. ``git tag push origin v1.11.0-rc1``
Feel free to modify the parts referring to version in the way you think is better.

2020-08-13 17:07 UTC, karliss commented on docs/source/contributing/code/release-procedure.rst
> +    2. Place the archive in folder and run the script, see cutter-translations for instructions
How about now?

2020-08-20 15:34 UTC, ITAYC0HEN requested changes

2020-08-20 15:34 UTC, ITAYC0HEN commented on docs/source/contributing/code/release-procedure.rst
> +    #. ``git tag push origin v1.11.0-rc1``
```suggestion
5. Create a tag for the release candidate. For example, for the `v1.11.0` release you'd do something like this:
    #. ``git tag v1.11.0-rc1``
    #. ``git tag push origin v1.11.0-rc1``
```

2020-11-01 11:53 UTC, xarkes commented
We are already using this procedure for releases, I think we can safely merge this and improve it over time.

2020-11-01 11:57 UTC, xarkes commented
I updated the procedure about Translations since it changed a bit since this PR was opened.

2020-11-01 11:58 UTC, merged