R2Dec with Annotations
rizinorg/cutter pull request #2407
Opened 2020-08-28 05:32 UTC by NirmalManoj

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
This PR implements annotations for the r2dec decompiler. Earlier, we were parsing to RAnnotatedCode from the `pddj` output. Now, a command `pddA` has been implemented by @wargio recently. The JSON output from `pddA` should ideally give all the information we need to make annotations as we have in r2ghidra-dec. This PR makes JSON parser for `pddA` output to `RAnnotatedCode`.

**Note**
This branch is created from the branch in PR #2402. Hence to see the changes made for just this PR, select commits from the commit with the message "output and looping for annotation.".

**Test plan (required)**
1. Fetch latest r2dec [ `r2pm -ci r2dec` ].
2. Compile this PR and open cutter.
3. You should be able to see the features available to r2dec with context-annotations.
4. Test all the actions (see note below)

**Note**
The `pddA` output as noted before, is still not perfect. There were some confusions, and because of that, the address of the references are not correct. Also, r2dec crashes while running `pddA` in some functions. Hopefully, this will get patched soon.
1. So for the function related actions, and targeted show-in, the only reference that will work now is the one for the declaration/definition of the functions. Test this.
2.  As of now, only function variable(arguments and local variables) declarations have annotations, so variable related actions (Rename and Edit) will work only for them.
3. Global variables and constant variables cannot be tested before it gets patched.

**Closing issues**

2020-08-28 18:20 UTC, karliss commented on src/common/Decompiler.cpp
> +                annotation.offset.offset = jsonAnnotation["offset"].toString().toULongLong(&ok);
If you are not using the the result you might was well leave the argument to default value which is `nullptr` for not reporting a failure. `QString::toUlongLong` supports that.

2020-08-28 19:16 UTC, NirmalManoj commented on src/common/Decompiler.cpp
> +                annotation.offset.offset = jsonAnnotation["offset"].toString().toULongLong(&ok);
Removed `&ok`.

2020-08-30 11:23 UTC, karliss commented
@NirmalManoj  Please rebase this PR to latest master?

2020-08-30 11:33 UTC, NirmalManoj commented
Will do that in half an hour

2020-08-30 12:48 UTC, NirmalManoj commented
@karliss Rebased this.

2020-08-30 16:35 UTC, karliss requested changes

2020-08-30 16:35 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    // seekable->seekToReference(offset);
Unused code.

2020-08-30 16:35 UTC, karliss commented on src/common/Decompiler.cpp
> +        code->code = strdup(json["code"].toString().toStdString().c_str());
The part of this function doing JSON -> RAnnotated code conversion could extracted to separate functions. Such conversions from one data structure to another are very suitable for being their own functions. Doing this will make rest of `decompileAt` logic easier to follow and it might help in future testing it.

2020-08-30 17:18 UTC, NirmalManoj commented on src/common/Decompiler.cpp
> +        code->code = strdup(json["code"].toString().toStdString().c_str());
I will extract this to a separate function. I was also thinking if I should make it a function in `Decompiler`, so that it can be used with other decompilers/new decompilers in case of need arises.

2020-09-27 11:03 UTC, ITAYC0HEN commented
@NirmalManoj What is the status of this PR ?:)

2020-12-16 06:51 UTC, XVilka commented
@NirmalManoj @wargio would be nice to have it merged before the 2.0.0

2020-12-16 12:56 UTC, NirmalManoj commented
> @NirmalManoj @wargio would be nice to have it merged before the 2.0.0

I talked with @wargio. He's saying there are still some wrong outputs in the output of `pddA`. So that will have to get fixed before merging this PR. Meanwhile, I will try to make this PR ready to merge when `pddA` output is fixed.

2020-12-21 09:07 UTC, ITAYC0HEN commented
Sounds amazing @NirmalManoj ! Let us know if there's anything we can do to help

2021-01-16 11:46 UTC, XVilka commented
Since https://github.com/rizinorg/cutter/commit/88478ffb30e177ad516ed091a53036e6b7eed074 was merged, please rebase the PR and update the title.

2021-03-04 18:15 UTC, xarkes commented
Hello, any update @NirmalManoj?

2021-07-22 06:25 UTC, NirmalManoj commented
Hello! I was very busy with university and some other things so that I couldn't spend time on this. Now, I plan to complete this PR by the end of this month.

2021-10-04 14:04 UTC, NirmalManoj commented on src/common/Decompiler.cpp
> +        code->code = strdup(json["code"].toString().toStdString().c_str());
Done.

2021-10-04 14:33 UTC, NirmalManoj commented
Hi everyone! I have pushed the changes. Here's a brief summary of changes:
 - A new function `RzAnnotatedCode *rz_annotated_code_from_json(QJsonObject &json);` is created in `Decompiler`. The function returns a `RzAnnotatedCode` parsing the JSON input.
- The JSON input should follow the format followed by the output of the decompiler plugins we have for Ghidra and RetDec.

The pddA output is still buggy, so some functions like seek to reference won't work. I have informed @wargio about this, but syntax highlighting and renaming variable names seems to work(partially). If there aren't other problems I have missed, we can merge this PR once the `pddA` output gets fixed.

An image showing highlighted output of JSDec.
![image](https://user-images.githubusercontent.com/18501167/135869799-fd4cdb91-fdc6-4702-a74b-0fd1de561c10.png)

2021-10-05 21:18 UTC, wargio commented
I have fixed the issue with jsdec. sorry for taking so long, but i never understood the output.
now it works as expected from this commit: https://github.com/rizinorg/jsdec/commit/8203bd379e625bb709feabd4e2351e438a3b8e27.

2021-10-20 08:33 UTC, wargio commented
> @NirmalManoj @wargio so what is the status? Could you please update and finish this PR?

The PR is ready for me (jsdec side the needed files have been updated via this PR: https://github.com/rizinorg/cutter/pull/2801)

2021-12-21 17:19 UTC, wargio commented
This is not a WIP anymore since i did test this PR with the current JSDec (0.3.x)

2021-12-21 17:32 UTC, NirmalManoj commented
Apologies for the delay. I got busy with some things and couldn't complete this. However, I had also tested this PR and there are no major changes if I remember correctly.

There were a couple of things I wanted check before merging. I'll try to finish it in a week and rebase this PR.

2022-02-08 04:35 UTC, XVilka commented
@NirmalManoj have you had any luck with that? Would be nice to have it in the 2.0.6 release.

2022-03-29 15:26 UTC, thestr4ng3r commented
I am doing the finalizing touches on #2407 and will then merge. Thanks for the work so far @NirmalManoj!

2022-03-29 15:26 UTC, closed without merging