Add cmake script for packaging r2dec on windows.
rizinorg/cutter pull request #2425
Opened 2020-09-06 18:24 UTC by karliss

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Same as recent PR for r2ghidra, this time for r2dec. After this it will be almost ready for switching windows release builds from qmake to cmake.

**Test plan (required)**

* Download windows artifact from github actions build, make sure r2dec compiler works

**Related issues**
#2098

2020-09-20 17:42 UTC, yossizap requested changes
The artifact doesn't contain r2dec, you forgot to update the GH workflow yaml with `-CUTTER_PACKAGE_R2DEC=ON`

2020-09-20 17:42 UTC, yossizap commented on scripts/r2dec.sh
> +	#cd ..
Is there a reason to keep the comments here and in `scripts/bundle_r2dec.ps1` now that master is used?

2020-09-23 08:15 UTC, wargio commented on scripts/r2dec.sh
> +	#cd ..
i guess is because that one was the working r2dec version? XD

2020-09-23 10:41 UTC, karliss commented on scripts/r2dec.sh
> +	#cd ..
Next time we make a release it will be necessary to lock the version again. The script could be modified at some point to have cleaner config for it, but for now I am leaving this.

2020-09-27 11:07 UTC, ITAYC0HEN requested changes
Nice! I noticed a couple of things:

1. There is no icon to Cutter.exe. I believe that the previous builds had one
2. The Windows console opened after double-clicking `Cutter.exe`. When closing cutter interface, the console is still there. 
![image](https://user-images.githubusercontent.com/20182642/94363430-b67d7080-00ca-11eb-97cd-70ed91890f46.png)

2020-09-30 09:48 UTC, ITAYC0HEN requested changes
r2dec indeed recognized by Cutter now, but I get the following errors
![image](https://user-images.githubusercontent.com/20182642/94670396-2da94380-031b-11eb-9829-96974b377bae.png)

2020-09-30 20:17 UTC, karliss commented
Confirmed r2dec home problem and have a plan for fixing it.

2020-10-03 03:59 UTC, ITAYC0HEN approved these changes
Works, good job :)

2020-10-03 05:36 UTC, yossizap approved these changes

2020-10-03 10:50 UTC, merged