update cmake build docs
rizinorg/cutter pull request #2499
Opened 2020-12-10 05:38 UTC by Surendrajat

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
I've updated cutter building with cmake documentation as per the new dir structure and backend change.

**Test plan (required)**
- Build cutter with cmake
- Build from VS code build/debug option after `Cmake: Configure`

**Closing issues**

2020-12-10 08:03 UTC, XVilka approved these changes

2020-12-11 12:42 UTC, xarkes approved these changes

2020-12-11 12:48 UTC, xarkes requested changes
I followed the instructions
```
$ git clone --recurse-submodules https://github.com/rizinorg/cutter
$ cd cutter
$ mkdir build && cd build
$ cmake -DCUTTER_USE_BUNDLED_RIZIN=ON ../src
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:1 (include):
  include could not find load file:

    QMakeConfigureFile
```

2020-12-11 13:02 UTC, Surendrajat commented
@xarkes you should use `cmake -DCUTTER_USE_BUNDLED_RIZIN=ON ..`

2020-12-11 15:53 UTC, ITAYC0HEN approved these changes

2020-12-11 18:23 UTC, xarkes commented
Yes I am just very bad at reading diffs.

2020-12-11 18:23 UTC, xarkes approved these changes
lgtm

2020-12-11 19:10 UTC, karliss commented on docs/source/building.rst
> +   cmake -S . -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
`-S .` is redundant.

2020-12-12 03:26 UTC, Surendrajat commented on docs/source/building.rst
> +   cmake -S . -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
removed.

2020-12-12 10:54 UTC, karliss approved these changes

2020-12-12 13:29 UTC, merged