Rename radare2 mention to rizin in documentation
rizinorg/cutter pull request #2505
Opened 2020-12-12 13:40 UTC by xarkes

This PR removes any mention to radare2 in the documentation, and fix the various links to the updated locations.

2020-12-12 19:58 UTC, ITAYC0HEN requested changes
Thanks!

I didn't go over all of it, as in the middle I've noticed it is too much.
The idea of most of my reviews is something we agreed on, that the project will be named using "Rizin" (R capitalized) and only the command line utility will be named "rizin" (r lowercased). So unless you are referring to the `$ rizin` command line, to "rizin" (case-sensitive) submodule, it should be used with capital R. 

(putting logo typography decision aside)

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +The recommended way to build Cutter on Linux is by using CMake. Simply invoke CMake to build Cutter and its dependency rizin.
```suggestion
The recommended way to build Cutter on Linux is by using CMake. Simply invoke CMake to build Cutter and its dependency Rizin.
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +* ``CUTTER_ENABLE_DEPENDENCY_DOWNLOADS`` Enable downloading of dependencies. Setting to OFF doesn't affect any downloads done by rizin build. This option is used for preparing Cutter binary release p
```suggestion
* ``CUTTER_ENABLE_DEPENDENCY_DOWNLOADS`` Enable downloading of dependencies. Setting to OFF doesn't affect any downloads done by Rizin build. This option is used for preparing Cutter binary release packages. Turned off by default.
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +* **Rizin's libr_*.so cannot be found when running Cutter**
```suggestion
* **Rizin's librz_*.so cannot be found when running Cutter**
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +The exact rizin .so file that cannot be found may vary. On some systems, the linker by default uses RUNPATH instead of RPATH which is incompatible with the way rizin is currently compiled. It results
```suggestion
The exact Rizin .so file that cannot be found may vary. On some systems, the linker by default uses RUNPATH instead of RPATH which is incompatible with the way Rizin is currently compiled. It results in some of the Rizin libraries not being found when running Cutter. You can verify if this is the problem by running `ldd ./Cutter`. If all the Rizin libraries are missing you have a different problem.
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +The workaround is to either add the `--disable-new-dtags` linker flag when compiling Cutter or add the rizin installation path to LD_LIBRARY_PATH environment variable.
```suggestion
The workaround is to either add the `--disable-new-dtags` linker flag when compiling Cutter or add the Rizin installation path to LD_LIBRARY_PATH environment variable.
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +If you installed rizin and still encounter this error, it could be that your
```suggestion
If you installed Rizin and still encounter this error, it could be that your
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/building.rst
> +You can also install rizin into ``/usr/lib/pkgconfig/`` and then
```suggestion
You can also install Rizin into ``/usr/lib/pkgconfig/`` and then
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +This is the main class where every link with rizin is made. It is *unique*
```suggestion
This is the main class where every link with Rizin is made. It is *unique*
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +Calling a rizin Command
```suggestion
Calling a Rizin Command
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +There are multiple ways to call a rizin command:
```suggestion
There are multiple ways to call a Rizin command: 
```

2020-12-12 19:58 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +  This is the command we used to fetch structured data from rizin.
```suggestion
  This is the command we used to fetch structured data from Rizin.
```

2020-12-14 23:01 UTC, ITAYC0HEN approved these changes

2020-12-15 05:03 UTC, XVilka approved these changes

2020-12-15 08:49 UTC, merged