Apply Qt clang-format configuration
rizinorg/cutter pull request #2513
Opened 2020-12-15 13:25 UTC by ITAYC0HEN

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

|| Work in progress and open-for-discussions ||

This PR applies the Qt clang-format configuration on Cutter's codebase. This includes `.cpp` and `.h` files.
The `_clang-format` file is  https://code.qt.io/cgit/qt/qt5.git/tree/_clang-format which is linked at the top of https://wiki.qt.io/Qt_Coding_Style.

**Test plan (required)**
Compile Cutter and verify that it is running properly

**Closing issues**
closes #2508

2020-12-15 17:43 UTC, karliss commented
Looks better than I expected, many files with only few modified lines.

2020-12-15 17:50 UTC, ITAYC0HEN commented
Yes I felt the same thing. Seems like small changes, nothing overwhelming in most files I went over. I'd prefer to use the file used by Qt, I don't have any special request or suggestion for modification in the cmake file.

Other than that, it compiles correctly. Do you think anything else is needed here?

2020-12-15 18:04 UTC, karliss commented
How well do various IDEs handle when the format is named _clang-format instead of .clang-format? It is mentioned and supported by clang-format itself so it's probably fine, still It wouldn't hurt verifying that.

Developer docs probably need to be updated.

2020-12-15 21:08 UTC, yossizap commented
Can you also add [clang-format-diff.py](https://github.com/rizinorg/rizin/blob/dev/sys/clang-format-diff.py)? It lets you pipe git diff output into clang-format and apply the fixes with -i before committing: 
`git diff dev --unified=0 HEAD^ | ./sys/clang-format-diff.py -p1`

2020-12-15 21:38 UTC, yossizap reviewed
Do we intend to stick to Qt's style settings or can we play around with things like Alignment and spaces? This seems to be a good base but I am not a fan of some of the settings here.

2020-12-15 21:38 UTC, yossizap commented on src/widgets/WidgetShortcuts.h
> +    { "ConsoleWidget", Qt::CTRL + Qt::Key_QuoteLeft }, { "ConsoleWidgetAlternative", Qt::Key_Colon }
I think that it's easier to detect errors and go over code with everything aligned in one column.

2020-12-15 21:38 UTC, yossizap commented on src/widgets/VisualNavbar.h
> +    unsigned int previousWidth = 0;
Maybe add AlignConsecutiveAssignments? No need to manually do it and it looks nicer

2020-12-15 21:38 UTC, yossizap commented on src/widgets/SegmentsWidget.cpp
> +        QColor("#95A5A6") // COBCRETE
AlignTrailingComments?

2020-12-15 21:38 UTC, yossizap commented on src/common/Helpers.h
> +#    define CUTTER_QT_SKIP_EMPTY_PARTS QString::SkipEmptyParts
indent before define intended?

2020-12-15 21:38 UTC, yossizap commented on src/common/PythonAPI.h
> +#    include <Python.h>
indent before include here, maybe it's affected by the ifdef?

2020-12-15 21:38 UTC, yossizap commented on src/common/SettingsUpgrade.cpp
> +#define CUTTER_SETTINGS_VERSION_KEY "version"
AlignConsecutiveMacros will also be cool

2020-12-15 21:38 UTC, yossizap commented on src/common/ColorThemeWorker.cpp
> +        theme[it.key()] = QJsonArray({ r, g, b, a });
Do we want to keep spaces before and after braces? Not a big fan

2020-12-15 21:38 UTC, yossizap commented on src/common/ColorThemeWorker.cpp
> +    "ai.read",    "ai.exec",       "ai.ascii",   "prompt",     "graph.traced"
better as single column imo

2020-12-16 11:11 UTC, XVilka commented
Please rerun/update since the recent renames broke it.

2020-12-23 16:01 UTC, ITAYC0HEN commented on src/widgets/SegmentsWidget.cpp
> +        QColor("#95A5A6") // COBCRETE
This looks very bad when the differences between two lines is so big. For example if row `x` is 60 chars before the comment, and row `x+1` is 20 chars before the comment, the 40 chars indention makes it very hard to notice that there is a comment at all

2020-12-23 16:01 UTC, ITAYC0HEN commented on src/common/Helpers.h
> +#    define CUTTER_QT_SKIP_EMPTY_PARTS QString::SkipEmptyParts
Not sure, if you have format option to send me I'd love to change it

2020-12-23 16:04 UTC, ITAYC0HEN commented
I applied some of the changes suggested. I couldn't find how to make the formatted happy about single line items in the places Yossi referred to ([[1]](https://github.com/rizinorg/cutter/pull/2513#discussion_r543704806), [[2]](https://github.com/rizinorg/cutter/pull/2513#discussion_r543699518)) and I tried different options. Would love help here (CC @thestr4ng3r @karliss @ret2libc )

2020-12-23 18:54 UTC, ret2libc commented
> Can you also add [clang-format-diff.py](https://github.com/rizinorg/rizin/blob/dev/sys/clang-format-diff.py)? It lets you pipe git diff output into clang-format and apply the fixes with -i before committing:
> `git diff dev --unified=0 | ./sys/clang-format-diff.py -p1`

I suggest to actually take the original script because the modifications I did do not work very well in all cases because I had to handle some things myself. If you are just using .clang-format, the original script should work quite well IIRC. https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/clang-format-diff.py

2020-12-25 12:54 UTC, yossizap commented on src/common/Helpers.h
> +#    define CUTTER_QT_SKIP_EMPTY_PARTS QString::SkipEmptyParts
IndentPPDirectives: None

2020-12-25 12:56 UTC, yossizap commented on _clang-format
> +BasedOnStyle: WebKit
You should include the full config by dumping it with `clang-format -dump-config > .clang_format`. Having 'BasedOnStyle' might be cause issues down the line when things change and it's harder to debug which setting messed things up this way.

2020-12-25 13:07 UTC, yossizap commented on src/widgets/SegmentsWidget.cpp
> +        QColor("#95A5A6") // COBCRETE
Maybe we should move the comment above the code in those cases? same line comments should only be in initializations/defines/structs/enums imo.

2020-12-25 13:14 UTC, yossizap commented on src/widgets/WidgetShortcuts.h
> +    { "ConsoleWidget", Qt::CTRL + Qt::Key_QuoteLeft }, { "ConsoleWidgetAlternative", Qt::Key_Colon }
I can't find a way to solve this for brackets

2020-12-25 13:24 UTC, yossizap commented on src/common/ColorThemeWorker.cpp
> +    "ai.read",    "ai.exec",       "ai.ascii",   "prompt",     "graph.traced"
`AllowAllArgumentsOnNextLine: false` and `BinPackArguments: false` but you need to revert initialization to it's original formatting first, otherwise all parameters fit and it won't align them in a single column(I guess that's a positive thing since it lets people leave initializer lists as they were as long as it doesn't go over the `ColumnLimit` if they are too long to be broken down to multiple lines with 1 arg).

2020-12-25 13:35 UTC, karliss commented on _clang-format
> +BasedOnStyle: WebKit
Not sure how much of a problem it is now, but having all options explicit has potential problem when some people are using slightly older or newer version of clang-format. Having unrecognized options (which is a lot more likely if config contains dump of all options) used to be an error.

Checking how well it behaves in range 8-11 might be an interesting test regardless of decision for dumping full config. 8 is latest version available in ubuntu 16.04 repo which is not as bad as I thought.

2020-12-26 03:50 UTC, ITAYC0HEN commented on _clang-format
> +BasedOnStyle: WebKit
this line is from Qt's config

2021-01-02 17:27 UTC, karliss requested changes
Cutter.astylerc  should be removed.

2021-01-02 17:49 UTC, karliss commented on _clang-format
> +BasedOnStyle: WebKit
Did some testing using 8 and 11. There were some differences between 8-11, but using config generated using clang-format-8 with clang-format-11 worked and produce the same result as 8. So I propose following approach:

* -dump-config using clang-format-8 as _clang_format
* save current config in scripts as clang_format_base
* At the top of full config in _clang_format add comment "This file is automatically generated file. Do not edit directly. Edit scripts/clang_format_base instead."
* Create simple "update_clang_format_config.sh" shell script which automates the steps above and maybe checks that you are not trying to update the format using too new clang-format.

2021-01-11 19:27 UTC, xarkes commented
What is the status of this Pull Request? Can we merge it now?

2021-01-11 21:52 UTC, karliss commented
In my opinion it's good enough. Just needs to be reapplied on top of latest master.

2021-01-12 07:49 UTC, ITAYC0HEN commented
Waited for #2561 to be merged, will do it on master tonight

2021-01-16 10:52 UTC, xarkes commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
Do we really want to have this?

2021-01-16 13:21 UTC, ITAYC0HEN commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
I don't mind. @yossizap liked it, and I think it looks nice.

2021-01-16 14:21 UTC, karliss commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
I think it's somewhere between neutral and negative. Biggest potential problem with such automated alignment is that it can introduce a lot of noise and unnecessary conflicts when you modify or add single element but whole list gets updated.

2021-01-16 14:31 UTC, ITAYC0HEN commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
So you think it is better to be removed?

2021-01-16 15:09 UTC, yossizap commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
My thinking was that it's a nice readability improvement but I agree with Karliss. The assignment alignment is the least important alignment for error spotting, if you're against it I don't mind having it removed.

2021-01-16 15:41 UTC, ITAYC0HEN commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
done thx
(actually it was enabled by the other _clang-format so enabling it specifically wasn't meaningful anyways. I disabled it.

2021-01-16 16:57 UTC, karliss commented on scripts/_clang-format
> +AlignConsecutiveAssignments: true
@ITAYC0HEN Other _clang-format needs to be regenerated after modifying the one you modified.

2021-01-17 09:38 UTC, xarkes commented on src/CutterApplication.h
> +    bool enableRizinPlugins       = true;
I don't think it was properly updated, I can still see the alignment here.

2021-01-18 20:02 UTC, karliss commented on src/CutterApplication.h
> +    bool enableRizinPlugins       = true;
See my comment above.

2021-01-18 20:04 UTC, karliss commented on src/CutterApplication.h
> +    bool enableRizinPlugins       = true;
Changing that clang-format file had no effect because it's used for generating full config with all the variables as noted in a comment at the top of it.

2021-01-19 18:29 UTC, xarkes commented on src/CutterApplication.h
> +    bool enableRizinPlugins       = true;
Yeah I it just was a reminder to regenerate the full config and reapply the clang-format, or did I miss something?

2021-01-19 19:06 UTC, ITAYC0HEN commented on src/CutterApplication.h
> +    bool enableRizinPlugins       = true;
No worries Antide, wait for the next iteration, once I will be back on my Linux machine

2021-01-23 15:25 UTC, karliss requested changes

2021-01-23 15:25 UTC, karliss commented on docs/source/contributing/code/ide-setup.rst
> +To configure ``clang-format`` for formatting a file you will need to use the built-in Beautifier plugin. `Follow the instructions <https://doc.qt.io/qtcreator/creator-beautifier.html>`_ on Qt Creator
Specifying _clang-format file manually shouldn't be necessary. It's location is standardized and most tools should use it automatically. It should even work correctly if some subfolders for example rizin submodule has different clang-format.

2021-01-23 15:25 UTC, karliss commented on docs/source/contributing/code/ide-setup.rst
> +To configure ``clang-format`` for formatting a file you will need to use the built-in Beautifier plugin. `Follow the instructions <https://doc.qt.io/qtcreator/creator-beautifier.html>`_ on Qt Creator
Just checked the settings, it looks suspicious. I hope it only gets applied for projects that don't have _clang-format  file. Will need to verify how exactly it behaves.

2021-01-23 15:25 UTC, karliss commented on docs/source/contributing/code/ide-setup.rst
> +To configure ``clang-format`` for formatting a file you will need to use the built-in Beautifier plugin. `Follow the instructions <https://doc.qt.io/qtcreator/creator-beautifier.html>`_ on Qt Creator
It has the file option I guess they replicated the CLI interface precisely.  So that's what developers should use.

2021-01-23 15:25 UTC, karliss commented on docs/source/contributing/code/development-guidelines.rst
> +to format the code. Before sending a pull request, you will need to use `clang-format`<https://clang.llvm.org/docs/ClangFormat.html>`__
It would be good to note that config is compatible with clang-format-8 or newer.

2021-01-23 15:45 UTC, ITAYC0HEN commented on docs/source/contributing/code/development-guidelines.rst
> +to format the code. Before sending a pull request, you will need to use `clang-format`<https://clang.llvm.org/docs/ClangFormat.html>`__
```suggestion
to format the code. Before sending a pull request, you will need to use `clang-format`<https://clang.llvm.org/docs/ClangFormat.html>`__ (Version 8 or newer)
```

2021-01-23 18:43 UTC, karliss commented on docs/source/contributing/code/ide-setup.rst
> +To configure ``clang-format`` for formatting a file you will need to use the built-in Beautifier plugin. `Follow the instructions <https://doc.qt.io/qtcreator/creator-beautifier.html>`_ on Qt Creator
Tested it, choosing option "Use predefined style: File" works as described in clang-format docs. There isn't even an option to manually specify config file from Cutter's root directory unless you copy paste it.

2021-01-24 14:55 UTC, karliss approved these changes

2021-01-24 16:34 UTC, merged