refactor DisassemblyLeftPanel::paintEvent
rizinorg/cutter pull request #2559
Opened 2021-01-09 03:08 UTC by optizone

**Detailed description**
About two years ago I wrote the algorithm of calculating layers of jump arrows. It was kinda ugly and I didn't understand how it worked (+ it didn't in some corner cases), so I promised myself to refactor it someday. 

Well, this day has come.

This new algorithm roughly x2 faster, which speeds up whole `DisassemblyLeftPanel::paintEvent` by ~10%. (I made some changes to algorithm after benchmarking, but I'm sure it didn't affect performance much)
I replaced QMap with std::vector, because in this case it's faster to use binary search or brute search than map search because all vector data fits in L1 cache.  
 
Also I changed standard to C++17, because I needed `auto` in lambda parameters. This is C++14 feature, but if we changing standard, why not use newer one?

**Test plan (required)**
some screenshots (binary - /usr/bin/ls):
![Screenshot_20210109_055221](https://user-images.githubusercontent.com/42874998/104081308-d9c5c900-523e-11eb-9db8-3f307dff8040.png) ![Screenshot_20210109_055246](https://user-images.githubusercontent.com/42874998/104081315-e9dda880-523e-11eb-957f-be16f83d6ab0.png) ![Screenshot_20210109_055323](https://user-images.githubusercontent.com/42874998/104081330-feba3c00-523e-11eb-9e68-2c78f6f09d1b.png)

versus old algorithm:
 
![Screenshot_20210109_055524](https://user-images.githubusercontent.com/42874998/104081397-50fb5d00-523f-11eb-9725-50c72122395d.png) ![Screenshot_20210109_055441](https://user-images.githubusercontent.com/42874998/104081379-3923d900-523f-11eb-85d1-bdd7b41c7b95.png) ![Screenshot_20210109_055619](https://user-images.githubusercontent.com/42874998/104081415-6b353b00-523f-11eb-8d8b-f4dad803d506.png)

As you can see, new algorithm produces a littler bit prettier results (+ is easier to understand why). 

P.S.
Is it possible to know all jumps on analysis stage, so we can call this algorithm only once and then just draw visible arrows?
Because now arrows appear and disappear while scrolling, and this is a bit annoying, especially if jump is longer than disassembly listing (arrow will simply disappear before you see where it leads).

2021-01-09 07:27 UTC, karliss requested changes

2021-01-09 07:27 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +        linesPixPosition.emplace_back(lines[i].offset, i * lineHeight + lineHeight / 2 + topOffset);
Better keep position in rows here, and do the pixel calculation during drawing.

2021-01-09 07:27 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +        for (it = std::begin(arrows), end = std::end(arrows); !exit; increment()) {
Just do:
```cpp
while (changedAtLeastOne) {
    for (it = std::begin(arrows), end = std::end(arrows); it != end; it++) {
}
}
```
It's shorter and much easier to understand. Although I have even better suggestion, will describe it later.

2021-01-09 07:27 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +                [&](const auto& acc, const Arrow& it2) {
I suggest typedefing your pair, that way you won't need lambda with auto arg here.

2021-01-09 07:27 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +            return offset == res->first ? std::optional{ res } : std::nullopt;
I suggest returning `std::end(linesPixPosition)` in case of result not found here instead of optional that way it will be consistent with standard library search functions and  won't need half a paragraph of comment explaining usage of optional.

You are also potentially dereferencing invalid iterator when lower_bound returns end iterator.

A

2021-01-09 07:27 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +            : (endVisible = false, (arrow->reversed ? 0 : geometry().bottom())); // destination isn't on screen
Please don't abuse ternary operator + coma operator. If you need anything more complex than single expression in ternary operator just use a proper if statement.

2021-01-09 07:50 UTC, karliss commented
>  Is it possible to know all jumps on analysis stage, so we can call this algorithm only once and then just draw visible arrows?

I don't think it's a good idea.
* I would expect there  to be sufficient amount of jumps going across half the executable to turn the resulting drawing into mess. 
* Your  algorithm has  quadratic time based on number number of arrows so it's unsuitable for use beyond current screen.
* Current version works without analysis and while looking at other libraries during debugging. 

Better approach in my opinion would be:
* keep a list of arrows from previous drawing
* remove arrows for which both ends are either before or after the screen

It would address the main concern of arrows not disappearing while you scroll, without extra much noise by extra arrows you probably don't want to see.

2021-01-09 08:21 UTC, karliss commented
I don't think it's worth concerning about performance here. You have to try really hard to make processing of 10-30 arrows slow. As you said yourself improving the performance of line position calculations 2x improved the paintEvent by only 10%. So even if it was optimized to nothing it would barely change anything and current state is fast enough. Especially if in some situations like debugging can make things 100x slower due to IO layer and how disassembly printing in rizin works which is actually be observed.

With that I didn't meant that I am against this PR or cleaning up line drawing, only that readability for this part of code is lot more important here than performance since it is far from being the bottleneck.

2021-01-09 11:21 UTC, karliss commented
> Although I have even better suggestion, will describe it later.

Here is my take on this https://github.com/karliss/cutter/commit/79e506b75505560266b6e3d784f74bf8946e42d3

2021-01-09 14:04 UTC, ITAYC0HEN commented
thanks for the PR! Glad to have you back 👍  :)
A slightly related issue to the things you discussed: https://github.com/rizinorg/cutter/issues/507

2021-01-09 14:27 UTC, optizone commented
> > Although I have even better suggestion, will describe it later.
> 
> Here is my take on this [karliss@79e506b](https://github.com/karliss/cutter/commit/79e506b75505560266b6e3d784f74bf8946e42d3)
> It doesn't have the case where it put's lines at level 1 when minimum is > 1, but it didn't observe many cases where it was needed. It could be added by adding variation of tree which tracks min and max.

Other reason I wanted to refactor this code is that I wanted arrows to be more organized, and while your proposal seems more readable, arrows look more chaotic in cases when there is a bunch of them:
![ks](https://user-images.githubusercontent.com/42874998/104093791-e0375d80-529d-11eb-80f3-a136b6ebf08a.png) ![kh2](https://user-images.githubusercontent.com/42874998/104093802-f3e2c400-529d-11eb-8c67-f9d4d3ef1d64.png)
versus
![ms](https://user-images.githubusercontent.com/42874998/104093810-ffce8600-529d-11eb-8130-7ea5d9e4ddf8.png) ![mh2](https://user-images.githubusercontent.com/42874998/104093813-03faa380-529e-11eb-8d9f-0a5d08e700b8.png)

New algorithm arranges arrows based on their maximum offset, so it isn't as nice as it could be, but I know how to make arrows look good. (Just didn't have time to implement yet).
And I think that it is better to have nice looking arrows, than nice looking code. What do you think?

Thanks for feedback, will commit changes in the couple of days.

P.S. 
I agree that performance in this case isn't that important, just wanted to flex a bit :)

2021-01-09 14:29 UTC, optizone commented on src/widgets/DisassemblyWidget.cpp
> +        for (it = std::begin(arrows), end = std::end(arrows); !exit; increment()) {
Agree, for some reason I couldn't think of this

2021-01-09 14:33 UTC, optizone commented on CMakeLists.txt
> -set(CMAKE_CXX_STANDARD 11)
Ok, but just curious why? What platforms don't have 3-4 years old compilers?

2021-01-09 14:51 UTC, optizone commented on CMakeLists.txt
> -set(CMAKE_CXX_STANDARD 11)
And... what about C++14 then?

2021-01-09 16:13 UTC, optizone commented on src/widgets/DisassemblyWidget.cpp
> +            return offset == res->first ? std::optional{ res } : std::nullopt;
yeah, but `std::end(linesPixPosition)` is being returned only if `offset` is less than `linesPixPosition[i].offset`, which is not possible, because `offset` is passed from `lines`, and `linesPixPosition` is created from `lines`

2021-01-09 20:50 UTC, karliss commented
Update my branch to produce arrow order which is closer to what this branch does. I slightly preferred the result of ordering by size instead of end and start as it seemed to produce more compact layout.

One case your branch currently doesn't handle is this:
![image](https://user-images.githubusercontent.com/7101031/104108380-d842e200-52cc-11eb-93ec-e8d9733e4e7c.png)

2021-01-09 21:17 UTC, optizone commented
Yeah, I didn't push these changes yet, but it does (your on the right):
![my_s](https://user-images.githubusercontent.com/42874998/104108624-4be9ec80-52d7-11eb-90bf-9eb52929bda2.png) ![Screenshot_20210110_000224](https://user-images.githubusercontent.com/42874998/104108627-4f7d7380-52d7-11eb-8b51-d1ae71e52c75.png)

> I slightly preferred the result of ordering by size instead of end and start as it seemed to produce more compact layout.

Compact doesn't always mean easier to look at, but anyways, that's the matter of taste.

And (just m opinion, dunno) it it is better when intersection of one type of arrows (up or down) happens on at the end, not the beginning. For instance, in your example arrows going from `0x5f94` `0x5f96` `0x5f98` `0x5f9a` should have 4th, 3rd, 2nd and 1st layers respectively (now it is 1,4,2,3).

2021-01-09 21:40 UTC, optizone commented
I thought that I should maybe push these changes, so you can look at results yourself

2021-01-09 22:30 UTC, karliss commented
> And (just m opinion, dunno) it it is better when intersection of one type of arrows (up or down) happens on at the end, not the beginning. For instance, in your example arrows going from 0x5f94 0x5f96 0x5f98 0x5f9a should have 4th, 3rd, 2nd and 1st layers respectively (now it is 1,4,2,3).

Yes, that's why I was showing a screenshot with output from your last version to remind you that your last version didn't handle it. Both versions I suggested produce 4, 3, 2, 1

2021-01-09 23:16 UTC, karliss commented
The biggest change in your last version was placing downward arrows to the right of upward arrows. If that's what you like it can be achieved.

Mine on the left, yours on the right.

![image](https://user-images.githubusercontent.com/7101031/104110347-8b1c3b80-52df-11eb-9aa6-40658772196f.png)

Downside of such choice is doing this:
![image](https://user-images.githubusercontent.com/7101031/104110550-5f01ba00-52e1-11eb-82b9-a0d19f9ec068.png)

2021-01-10 07:41 UTC, ITAYC0HEN commented
Side note: I like it when the arrows aren't **completely** merged together, so you can see that there are more than one entries to this address

![image](https://user-images.githubusercontent.com/20182642/104117175-f1c54780-5327-11eb-9271-70b9ca15db6c.png)

2021-01-10 11:36 UTC, optizone commented
> If that's what you like it can be achieved (2 lines of changes).

yeah, can you push these changes, please? 

> Side note: I like it when the arrows aren't completely merged together, so you can see that there are more than one entries to this address

About that. There are two approaches: separate all arrows and separate only up and down arrows.
With first approach it can be very noisy (in case there are more than 5 arrows to/from the same offset) and is harder to implement. So I choose second one (draw all upward arrows one pixel below the center of line and all downward ones - one pixel above)

2021-01-10 13:58 UTC, karliss commented
>yeah, can you push these changes, please?

Already pushed yesterday in the same branch. You can use link above.

2021-01-10 14:13 UTC, karliss commented
> With first approach it can be very noisy
I agree that everything separately would be too noisy. What about case where there are edge going both to and from current line? I guess that would mean jump to jump which compiler could optimize, so it probably won't happen too often and isn't worth handling such case during drawing. Jump to instruction with conditional jump can make sense even in optimized compiler generated code so  it might appear sometimes. From quick look at `ls` I was able to notice only one such jump out of few dozens.

2021-01-10 14:29 UTC, optizone commented
Well, if you draw all both beginning and ending with a margin, then these cases will be handled, I just use `i * lineHeight + lineHeight / 2 + topOffset + int(up ? pixelRatio : -pixelRatio);` to calculate Y position of arrow.

2021-01-10 14:31 UTC, optizone commented
sorry about that

2021-01-10 14:34 UTC, optizone commented
> From quick look at ls I was able to notice only one such jump out of few dozens.

Well, we can use more complex algorithm to catch these cases, I'll look into it.

2021-01-13 18:19 UTC, karliss commented
> Well, we can use more complex algorithm to catch these cases, I'll look into it.

Not sure i understood. Handling it in code wouldn't be difficult. The simplest approach could be +- 1 for arrows going from top and bottom and +0 for arrows going out. I was just expressing doubts if it's worth adding extra code if in most cases it won't make a difference, and in cases where it makes a difference it wouldn't be that much worth without it.

2021-01-15 15:17 UTC, optizone commented
No, I mean, it looks ugly if you use +-1 for in and +0 for out, because they just merge together, but if you use +-2 and +0, it looks ugly in regular cases when there are only 2 or 1 arrow at offset, so if you want for it to be pretty in all cases, you want to handle case with 3 arrows differently. But I agree that it isn't worth it, so I'll leave code how it is.

2021-01-16 12:24 UTC, karliss commented on CMakeLists.txt
> -set(CMAKE_CXX_STANDARD 11)
>  What platforms don't have 3-4 years old compilers?

Start by taking a look at CI builds you broke. Main goal currently is being able to easily compile on Ubuntu 16.04 at least in basic config without third party repos or significant hassle. Having a look at bigger picture there are  plenty of popular distros for which supported LTS versions recently had ~GCC 4.8. That is slightly older than what Ubuntu 16.04 has, but it was able to compile Cutter on them due to the C++11 target. And there were occasional PRs from people using such distro.

2021-01-16 12:39 UTC, karliss commented
Scrolling up sometimes produces this. If I scroll down it disappears and when I scroll up it reappears.
![image](https://user-images.githubusercontent.com/7101031/104812072-6e649400-5808-11eb-80ce-e6ca5f65b29b.png)

2021-01-16 12:59 UTC, optizone commented
> Scrolling up sometimes produces this. If I scroll down it disappears and when I scroll up it reappears.

Didn't notice first time.
That's because DisasemblyWidget doesn't draw first and last few lines:
![Screenshot_20210116_155532](https://user-images.githubusercontent.com/42874998/104812459-4dee0700-5813-11eb-99b2-853708f24600.png)
![Screenshot_20210116_155625](https://user-images.githubusercontent.com/42874998/104812474-7aa21e80-5813-11eb-814a-50575b06d5df.png)

Is that what you are talking about?

2021-01-16 13:24 UTC, karliss commented
> Is that what you are talking about?

No take a look at screenshot. That large amount of arrows isn't supposed to go there. I assume it's caused by combination of arrow caching and handling of arrows fully outside screen or something like that.

2021-01-16 13:30 UTC, karliss commented
With arrow caching it's time to reconsider sorting strategy. Since there are a lot more arrows being remembered, down arrows always being to the right of up arrows, are more likely to cause short arrows being hidden by long arrows going across the screen. Sorting by length deals a lot better with that, but previously you pointed out that it looks messier when there are only short arrows all fitting within screen. 

One approach I tried was to prioritize arrows fully within screen, and then using one of the orders discussed above. It wasn't bad when looking at static image but introduced a lot of instability as you scrolled. Similar result without scrolling instability was obtained by instead having 1 bit length check -> is arrow shorter than height of screen.

2021-01-16 13:40 UTC, karliss commented
Here one more screenshot comparing different approaches. It doesn't demonstrate the bad case mentioned above, but is otherwise interesting location. If I remember correctly thats:
* up, max, min
* length
* max, min
* (length < screen_height), max, min
![image](https://user-images.githubusercontent.com/7101031/104813127-dec2e380-580f-11eb-972f-1fb882105b89.png)

2021-01-16 13:48 UTC, karliss commented
Here example where up,max,min order behaves especially bad in combination with arrow caching.
![Screenshot from 2021-01-16 15-44-22](https://user-images.githubusercontent.com/7101031/104813448-01ee9280-5812-11eb-95c1-1d5a21cdb86f.png)

2021-01-16 14:18 UTC, optizone commented
So, I pushed some changes, which hopefully will fix this https://github.com/rizinorg/cutter/pull/2559#issuecomment-761557129. I couldn't reproduce this behavior so this fix is based only on my assumptions why it happened. + I switch back to C++11 and now there are some issues with MinMaxAccumulateTree (undefined reference to MinMaxAccumulateTree::LIMITS). Can you, please, take a look at it and push one of the [max, min] or [(length < screen_height), max, min] approaches?

P.S. now I decided to flush cache in case we hit some threshold of used levels, should we keep this behavior?

2021-01-16 14:41 UTC, karliss commented
Will take a look at the LIMITS issue. Under what conditions did you get undefined reference? It fails in CI but differently.

2021-01-18 09:09 UTC, optizone commented
> Will take a look at the LIMITS issue. Under what conditions did you get undefined reference? It fails in CI but differently.

Sorry for the delay. 
The build output:
`[build] /usr/bin/ld: src/CMakeFiles/Cutter.dir/widgets/DisassemblyWidget.cpp.o: in function`
`«MinMaxAccumulateTree::MinMaxAccumulateTree(unsigned long, std::pair<unsigned long long, unsigned long long>)»:`
`[build] /home/optizone/code/cutter/build/../src/common/BinaryTrees.h:461: undefined reference to «MinMaxAccumulateTree::LIMITS»`

2021-01-18 09:22 UTC, optizone commented
funny thing is that clang compiles this just fine, but gcc does not

2021-01-18 19:59 UTC, karliss commented
> Sorry for the delay. The build output:

I asked how did you obtained it not what the error was you already posted that before. What platform, toolchain any other information else, build system commands used?

2021-01-18 20:27 UTC, optizone commented
OS: Arch x64 (5.10.3-arch1-1)

Toolchain:
gcc (GCC) 10.2.0
g++ (GCC) 10.2.0
GNU ld (GNU Binutils) 2.35.1

Configure:
`/usr/bin/cmake --no-warn-unused-cli -DCUTTER_USE_BUNDLED_RIZIN:STRING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -H/home/optizone/code/cutter -B/home/optizone/code/cutter/build -G Ninja`

Build:
`/usr/bin/cmake --build /home/optizone/code/cutter/build --config Release --target all -- -j 16`

Command that was used to compile DisassemblyWidget.cpp:
`/usr/bin/g++ -DCUTTER_ENABLE_GRAPHVIZ -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING -DCUTTER_SOURCE_BUILD -DCutter_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Isrc -I../src -Isrc/Cutter_autogen/include -I../src/core -I../src/widgets -I../src/common -I../src/plugins -I../src/menus -I../src/. -IRizin-prefix/include/librz -IRizin-prefix/include/librz/sdb -isystem /usr/include/graphviz -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtNetwork -isystem /usr/include/KF5/KSyntaxHighlighting -isystem /usr/include/KF5 -O3 -DNDEBUG -fvisibility=hidden -Wall -Wextra -fPIC -std=gnu++11 -o src/CMakeFiles/Cutter.dir/widgets/DisassemblyWidget.cpp.o -c /home/optizone/code/cutter/src/widgets/DisassemblyWidget.cpp`

ld command:
`/usr/bin/g++ -O3 -DNDEBUG -Wl,--export-dynamic -rdynamic ~~a bunch of .o files like src/CMakeFiles/Cutter.dir/widgets/DisassemblyWidget.cpp.o~~ -o Cutter -L/home/optizone/code/cutter/build/Rizin-prefix/lib -Wl,-rpath,/home/optizone/code/cutter/build/Rizin-prefix/lib:  /usr/lib/libQt5Svg.so.5.15.2  /usr/lib/libKF5SyntaxHighlighting.so.5.77.0  /usr/lib/libgvc.so  /usr/lib/libcgraph.so  /usr/lib/libcdt.so  /usr/lib/libQt5Widgets.so.5.15.2  -lrz_core  -lrz_config  -lrz_cons  -lrz_io  -lrz_util  -lrz_flag  -lrz_asm  -lrz_debug  -lrz_hash  -lrz_bin  -lrz_lang  -lrz_io  -lrz_util  -lrz_flag  -lrz_asm  -lrz_debug  -lrz_hash  -lrz_bin  -lrz_lang  -lrz_analysis  -lrz_parse  -lrz_bp  -lrz_egg  -lrz_reg  -lrz_search  -lrz_syscall  -lrz_socket  -lrz_magic  -lrz_crypto  /usr/lib/libQt5Gui.so.5.15.2  /usr/lib/libQt5Network.so.5.15.2  /usr/lib/libQt5Core.so.5.15.2`

Error:
`DisassemblyWidget.cpp:(.text+0x32cc): undefined reference to «MinMaxAccumulateTree::LIMITS»`

2021-01-19 17:33 UTC, karliss commented
@optizone Pushed a fix for arch, will see if it also helps macOS CI. Also pushed the [(length < screen_height), max, min] order.

2021-01-25 09:13 UTC, ITAYC0HEN commented
> @optizone Pushed a fix for arch, will see if it also helps macOS CI. Also pushed the [(length < screen_height), max, min] order.

still failing

2021-01-25 20:54 UTC, karliss commented
@ITAYC0HEN Pushed to my branch, I don't have permissions pushing to optione repository. Or did you try building my branch?

2021-01-25 20:55 UTC, ITAYC0HEN commented
I think should have permissions to push to forks' branches because you're an admin. If not maybe this can be fixed somehow

2021-01-27 01:18 UTC, optizone commented
> still failing

yeah, sorry, my bad, forgot that I should push these changes.

> Scrolling up sometimes produces this. If I scroll down it disappears and when I scroll up it reappears.

Does this bug still appears? I can't reproduce. If it does, can you please attach the binary and offset?

It doesn't want to start CI because of conflicts. I merged `rizin:master` then remembered that you don't like merges in pull requests, so I did force push to go back and then rebased on `rizin:master` and did another force push.

2021-01-27 15:54 UTC, karliss commented
> Does this bug still appears? I can't reproduce. If it does, can you please attach the binary and offset?
No your attempt fixing it helped.

2021-01-29 18:26 UTC, ITAYC0HEN commented
What's the current status then? :)

2021-01-31 11:09 UTC, optizone commented
> What's the current status then? :)

I noticed one bug, will fix and I think it's done

2021-02-11 11:00 UTC, ITAYC0HEN approved these changes
I think it looks great :)
Good work @optizone  and @karliss !

2021-02-11 21:18 UTC, optizone commented
Should I squash all the commits?

2021-02-15 06:46 UTC, merged

2021-02-15 06:47 UTC, ITAYC0HEN commented
Thank you! VEry exciting about this improvement :)
@karliss I will be happy if you can test and even though it was merged, just in case we missed anything before your final approval <3