New JSDec home
rizinorg/cutter pull request #2563
Opened 2021-01-13 07:39 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Since @wargio updated the [jsdec]() repository recently with some renaming, fixing it in Cutter too.

**Test plan (required)**

All green.

**Closing issues**

Closes https://github.com/rizinorg/cutter/issues/2549

2021-01-13 08:22 UTC, karliss commented
Does it actually works now or does it still need changes on decompiler side? Can it now be renabled in CI builds?

2021-01-13 09:46 UTC, XVilka commented
@karliss  I enabled JSDec in CI, seems to work.

2021-01-13 10:56 UTC, karliss commented
Probably needs a separete issue created for making sure its packed correctly on macOS. I didn't do it during my last macOS packaging PR since it couldn't be compiled then.

2021-01-13 19:28 UTC, karliss commented
Tested the windows build. jsdec is properly packaged and works in console widget but it is not listed in decompiler widget due to `e cmd.pdc` being removed. `JSDecDecompiler::isAvailable` needs to be adjusted.  Something like `cmdList("es").contains("jsdec")` is probably good enough as quick fix.

2021-01-14 12:26 UTC, XVilka commented
@karliss just tested that package for Windows and `jsdec` seems to work out of the box.

2021-01-14 12:44 UTC, wargio approved these changes

2021-01-14 15:47 UTC, karliss requested changes

2021-01-14 15:47 UTC, karliss commented on .github/workflows/ccpp.yml
> +          # "../scripts/jsdec.sh" --prefix=`pwd`/appdir/usr
You can try uncommenting this to enable jsdec for appimage build.

2021-01-16 09:17 UTC, karliss approved these changes

2021-01-16 10:47 UTC, xarkes approved these changes

2021-01-16 10:48 UTC, merged