Update Windows building instructions
rizinorg/cutter pull request #2590
Opened 2021-02-11 10:53 UTC by ITAYC0HEN

**Detailed description**
The Windows building instructions were outdated since we moved to Rizin. These changes not only make them up-to-date, but also improve them

2021-02-11 13:26 UTC, Surendrajat requested changes
I like the PowerShell approach. Hope we can put a simple `winget` command someday for the dependencies list :)

2021-02-11 13:26 UTC, Surendrajat commented on docs/source/building.rst
>  Recommended Way
Since it is the only way to build now...
```suggestion
Building Steps
```

2021-02-11 13:29 UTC, Surendrajat commented on docs/source/building.rst
> +If they are not available, you can use PowerShell to add them to your path one by one:
```suggestion
If they are not available, you can use PowerShell to add them to your PATH one by one:
```

2021-02-11 13:29 UTC, Surendrajat commented on docs/source/building.rst
> +* `Qt <https://www.qt.io/download-qt-installer>`_
Do we need to specify Qt5 here? I think we're not Qt6 ready yet which the installer might suggest/default to.

2021-02-11 13:44 UTC, ITAYC0HEN commented on docs/source/building.rst
> +* `Qt <https://www.qt.io/download-qt-installer>`_
```suggestion
* `Qt 5 <https://www.qt.io/download-qt-installer>`_
```

2021-02-11 13:49 UTC, Surendrajat approved these changes

2021-02-11 13:59 UTC, yossizap commented on docs/source/building.rst
> +   cmake -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
Maybe we should also include instructions for python bindings using cutter-deps? It's a basic functionality

2021-02-11 14:48 UTC, ITAYC0HEN commented on docs/source/building.rst
> +   cmake -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
I agree it is basic but I never tried it myself. Do we have any instructions for this anywhere? if no, can you draft something and push to this branch?

2021-02-11 21:57 UTC, yossizap commented on docs/source/building.rst
> +   cmake -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
I am currently having issues with windows builds on the latest commit but you can my `build.bat` which was based on the CI:

```
scripts/fetch_deps.sh # you'll need some type of bash for windows(or just manually download the zip from releases and extract) but this also replaces installing full Qt
set ARCH=x64
set CUTTER_DEPS=%CD%\cutter-deps
set PATH=%CD%\cutter-deps\qt\bin;%PATH%
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
mkdir build
cd build
set PACKAGE_NAME=cutter-git-x64.Windows
cmake ^
          -DCMAKE_BUILD_TYPE=Debug ^
          -DCUTTER_USE_BUNDLED_RIZIN=ON ^
          -DCUTTER_ENABLE_PYTHON=ON ^
          -DCUTTER_ENABLE_PYTHON_BINDINGS=ON ^
          -DCUTTER_ENABLE_PACKAGING=ON ^
          -DCUTTER_PACKAGE_DEPENDENCIES=ON ^
          -DCUTTER_PACKAGE_RZ_GHIDRA=ON ^
          -DCUTTER_PACKAGE_JSDEC=ON ^
          -DCUTTER_ENABLE_DEPENDENCY_DOWNLOADS=ON ^
          -DCUTTER_ENABLE_CRASH_REPORTS=OFF ^
          -DCMAKE_PREFIX_PATH="%CUTTER_DEPS%\pyside" ^
          -DCPACK_PACKAGE_FILE_NAME=%PACKAGE_NAME% ^
          -G Ninja ^
          .
cmake --build . --config Debug
cmake --build . --config Debug --target package
```
the result is in `_CPack_Packages\win64\ZIP\cutter-git-x64.Windows`

2021-02-13 09:25 UTC, ITAYC0HEN commented on docs/source/building.rst
> +   cmake -B build -DCUTTER_USE_BUNDLED_RIZIN=ON
I failed :<

2021-02-18 14:35 UTC, merged