Enable CUTTER_USE_BUNDLED_RIZIN by default
rizinorg/cutter pull request #2622
Opened 2021-03-05 10:25 UTC by ITAYC0HEN

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Users and devs are more likely to want to build Cutter with -DCUTTER_USE_BUNDLED_RIZIN enabled. Moreover, it is usually our recommendation and the changes in the docs are a proving this.

I kept some references to `CUTTER_USE_BUNDLED_RIZIN=ON` in a couple of places just for the sake of giving a fuller picture to the reader of these building scripts.

**Test plan (required)**

- CI should pass
- Build with `cmake ..` and see that everything is good

2021-03-05 17:40 UTC, Surendrajat approved these changes
Tried on Ubuntu 18.04 and it works fine.

2021-03-10 09:47 UTC, XVilka commented
A good addition to 2.0.0 too, I think.

2021-03-13 13:09 UTC, karliss commented
Additional documentation changes:
* add link for downloading CI builds
* link to IDE setup from building page
* Explain when you might want to disable CUTTER_USE_BUNDLED_RIZIN and other details relevant for package maintainers.

2021-03-13 13:12 UTC, karliss approved these changes
@ITAYC0HEN Please proofread my documentation changes. With the note to packagers I am willing to accept changes in default behavior.

2021-03-13 13:37 UTC, Surendrajat requested changes

2021-03-13 13:37 UTC, Surendrajat commented on docs/source/building.rst
> + `CI page <https://github.com/rizinorg/cutter/actions/workflows/ccpp.yml?query=branch%3Amaster>`_ (requires logging in) for latest development builds.
@karliss can we instead use https://nightly.link for linking dev builds? It doesn't require logging in and offers clean download page for all artifacts.
```suggestion
 `CI page <https://nightly.link/rizinorg/cutter/workflows/ccpp/master>`_ for latest development builds.
```

2021-03-13 13:37 UTC, Surendrajat commented on docs/source/building.rst
> +When making a distribution specific packages the default install target should give you a good starting point.
```suggestion
When making a distribution specific package, the default install target should give you a good starting point.
```

2021-03-13 15:30 UTC, ITAYC0HEN commented on docs/source/building.rst
> +This page describes how to do basic build from command line. If you are planning to modify Cutter it is recommended to also read :doc:`development environment setup</contributing/code/ide-setup>`.
```suggestion
This page describes how to do a basic build from the command line. If you are planning to modify Cutter it is recommended to also read our :doc:`development environment setup</contributing/code/ide-setup>`.
```

2021-03-13 15:31 UTC, ITAYC0HEN commented on docs/source/building.rst
> +It uses CMake builtin functionality and `GNUInstallDirs <https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html?highlight=gnu%20directories>`_ for
```suggestion
It uses CMake built-in functionality and `GNUInstallDirs <https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html?highlight=gnu%20directories>`_ for
```

2021-03-13 15:32 UTC, ITAYC0HEN commented on docs/source/building.rst
> +installing the executable, desktop file, headers and other files required for plugin compilation. See CMake documentation for adjusting installed file locations and properties.
optional: link to cmake docs?

2021-03-13 15:32 UTC, ITAYC0HEN commented on docs/source/building.rst
> +It is recommended to build and package rizin as separate package so that it can be used with or without Cutter. Doing that will also give more control over the way rizin dependencies are handled. We
```suggestion
It is recommended to build and package rizin as a separate package so that it can be used with or without Cutter. Doing that will also give more control over the way dependencies are handled. We are trying to maintain
```

2021-03-13 15:33 UTC, ITAYC0HEN commented on docs/source/building.rst
> +If you are packaging Cutter users will appreciate if you also package `rz-ghidra <https://github.com/rizinorg/rz-ghidra>`_ and `jsdec <https://github.com/rizinorg/jsdec>`_ decompilers as optional pac
```suggestion
If you are packaging Cutter, users will appreciate it if you also package `rz-ghidra <https://github.com/rizinorg/rz-ghidra>`_ and `jsdec <https://github.com/rizinorg/jsdec>`_ decompilers as optional packages.
```

2021-03-13 15:34 UTC, ITAYC0HEN commented on docs/source/building.rst
> +If name Cutter or cutter conflicts with other packages or their content, rz-cutter can be used.
```suggestion
If the names "Cutter" or "cutter" conflict with other packages or their content, "rz-cutter" can be used.
```

2021-03-13 15:35 UTC, ITAYC0HEN commented on docs/source/building.rst
> +* ``CUTTER_EXTRA_PLUGIN_DIRS`` use it to specify additional plugin search locations if distro packaging guidelines require you placing them in locations Cutter doesn't use by default.
@karliss, duplication? (lines 201+)

2021-03-13 15:48 UTC, karliss commented on docs/source/building.rst
> +installing the executable, desktop file, headers and other files required for plugin compilation. See CMake documentation for adjusting installed file locations and properties.
Are you referring to
> It uses CMake built-in functionality 

or 
> See CMake documentation

In both cases there is no single part of documentation to link since there at least a dozen different options controlling various aspects of file installation.

2021-03-13 15:53 UTC, karliss commented on docs/source/building.rst
> +* ``CUTTER_EXTRA_PLUGIN_DIRS`` use it to specify additional plugin search locations if distro packaging guidelines require you placing them in locations Cutter doesn't use by default.
I don't think that some overlap with option description at bottom is bad here. General description of  options and listing options relevant for specific uses case with explanation why we recommend changing them are two different things.

2021-03-13 16:06 UTC, ITAYC0HEN commented on docs/source/building.rst
> +installing the executable, desktop file, headers and other files required for plugin compilation. See CMake documentation for adjusting installed file locations and properties.
the latter. Alright then :)

2021-03-13 16:09 UTC, ITAYC0HEN commented on docs/source/building.rst
> +* ``CUTTER_EXTRA_PLUGIN_DIRS`` use it to specify additional plugin search locations if distro packaging guidelines require you placing them in locations Cutter doesn't use by default.
> General description of options and listing options relevant for specific uses case with explanation why we recommend changing them are two different things

Two different things that  can be combined. For example

```
**<Config name>**
[Laconic description]
[Recommendations and personal notes]

```

2021-03-13 16:43 UTC, karliss commented on docs/source/building.rst
> + `CI page <https://github.com/rizinorg/cutter/actions/workflows/ccpp.yml?query=branch%3Amaster>`_ (requires logging in) for latest development builds.
I am hesitant on giving links to small third party service as primary link for downloading executables. Users can use such services if they want but that would have to be their own choice.

* dev-builds aren't critical there is always option to use release package or compile yourself
* everyone participating in development or reporting issues already have a GitHub account
* If you don't have GitHub account because you don't trust them you shouldn't blindly trust nightly.link either especially without means of verifying origin of what you download.

2021-03-14 09:43 UTC, karliss commented on docs/source/building.rst
> +* ``CUTTER_EXTRA_PLUGIN_DIRS`` use it to specify additional plugin search locations if distro packaging guidelines require you placing them in locations Cutter doesn't use by default.
I still disagree. It doesn't help anyone. For people who are not packagers, it add extra text they are not interested in, making them even less likely to read anything. Also some the recommendations might be completely opposite of their use-case.  As for people doing packaging it splits the information into multiple places making it easier to miss the important parts. Single  motivation might apply to group of options. That allows doing:
```
Use case X:
* Due to `Y` keep `A` `B` `C` on.
* Turn off `E` `F` due to `Z`

General option description
* A - does a
* B - does b
* C - does c
```

Instead of producing different kind of duplication
```
* Option  A - does a. In use case `X` due to `Y` turn on.
* Option  B - does b. In use case `X` due to `Y` turn on.
* Option  C - does c. In use case `X` due to `Y` turn on.
```

2021-03-15 04:46 UTC, Surendrajat approved these changes

2021-03-15 04:47 UTC, merged