Add missing copyright information
rizinorg/cutter pull request #2653
Opened 2021-03-31 03:29 UTC by TAbhay

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2021-03-31 04:16 UTC, XVilka requested changes

2021-03-31 04:16 UTC, XVilka commented on .reuse/dep5
> +# Sample paragraph, commented out:
Just remove the sample lines.

2021-03-31 04:16 UTC, XVilka commented on src/Main.cpp
> +//
No need for space between them.

2021-03-31 05:52 UTC, XVilka commented
Now you need to add these lines to the rest of the files. But before that, lets wait what @thestr4ng3r @xarkes @karliss @ITAYC0HEN say on the copyright contents/format.

2021-03-31 06:08 UTC, TAbhay commented
> Now you need to add these lines to the rest of the files. But before that, lets wait what @thestr4ng3r @xarkes @karliss @ITAYC0HEN say on the copyright contents/format.

Okay

2021-03-31 17:17 UTC, karliss commented
Probably needs additional entries for the fonts and icons.

2021-04-03 17:22 UTC, thestr4ng3r commented on LICENSES/GPL-3.0-or-later.txt
> +�This License� refers to version 3 of the GNU General Public License.
These characters look strange.

2021-04-03 18:59 UTC, karliss commented on LICENSES/GPL-3.0-or-later.txt
> +�This License� refers to version 3 of the GNU General Public License.
I Initially thought that it's github diff view is not playing nice with UTF8 but I just confirmed and the file really is using who knows what text encoding.

2021-06-19 08:23 UTC, xarkes commented
Should we merge this?

2021-07-02 05:03 UTC, XVilka commented
@xarkes is it incomplete. Will need cover some significant part of the source files to be ready. This one just adds exactly one file - `src/Main.cpp`.

2021-09-15 06:35 UTC, closed without merging