Improved function widget (https://github.com/rizinorg/cutter/issues/2…
rizinorg/cutter pull request #2659
Opened 2021-04-05 14:37 UTC by XutaxKamay

…598)

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Hello.

This is improving mainly the function widget by adding icons which can be colorized on the function widget. 
However, there's still some work to do in my opinion:

- Adding function export functionality.
- Some functions on windows (or even in general) aren't marked as imports / entry point.
- Maybe improving the icons as my skills at Inkscape are really limited... I would be glad if someone could improve them if needed.

**Test plan (required)**

I've tested it, it seems to work properly for now and doesn't seem to break anything but let me know if you find anything. (I've tested both vertical and horizontal view)

![Screenshot_20210405_163023](https://user-images.githubusercontent.com/20893801/113585428-7fb18580-962c-11eb-874d-7e533c778a3b.png)

**Closing issues**

2021-04-06 19:48 UTC, karliss requested changes
In my opinion gradient doesn't help with readability and distinguishing between Fx Fi and FE with unique part already being small fraction of the whole icon.

2021-04-06 19:53 UTC, karliss commented
> About the entry point it doesn't seem also to point to the real entry point.. I suppose "main" and entry-point is different which is a bit confusing to me.

Yes entry-point and main are two different things. Main is concept of programming language, entry point is concept of executable format. During start executable might execute a bunch of code before main function.

2021-04-06 20:05 UTC, XutaxKamay commented on src/widgets/FunctionsWidget.cpp
> +        static QIcon icon_entry(":/img/icons/function_entry.svg");
Well it's what was doing previous code, so I just took it as reference.
And alright I can remove the gradient by just doing pure black/white depending on the theme, but that might remove the dynamic color thing.

2021-04-06 20:06 UTC, XutaxKamay commented on src/widgets/FunctionsWidget.cpp
> +        };
About the Qt::white thing I didn't notice it, that's true it should have been just using `this->property("color")` but I've just totally forgot about it. Thanks.
The problem is that you can't colorize dynamically a QIcon (but apparently is with a QIconEngine, so I'll look on that) so you have to take the pixmap which results into using non-builtin logic. But apparently you're not for colorizing the icons.. I did that dynamically so it can respect the theme's current name functions, but you're against that and prefer to use two icons, one for light and dark theme if I understood you correctly ?

2021-04-06 20:07 UTC, XutaxKamay commented
> > About the entry point it doesn't seem also to point to the real entry point.. I suppose "main" and entry-point is different which is a bit confusing to me.
> 
> Yes entry-point and main are two different things. Main is concept of programming language, entry point is concept of executable format. During start executable might execute a bunch of code before main function.

Yep I know about it but I find it still confusing, I think main could be totally ignored and entry marked as green. Or we could do both with some others colors.

2021-04-07 07:43 UTC, karliss commented on src/widgets/FunctionsWidget.cpp
> +        static QIcon icon_entry(":/img/icons/function_entry.svg");
> Well it's what was doing previous code

Just because old code did something, doesn't always mean that it was good code and more code should do the same.

2021-04-07 09:18 UTC, karliss commented on src/widgets/FunctionsWidget.cpp
> +        };
I am not against the concept of dynamic color, but as you observed there is no easy way of doing that without throwing away some of Qt builtin sizing logic for handling svg icons and potentially making int pixelated or blurry on some configs.  Moving away from dynamic coloring was only 2/4 suggested approaches. It is partially up to you deciding how much you want to dig into this and if the other methods are worth the effort. My subjective opinion is that it's extra work with little gains taking into account  that color is already applied to rest of the row and the same information is already expressed using shape of the icon.

2021-04-07 10:57 UTC, XutaxKamay commented on src/widgets/FunctionsWidget.cpp
> +        static QIcon icon_entry(":/img/icons/function_entry.svg");
Alright okay, but then why it got accepted in the first place? This is a bit misleading.
Also, I'm not sure what you meant by your sentence about static functions variables.. It's either static functions or static variables?
Anyway, how do you want the icons being created? Do you want it inside the FunctionModel class?

2021-04-07 10:57 UTC, XutaxKamay commented on src/widgets/FunctionsWidget.cpp
> +        };
Alright, well I'll do dark & light icons then. Thanks.

2021-04-07 12:38 UTC, XutaxKamay commented
I've moved back by doing icons for dark and light themes, I've moved entry-point to main (created another icon for it), and added some others icons for the future for TLS callbacks, exports and entry-point(s). (There can be multiple entry-points sometimes when someone is manually injecting a PE/ELF with multiple threads, but not much the topic anyway)

Here is my subjective view of how the colors should be on those:

- Exports: purple/rose
- Entry-point(s): red
- TLS callbacks: orange/yellow

2021-04-07 18:56 UTC, karliss commented on src/widgets/FunctionsWidget.cpp
> +        static QIcon icon_entry(":/img/icons/function_entry.svg");
> Alright okay, but then why it got accepted in the first place? This is a bit misleading.

Any software project that has been maintained for extended period of time will have parts of varying quality. 

> Anyway, how do you want the icons being created? Do you want it inside the FunctionsWidget class?

Assuming they are used as DecorationRole having them as member variables in FunctionModel is fine.  Having it in FunctionsWidget if you are going to use it in FunctionModel doesn't make much sense since it would only introduce extra code for forwarding it to model. If you decide to use custom rendering instead of models DecorationRole that's a slightly different situation.

> for now I've just returned as a QIcon directly (you said to do that)

By returning directly i meant returning QIcon without manually converting it to pixmap.  From the looking at code I don't think QIcon as whole is cached that much. Qt has pixmap cache, but but that's for individual pixmaps, not for icons which  can consist of multiple pixmaps and svg images. Didn't see any icon cache. QICon::cacheKey seemed to be only used by QWindowsMenu to skip work when assigning the same icon and debug output. So it's probably better not to repeatedly create QIcon from file path.

2021-04-07 19:03 UTC, XutaxKamay commented on src/widgets/FunctionsWidget.cpp
> +        static QIcon icon_entry(":/img/icons/function_entry.svg");
`Assuming they are used as DecorationRole having them as member variables in FunctionModel is fine. Having it in FunctionsWidget if you are going to use it in FunctionModel doesn't make much sense since it would only introduce extra code for forwarding it to model. If you decide to use custom rendering instead of models DecorationRole that's a slightly different situation.`

Oh right I don't even remember why I renamed FunctionModel to FunctionsWidget I was right before I edited the post. I'll do that then.

`Assuming they are used as DecorationRole having them as member variables in FunctionModel is fine. Having it in FunctionsWidget if you are going to use it in FunctionModel doesn't make much sense since it would only introduce extra code for forwarding it to model. If you decide to use custom rendering instead of models DecorationRole that's a slightly different situation.`

I'll solve that in the next force-push.

2021-04-28 12:08 UTC, ITAYC0HEN commented
Hey, sorry for making you wait. I hope to find the time to go over it in the coming days and read the discussion :)
Regarding colors, I only briefly read it, but I prefer not see "Red" used in the colors as it is a color that is usually used negatively to mark an issue

2021-06-19 08:22 UTC, xarkes approved these changes
Sorry for the delay, honestly I like how this PR looks and I think we could merge it.

2021-06-20 08:10 UTC, ITAYC0HEN approved these changes
Looks okay indeed.
@karliss you left "changes required" so if you approve this PR we can merge

2021-06-20 08:15 UTC, XutaxKamay commented
Hey,

sorry I haven't had much time to do much work on it, so I left it as it is, especially if it looks good to you all.

2021-07-25 06:33 UTC, merged