Remove freenode mentions in remaining files
rizinorg/cutter pull request #2703
Opened 2021-06-09 21:50 UTC by rbrishabh

Fixes @2702

Hi @xarkes! How does this look?
let me know if this needs any changes!
Thanks

2021-06-09 22:21 UTC, 2702 commented
Hi, why am I tagged here?

2021-06-09 22:22 UTC, rbrishabh commented
My bad! It was a mistake

2021-06-10 04:26 UTC, XVilka approved these changes

2021-06-10 05:39 UTC, Surendrajat requested changes
BTW libera.chat has their own webchat(Kiwi IRC) hosted on https://web.libera.chat which can be used as the link.

2021-06-10 05:39 UTC, Surendrajat commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://kiwiirc.com/nextclient/#irc:/irc.libera.chat/#cutter
I guess we need it in format `irc://...`, right?
```suggestion
    url: https://kiwiirc.com/nextclient/#irc://irc.libera.chat/#cutter
```

2021-06-10 05:42 UTC, XVilka commented
@Surendrajat interesting, that wasn't the case when I did the change for the rizin.re site. We should probably use it instead. And update the links everywhere in rizinorg.

2021-06-10 05:44 UTC, rbrishabh commented
@XVilka If you want, I can do that on the other repos! you can just create an issue and tag me! :)

2021-06-10 05:47 UTC, rbrishabh commented
wait, so the changes reqd are that we need to change:
`https://kiwiirc.com/nextclient/#irc://irc.libera.chat/#cutter` with `https://web.libera.chat/#cutter`?

2021-06-10 06:02 UTC, Surendrajat commented
@rbrishabh yes.

2021-06-10 07:03 UTC, ITAYC0HEN commented
> wait, so the changes reqd are that we need to change:
> `https://kiwiirc.com/nextclient/#irc://irc.libera.chat/#cutter` with `https://web.libera.chat/#cutter`?

Exactly! Indeed few weeks ago it wasn't the case. It should be updated for:
- Rizin website (https://github.com/rizinorg/website) - Notice that there are multiple channels (one for users and one for devs)
- Rizin README and other places if needed (https://github.com/rizinorg/rizin)
- Cutter Source (https://github.com/rizinorg/cutter)
- Cutter Website (https://github.com/rizinorg/cutter.re)

2021-06-10 16:08 UTC, rbrishabh commented
Sure! I can do this later today!

2021-06-12 05:14 UTC, ITAYC0HEN commented
That's great! Let us know if you need any help. You can start from this PR on Cutter and then move forward

2021-06-13 19:44 UTC, xarkes commented
Hey @rbrishabh, thanks for the PR, changes look great as said by the others :)
If you can specify the official link as mentioned before instead of kiwiirc it would be perfect!

2021-06-13 19:46 UTC, rbrishabh commented
Sure @xarkes! I had a slightly busy weekend but I plan to get to this first thing on Monday!
sorry for the slight delay :)

2021-06-13 20:38 UTC, xarkes commented
No problem, and no worries! :)

2021-06-14 21:03 UTC, rbrishabh commented
Hey guys! this is ready for another review!
I'll make the same changes on other repositories!
@xarkes @Surendrajat @XVilka 

Thank you

2021-06-15 03:03 UTC, Surendrajat approved these changes
Looks good. Thanks!

2021-06-15 17:23 UTC, xarkes approved these changes
Looks good to me, thanks!

2021-06-15 17:23 UTC, merged