Heap dock widget
rizinorg/cutter pull request #2705
Opened 2021-06-20 06:23 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
Heap widget to show the state of Glibc heap to the user while debugging a program. 
<img width="394" alt="Screenshot 2021-06-20 at 11 48 21 AM" src="https://user-images.githubusercontent.com/56169176/122664189-6ea0fb00-d1bd-11eb-9b51-c20d20fe77bb.png">
<img width="461" alt="Screenshot 2021-06-20 at 11 48 38 AM" src="https://user-images.githubusercontent.com/56169176/122664192-78c2f980-d1bd-11eb-8d5f-c940d48f1e77.png">

Looking for feedback so I can improve the widget and add more functionality as the community desires!

Use Rizin branch: https://github.com/rizinorg/rizin/tree/coverity-error-fix

TODO:
- Add more functionality to the widget (graphs, bins, tcache etc)
- Add doxygen documentation
- Rename functions with better names (like `getHeap`)
- Test it with various heap exploits

**Test plan (required)**

**Closing issues**

2021-06-20 17:52 UTC, ITAYC0HEN commented
Exciting! Will check tomorrow :)

2021-06-22 12:06 UTC, ITAYC0HEN commented
Hey :) #2706 fixes an issue with rz_diff and now that is solved, please rebase your PR so we can test the Windows build :)

2021-06-23 08:22 UTC, ITAYC0HEN commented
@PulakIIIT Can you share a test-case? A binary (and a platform, is it only Linux?)
Things like:
1. Open this binary in Cutter on Linux\Windows,...
2. Put a BP in 0x123456
3. Start debugging
4. Check the heap viewer widget .... 
5. click here, observe that....
etc

2021-06-23 08:48 UTC, PulakIIIT commented
Yeah, this heap dock at the moment only works when the binary is running on linux system (with glibc as the heap allocator).
Here is a sample binary which uses many threads:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

void stopper(){
	printf("stop");
}

void* allocate_heap(){
	char *a = malloc(16);
	char *b = malloc(1600);
	char *c = malloc(320);
	char *e [70];
	for (int i = 0; i < 20; i++){
		e[i] = malloc(48);
	}
	char *large = malloc(50000);
	strcpy(large, "there");
	char *small = malloc(48);
	strcpy(small, "small stuff");
	char *larger = malloc(80000);
	strcpy(larger, "there");
	char *f = malloc(16);	
	strcpy(b, "some more data");
	strcpy(a, "a lot of dataxD");
	for (int i = 0; i < 20; i++){
		free(e[i]);
	}
	free(large);
	free(larger);
	free(c);
	char *smalls[20];
	for(int i = 0; i < 20; i++){
		smalls[i] = malloc(256);
		malloc(10);
	}
	malloc(25);
	for(int i = 0; i < 20; i++){
		free(smalls[i]);
	}
	malloc(100);
	char * ff;
	char* ee[50];
	for (int i = 0; i < 50; i++){
		ee[i] = malloc(64);
		strcpy(ee[i], "dd");
		ff = malloc(16);
		strcpy(ff, "hh");
	}
	char *fff = malloc(32);
	for (int i = 0; i < 20; i++){
		free(ee[i]);
	}
	printf("heap things done");
	stopper();
	pthread_exit(NULL);
}


int printer(){
	printf("Hello");

}
# define NUM_THREAD 2
int main(int argc, char* argv[]){
	pthread_t threads[NUM_THREAD];
	int rc;
	for(int i = 0; i < NUM_THREAD; i++){
		 rc = pthread_create(&threads[i], NULL, allocate_heap, NULL);
		 if(rc){
			printf("ff already");
		 }
	}
	allocate_heap();
	printer();
	pthread_exit(NULL);
//	for(int i = 0; i < NUM_THREAD; i++){
//		pthread_join(threads[i], NULL);	
//	}
}
```
The steps to test it as follows: 
1. Open the binary in Cutter on Linux (or using a gdb server running on linux if that is possible)
2. Put a breakpoint on `stopper` function
3. Run the binary
4. In the debug dock (where the stack thread etc are) click on `heap` tab
5. You can observe all the heap chunks in the widget
6. You can change arenas by clicking on the dropdown below the list of chunks
7. Double-clicking on the chunk shows the hexdump of that in the hexdump widget
8. Right clicking a chunk reveals a context menu, where there is a detailed chunk option. Clicking on the same reveals a dialog box with more information about the heap chunk

2021-06-24 10:35 UTC, yossizap reviewed
Awesome work! 🥳 
Overall the code is great and it worked well in native debug and remote gdb. My main concern is with making it easy to maintain several implementations and letting the user know if this feature actually works on their machine.

2021-06-24 10:35 UTC, yossizap commented on src/core/Cutter.h
> +     * @brief Get a list of heap chunks. (glibc)
> (glibc)

We wouldn't want to have specific implementation for each platform/allocator here, `rz_heap_chunks_list` doesn't necessarily return something specific for a given allocator, some of the fields could be empty in the future(while things like chunks are a shared concept among many allocators) and we'll differentiate subfields in the heap widget.

Same for `getArenas` and `getHeapChunk`, they should be as generic as possible. This isn't an issue right now, just mentioning it in relation to this comment.

2021-06-24 10:35 UTC, yossizap commented on src/core/Cutter.h
> +    QVector<Chunk> getHeap(RVA arena_addr);
getHeapChunks?

2021-06-24 10:35 UTC, yossizap commented on src/core/MainWindow.cpp
> +                                              heapDock };
Maybe this widget shouldn't be toggled by default in Windows/MacOS for now. It should still be accessible for remote gdb but having an empty widget might be confusing until those platforms are supported.

2021-06-24 10:35 UTC, yossizap commented on src/dialogs/HeapInfoDialog.ui
> +        <string>NON_MAIN_ARENA</string>
The three flags here could use a toolTip field

2021-06-24 10:35 UTC, yossizap commented on src/dialogs/HeapInfoDialog.h
> +class HeapInfoDialog : public QDialog
I think that this should be split into a parent class and GlibcHeapInfoDialog. 
I would also consider dynamically creating the dialog's fields from `rz_heap_chunks_list` output(can be easily done from a JSON) to avoid maintaining platform specific implementation but that might be out of the scope of this PR.

2021-06-24 14:38 UTC, ITAYC0HEN commented on src/core/MainWindow.cpp
> +                                              heapDock };
Agree, this was my main concern as well :+1:

2021-06-24 14:39 UTC, ITAYC0HEN commented
Very exciting! The code looks great and the feature works well with your demo binary on a Linux VM. That's great :)
I join @yossizap's concern and suggest hiding this feature from non-supported platforms for Native debug, but show it for remote debug if the backend is Linux-based

2021-06-25 12:35 UTC, PulakIIIT commented on src/core/MainWindow.cpp
> +    if (QSysInfo::kernelType() == "linux" || Core()->currentlyRemoteDebugging) {
I was not able to test remote debugging flag is working correctly as remote debugging kept crashing Cutter on my mac. I will open an issue for it soon

2021-06-25 12:37 UTC, PulakIIIT commented on src/dialogs/HeapInfoDialog.ui
> +        <string>NON_MAIN_ARENA</string>
I added a tooltip but the tooltip isn't working as I have disabled the mouse events for the radio buttons so that they arent user-editable, I will check if there is any other way to disable the buttons which doesn't block tooltips

2021-06-26 19:46 UTC, yossizap requested changes

2021-06-26 19:46 UTC, yossizap commented on src/core/Cutter.cpp
> +        currentlyRemoteDebugging = true;
This should be toggled off in stopDebug

2021-06-26 19:46 UTC, yossizap commented on src/core/MainWindow.cpp
> +    if (QSysInfo::kernelType() == "linux" || Core()->currentlyRemoteDebugging) {
Seems to be MacOS specific, still works with Linux

2021-06-26 19:46 UTC, yossizap commented on src/dialogs/HeapInfoDialog.ui
> +        <string>NON_MAIN_ARENA</string>
You can try to overwrite `hitButton` and return false or set `setEnabled(false)` but that will make the label's text(IS_MAPPED) gray(also done for the flags in the advanced breakpoints menu so it's not too bad).

2021-06-27 10:25 UTC, PulakIIIT commented
After discussing with @yossizap, we have decided that different heap allocators will have different widgets so we can represent the heap information in the best possible way and provide relevant interactions for each allocator. So the heap dock widget will provide a drop-down with all the supported allocators and the user can select the allocator they want. Choosing allocator will render the allocator specific widget

2021-06-27 17:00 UTC, yossizap requested changes

2021-06-27 17:56 UTC, ITAYC0HEN commented
> After discussing with @yossizap, we have decided that different heap allocators will have different widgets so we can represent the heap information in the best possible way and provide relevant interactions for each allocator. So the heap dock widget will provide a drop-down with all the supported allocators and the user can select the allocator they want. Choosing allocator will render the allocator specific widget


Can more than one allocator be relevant in a single session? If not, then it's better to detect the allocator by ourselves rather than forcing the user guess\choose.

2021-06-27 18:20 UTC, PulakIIIT commented
> Can more than one allocator be relevant in a single session? If not, then it's better to detect the allocator by ourselves rather than forcing the user guess\choose.

@ITAYC0HEN Afaik only one allocator can be relevant per debugging session. We don't have code for detecting heap allocators and writing/testing code like this with all different heap allocators may take a while and might be out of the scope of this PR. I can take this up as a task in the future once I am done with the Glibc Heap viewer for Cutter.

2021-06-27 20:13 UTC, yossizap approved these changes

2021-06-27 20:21 UTC, merged