Heap bins view
rizinorg/cutter pull request #2710
Opened 2021-06-28 06:32 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Adding bins view to Glibc heap widget
How to:
- The bins view opens from the context menu by right clicking anywhere in the Glibc heap widget
- We can add a button next to arena selector for bins view if that is easier to find 
 
Current functionality:
- See a list of non empty unsorted, small, large and fastbins
- Show the chain info for each bin

TODO:
- Add graph view
- Add a way of seeing detailed info about the chunks from the chain info 
- Add tcache support?

<img width="622" alt="Screenshot 2021-06-28 at 12 01 53 PM" src="https://user-images.githubusercontent.com/56169176/123590730-a84eb300-d808-11eb-85c7-ddbcc98404e1.png">

**Test plan (required)**

**Closing issues**

2021-07-01 15:13 UTC, yossizap requested changes
Awesome work, the new dialog looks great :)

2021-07-01 16:52 UTC, PulakIIIT commented on src/CMakeLists.txt
> +        )
my ide auto formats it for some reason 😔 Thanks for pointing it out

2021-07-01 16:59 UTC, PulakIIIT commented on src/dialogs/GlibcHeapBinsDialog.cpp
> +void GlibcHeapBinsDialog::showHeapInfoDialog()
Ill look into this and try to add the detailed chunk view in the right click menu from menu. If that's not easily possible then I will try implementing the drop down idea.

2021-07-01 20:46 UTC, yossizap commented on src/CMakeLists.txt
> +        )
the brackets are still wrong just double verify in github after committing

2021-07-01 21:26 UTC, yossizap commented on src/widgets/HeapBinsGraphView.cpp
> +
extra newline

2021-07-02 08:21 UTC, ITAYC0HEN approved these changes
This looks fantastic. Very solid :)

2021-07-02 09:52 UTC, yossizap approved these changes

2021-07-02 10:19 UTC, merged