Heap widget wrapup
rizinorg/cutter pull request #2716
Opened 2021-07-11 10:17 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

- Edit option for detailed heap chunk
- Tcache bins support in the current bins menu
- Arena Info option to show more data from the MallocState struct

**Test plan (required)**

**Closing issues**

2021-07-12 21:08 UTC, yossizap requested changes

2021-07-12 21:08 UTC, yossizap commented on src/core/Cutter.cpp
> +            arena.last_remainder = data->arena->last_remainder_64;
Can't you just store all of these members in ut64 instead of having two sets of  variables? (in rizin)

2021-07-12 21:08 UTC, yossizap commented on src/dialogs/GlibcHeapInfoDialog.cpp
> +        this->ui->rbIM->setChecked(false);
Is it possible to somehow highlight pending changes? This might be a bit confusing since you can accidentally click on one of the flags

2021-07-12 21:08 UTC, yossizap commented on src/dialogs/GlibcHeapInfoDialog.cpp
> +void GlibcHeapInfoDialog::saveChunkInfo()
a basic confirmation dialog should be added here

2021-07-13 07:31 UTC, PulakIIIT commented on src/core/Cutter.cpp
> +            arena.last_remainder = data->arena->last_remainder_64;
This comes from some legacy code, will look into it if I can improve it

2021-07-13 07:58 UTC, PulakIIIT commented on src/dialogs/GlibcHeapInfoDialog.cpp
> +        this->ui->rbIM->setChecked(false);
I am not tracking the pending changes at the moment so Im not sure if this can be implemented easily

2021-07-14 20:00 UTC, yossizap commented on src/dialogs/GlibcHeapInfoDialog.cpp
> +        this->ui->rbIM->setChecked(false);
We can leave this for a future PR

2021-07-15 16:45 UTC, yossizap commented
Please update the Rizin submodule with the fixes from [#1279](https://github.com/rizinorg/rizin/pull/1279). Everything else looks good to me and the edge cases we discussed in mattermost were fixed with latest rizin commit. This should be ready for merge once the Rizin part is merged.

2021-07-16 13:47 UTC, yossizap approved these changes

2021-07-16 13:48 UTC, merged

2021-07-16 16:39 UTC, ITAYC0HEN commented
Looks good!