Use new Rizin API instead of cmdRaw/cmdRawAt
rizinorg/cutter pull request #2770
Opened 2021-09-20 16:55 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

See https://github.com/rizinorg/rizin/pull/1709 as well. This PR uses some of the Rizin API instead of calling the commands.

**Test plan (required)**

TODO: need to provide tests for all functionality i touched

* add CutterRzListForeach as a foreach-keyword for clang-format

**Closing issues**

Address parts of #2666

2021-09-20 17:01 UTC, xarkes commented on src/core/Cutter.cpp
> +        CutterRzListForeach (descs, it, RzIODesc, desc) {
Is there any reason for this extra space? Is it how you use the API in Rizin, or is it clang-format doing it?

2021-09-22 09:16 UTC, XVilka approved these changes

2021-09-22 09:16 UTC, XVilka commented on src/dialogs/EditVariablesDialog.cpp
> +    char *error_msg = NULL;
Maybe we should have a shortcut like `rz_anaysis_var_set_type_str(v, type_str)` in the Rizin API. But it's fine as is already.

2021-09-22 10:51 UTC, ret2libc commented
> make sure when changing an existing type link the current type name is selected

Seems to fail

2021-09-22 10:55 UTC, ret2libc commented
> check that hex widget can write increase/decrease

There's a problem if you change from byte to something else in the dialog, but this is present also in last release.

2021-09-22 10:58 UTC, ret2libc commented
> check that hex widget can write base64 encoded/decoded

Also this fails.

2021-09-22 11:03 UTC, ret2libc commented
> > make sure when changing an existing type link the current type name is selected
> 
> Seems to fail

@thestr4ng3r @xarkes i'm not sure about this... it seems that sometimes it work, others it doesn't :/ maybe it depends on where exactly you put the cursor? Can you double check? I was not able to use `type link` functions in last released cutter so i could not really compare.

2021-09-22 17:44 UTC, xarkes requested changes
- [ ] edit bytes endian through the stack widget and check it performs it correctly
    * couldn't find this option during debug
- [x] double click on stack-widget address or use seekToFunctionStart(TODO: where???) to check that seek and seek history work well
    * seek works well, history works well (although ESC key seems not to be working)
- [ ] try to load a file with PDB and make sure PDB info are correctly loaded
    * no PDB around, didn't test
- [x] try to edit a variable, both name and type and make sure it works
- [ ] test "type link" functionalities to add and remove a type link
    * it seems to be working in order to set a type link however I couldn't find how to remove it
- [ ] make sure when changing an existing type link the current type name is selected
    * there are weird issues with the pre-fill of the dialog box but I'm not sure it's unrelated to this PR
- [x] check that hex widget can write string
    * tested with cache mode
- [ ] check that hex widget can write increase/decrease
    * I couldn't understand the UI, it asks for a value (input is empty) and I'm not sure what to do with it
- [x] check that hex widget can write zeros
- [x] check that hex widget can write base64 encoded/decoded

2021-09-22 17:55 UTC, thestr4ng3r commented
macOS/arm64 with bundled rizin:

* [ ] ~edit bytes endian through the stack widget and check it performs it correctly~ **can't test on macOS atm because debugging there is too broken, but that is nothing new.**
* [ ] ~double click on stack-widget address or use seekToFunctionStart(TODO: where???) to check that seek and seek history work well~ **same**
* [x] try to load a file with PDB and make sure PDB info are correctly loaded - **works both with the menu entry and from InitialOptionsDialog**
* [x] try to edit a variable, both name and type and make sure it works
* [ ] test "type link" functionalities to add and remove a type link - **seems entirely broken and breaks disassembly, I suggest to remove it from cutter in light of globals which can be added later**
* [ ] make sure when changing an existing type link the current type name is selected - **same**
* [x] check that hex widget can write string
* [x] check that hex widget can write increase/decrease
* [x] check that hex widget can write zeros
* [x] check that hex widget can write base64 encoded/decoded

2021-09-22 18:21 UTC, thestr4ng3r approved these changes
So looks like apart from type links, everything works. But type links are broken primarily from rizin side, so I would merge this and then remove them from cutter.

2021-09-22 19:18 UTC, ret2libc commented
> edit bytes endian through the stack widget and check it performs it correctly

this is actually just setting a value in the stack widget, sorry

2021-09-23 04:36 UTC, XVilka commented
I suggest the following:
- We remove typelinks in 2.0.3 release
- We add global variables support in shortly following 2.0.4 release
- We remove typelinks from Rizin in maybe 0.3.1

2021-09-23 08:15 UTC, merged