Support for previewing in the Graph widget
rizinorg/cutter pull request #2797
Opened 2021-10-06 11:24 UTC by Petross404

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This PR is implementing the preview feature much like #2459 did but the configuration checkbox in `Graph` Settings is there from the beginning.

* First, I am going to say that the size of the font in `GraphWidget` is 8, compared to the font-size of preview in `DisassemblyWidget` which is 6. But that is a matter we can discuss.

* Second, I couldn't implement this in `GraphWidget` class. For example `DisassemblerGraphView *graphView`, a private member in the aforementioned class, has private visibility for some useful methods like `Instr *DisassemblerGraphView::getInstrForMouseEvent(..)`. So I wrote the code inside `DisassemblerGraphView` and not inside `GraphView` which would be the equilevant of `DisassemblyWidget` like in #2459.

* Third, I duplicated [a lot of code](https://github.com/rizinorg/cutter/compare/master...Petross404:graph-preview?expand=1#diff-6c75dce8aeeec87acdf0b26f5a35a393b59ce210a50831751eee0a9aba01df6eR32) for this. Or [here](https://github.com/rizinorg/cutter/compare/master...Petross404:graph-preview?expand=1#diff-6c75dce8aeeec87acdf0b26f5a35a393b59ce210a50831751eee0a9aba01df6eR1057). If only there was a commonly accessed API for extracting `QTextBlockUserData` data. These code snippets are copied from [`DisassemblyWidget.cpp`](https://github.com/rizinorg/cutter/blob/master/src/widgets/DisassemblyWidget.cpp#L25).

* Fourth, I wrote the code in a new `bool DisassemblerGraphView::eventFilter(..)` I know that an `eventFilter()` isn't the most efficient way since it filters any occurring event. Another candidate was `DisassemblerGraphView::blockHelpEvent(..)` but I can't really understand what a `blockHelpEvent` actually does, so please let's discuss other more efficient and proper solutions for this.

* Last, I used the followinc code to get the address.
```cpp
       /*
         * getAddrForMouseEvent() doesn't work for jmps, like
         * getInstrForMouseEvent() with false as a 3rd argument.
         */
        Instr *inst = getInstrForMouseEvent(*block, &point, true);
        if (inst != nullptr) {
            offsetFrom = inst->addr;
        }
```
If `getAddrForMouseEvent()` or `getInstrForMouseEvent` is used with the default (`false`) third argument, then I can't get previews for any `jmp`, `jne` etc. Only for `call`. That is why I am using this indirect way. Again. let me know if I can do this better.

**Test plan (required)**

Compile and run Cutter as usual. Open the Graph widget and hover the cursor where the assembly is using `jmp` or `call`. You will get a tool-tip previewing the code that exists at that address.

![graph1Screenshot_20211006_121647](https://user-images.githubusercontent.com/18561627/136192531-8a99fabe-4afb-4825-8353-0c3d9fc09b33.png)

![graph2Screenshot_20211006_121732](https://user-images.githubusercontent.com/18561627/136192619-e0a77f8a-4f86-49e5-b8e5-26d74bcfb2ce.png)

Although, there are some edge cases. I can't figure out this one. If I double click on this code, it will lead me to this function by opening a new block. The tool-tip won't show up though for this specific `call`.
![graph3Screenshot_20211006_133336](https://user-images.githubusercontent.com/18561627/136192700-31becc7e-4b5d-468e-a398-3453d78c7ce5.png)

2021-10-06 12:34 UTC, Petross404 commented
Another idea would be the following. Instead of previewing a fixed number of lines for the referenced block (10 in this case), we could count how many lines the block has, and preview only those. This way when a block to be previewed has only:

```asm
xor edb, edb
nop dword [rax]
```
and nothing else, the tool-tip won't show any more lines. Only the lines that exist in the block.

2021-10-06 18:23 UTC, Petross404 commented
Finally, the tooltips follow the color-scheme and stylesheet of the window.

![graph4Screenshot_20211006_211934](https://user-images.githubusercontent.com/18561627/136260904-40e0f2ae-5459-4f6f-bf50-ff03b70b66d7.png)

![graph6Screenshot_20211006_212053](https://user-images.githubusercontent.com/18561627/136260963-f53b3f8f-64ad-4dd3-86c2-f88aa6a0077c.png)

2021-10-20 19:00 UTC, Petross404 commented
> Looks good as is, in my opinion. Further improvements can be done separately.

Ok, as you think it's best.

2021-11-13 12:44 UTC, wargio approved these changes
This needs to be manually tested

2021-11-13 13:13 UTC, thestr4ng3r requested changes

2021-11-13 13:13 UTC, thestr4ng3r commented on src/widgets/DisassemblerGraphView.cpp
> +    if (Config()->getGraphPreview() && event->type() == QEvent::Type::ToolTip) {
Better swap this, so the heavier operation is short-circuited.
```suggestion
    if (event->type() == QEvent::Type::ToolTip && Config()->getGraphPreview()) {
```

2021-11-13 13:13 UTC, thestr4ng3r commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
As you already noted, there is indeed a lot of code duplication, while everything that is common with `DisassemblyWidget` about the tooltip should be implemented only once.
I would create new source files `src/common/DisassemblyPreview.h`/`src/common/DisassemblyPreview.cpp`, move it all there and call from the widgets.

2021-11-13 17:35 UTC, Petross404 commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
Sounds good. After you implement this we will discuss the details like if I should change the other widgets too in this PR.

2021-11-13 18:32 UTC, thestr4ng3r commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
This was meant as a suggestion for what you could improve in this pr, not what I plan to do 😉
Feel free to ask though if you have any questions about approaching the implementation.

2021-11-13 19:02 UTC, Petross404 commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
Lol, yes I can tell now, thanks for poinithing that out!

2021-11-18 17:15 UTC, Petross404 commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
I am facing a problem about the whole stylesheet setup.

Two very different widgets (three if you count the Functions widget) have to implement the same functionality. I am thinking about two ways:

a) Free function. I create a free function inside `src/common/DisassemblyPreview.cpp` like this:
```cpp
void setPreviewStyleSheet(QWidget *w)
{
    w->setStyleSheet(QString("QToolTip { border-width: 1px; max-width: %1px;"
                             "opacity: 230; background-color: %2;"
                             "color: %3; border-color: %3;}")
                             .arg(400)
                             .arg(Config()->getColor("gui.tooltip.background").name())
                             .arg(Config()->getColor("gui.tooltip.foreground").name()));
}
```
It's clean but it feels so weird to pass QWidgets like this when dealing with Qt and C++. It feels like C trying to emulate the `this` pointer.

b) Class member function. But in order to avoid copying all over again one would need one definition inside a common base widget for `DisassemblyWidget`, `DisassemblerGraphView` and `FunctionsWidget` which AFAIK doesn't exist.

Other ideas go as far as subclassing `QToolTip` and creating a tooltip object for each widget with the needed functionality already included. But it feels too much for a simple task.

Do you have any comments or ideas on this?

2021-11-18 18:06 UTC, thestr4ng3r commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
a) is perfectly fine. Don't worry about OOP in that regard, it's absolutely not necessary to force things into object orientation if does not provide any concrete value.
As a bonus, you could put it in a namespace:
```c++
namespace DisassemblyPreview
{
void setStyleSheet(QWidget *w);
// ... everything else common to the previews here ...
}
```
and then do `DisassemblyPreview::setStyleSheet(this);`.
But in fact, for the stylesheet I actually recommend to do it like this:
```c++
namespace DisassemblyPreview
{
QString toolTipStyleSheet(); // just return the string in here
// ...
}
```
and then `this->setStyleSheet(DisassemblyPreview::getToolTipStyleSheet());`.
That is because `setStyleSheet` will override the entire stylesheet of the widget, but the individual widgets may want to add some more to it themselves.

2021-11-19 03:52 UTC, Petross404 commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
Neat! Do we want this in the current source file or in helper.cpp?

In src/common/DisassemblyPreview.cpp I have put the getTextBlockData already.
Anyway I will push the following weekend my changes to discuss them.
Thanks for the help!

2021-11-19 07:41 UTC, thestr4ng3r commented on src/widgets/DisassemblerGraphView.cpp
> +                                    .arg(disasmPreview.join("<br>"));
I am not sure what you mean by the current source file. I would put everything preview-related into `DisassemblyPreview.cpp`.

2021-11-24 12:44 UTC, thestr4ng3r requested changes
The code itself looks good now, it is nicely separated.

I am seeing some unexpected behavior though (on macOS, see the video below):
* The preview only shows when I hover some pixels higher than the actual token
* The preview appears at a position where the pointer is in the middle of the tooltip and it disappears again immediately

Please also revert the changed rizin submodule commit.

When these points have been addressed I think it is good to merge.


https://user-images.githubusercontent.com/1460997/143240759-5f63d390-ec88-44be-a391-c5100cfe6fa1.mov

2021-11-28 00:11 UTC, Petross404 commented
> The code itself looks good now, it is nicely separated.
> 
> I am seeing some unexpected behavior though (on macOS, see the video below):

> * The preview only shows when I hover some pixels higher than the actual token
> * The preview appears at a position where the pointer is in the middle of the tooltip and it disappears again immediately
> 
> Please also revert the changed rizin submodule commit.
> 
> When these points have been addressed I think it is good to merge.
> 
>  Bildschirmaufnahme.2021-11-24.um.13.39.58.mov

How can I revert a single commit? I know it's a noob question but I suspect that I didn't revert it in my latset commits.

Also, about the mac os glitch, could I use mac os specific directives to change the `pointOfEvent` by a small offset?

2021-11-28 08:57 UTC, thestr4ng3r commented
> How can I revert a single commit? I know it's a noob question but I suspect that I didn't revert it in my latest commits.

Either `git revert <hash>` or you do something like `git rebase -i master` and completely remove the commit in the rebase.
 
> Also, about the mac os glitch, could I use mac os specific directives to change the `pointOfEvent` by a small offset?

Only as the very last resort. I have not investigated this issue in detail yet, but I doubt it is specific to macOS, rather than maybe because of some dpi scaling setting. Do you have an environment where you can reproduce the issue from the video?

2021-12-01 17:34 UTC, Petross404 commented
> Only as the very last resort. I have not investigated this issue in detail yet, but I doubt it is specific to macOS, rather than maybe because of some dpi scaling setting. Do you have an environment where you can reproduce the issue from the video?

Yes, in fact I am programming this in a 2013 macbook. I can reproduce this. I am thinking of offseting the QPoint by a little if hidpi is enabled.

2021-12-04 17:48 UTC, Petross404 commented
I came up with the following code:
```cpp
bool DisassemblyPreview::showDisasPreview(QWidget *parent, const QPoint &pointOfEvent,
                                          const RVA offsetFrom)
{
    QProcessEnvironment env;
    QPoint point = pointOfEvent;

    if (env.contains(QStringLiteral("QT_ENABLE_HIGHDPI_SCALING"))
        || env. contains(QStringLiteral("QT_AUTO_SCREEN_SCALE_FACTOR"))
        || QCoreApplication::testAttribute(Qt::AA_EnableHighDpiScaling)
        || QCoreApplication::testAttribute(Qt::AA_UseHighDpiPixmaps)) { /*<- Only the check on this line works */
        point.setY(pointOfEvent.y() - 80);
    }

    QList<XrefDescription> refs = Core()->getXRefs(offsetFrom, false, false);
    ....
```
So if the check finds that we are running on HiDPI, we change the y position by an offset of 80 (random number but it is working) and the tooltip is away from the mouse cursor and it doesn't hide.

![Screenshot 2021-12-04 at 7 39 54 PM](https://user-images.githubusercontent.com/18561627/144719161-bafc9e53-404c-4259-ad70-d7cd0422f6aa.png)
![Screenshot 2021-12-04 at 7 40 13 PM](https://user-images.githubusercontent.com/18561627/144719173-2091c895-abc2-4637-9b44-cae82859348f.png)

Finally, I have two questions:
a) I know that in my system only `QCoreApplication::testAttribute(Qt::AA_UseHighDpiPixmaps)` works but what about the other checks and other systems? Some checks are working only on 5.14 and [forward](https://doc.qt.io/qt-5/highdpi.html) (look at #High DPI Support in Qt).

b) Should I increase the y offset?

2021-12-04 18:01 UTC, thestr4ng3r commented
Sorry, but we can't just apply some offsets based on the system configuration. That is way too error-prone.
I think the code that initially calculates the `pointOfEvent` has a bug there that should be fixed instead.
It does help though that you have pinpointed it do some flags though. Maybe I will check the code there myself when I have time.

2021-12-04 18:37 UTC, Petross404 commented
> Sorry, but we can't just apply some offsets based on the system configuration. That is way too error-prone. I think the code that initially calculates the `pointOfEvent` has a bug there that should be fixed instead. It does help though that you have pinpointed it do some flags though. Maybe I will check the code there myself when I have time.

Hmm, I suppose you are right about the first issue.

But what could possibly be faulty in this code:
```cpp
        QHelpEvent *helpEvent = static_cast<QHelpEvent *>(event);
        QPoint pointOfEvent = helpEvent->pos();
        QPoint point = viewToLogicalCoordinates(pointOfEvent);

        GraphBlock *block = getBlockContaining(point);
```
It worked at my FHD 24" monitor. Weird.

2021-12-05 08:24 UTC, thestr4ng3r commented
`QToolTip::showText()` takes a global position rather than view-relative: https://doc.qt.io/qt-5/qtooltip.html#showText
I have pushed a fix to your branch.

2021-12-05 08:26 UTC, thestr4ng3r approved these changes
Seems to work well now, thanks!

2021-12-05 08:53 UTC, merged

2021-12-05 10:52 UTC, Petross404 commented
> Seems to work well now, thanks!

Sometimes the problem lies in the tiny details... Thank you for your help and the merge of the feature.