Hexeditor: add option to write hex bytes
rizinorg/cutter pull request #2845
Opened 2021-12-02 10:07 UTC by AlexThesys

**Your checklist for this pull request**
- [*] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [*] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
Target widget for this feature: Hexdump. The purpose of this feature is to give user the ability to enter a string of hexadecimal bytes (using Hex Editors RMB context menu) in the form of either 'ff00fccdcd' or '\xff\x00\xfc\xcd\xcd' and that would be exactly what gets written. Although this seems to be quite a common operation, currently there is no way of doing this without using the console. Basically we just parse the string to select the pairs of chars, then convert them to integers with radix 16 and write to the selected location.

**Test plan (required)**
Try entering any number of hexadecimal bytes using RMB->Edit->Write Hex Bytes in Hexdump.
![hexedit_demo](https://user-images.githubusercontent.com/41104158/144399646-7a0f03c1-e158-44e0-a166-5e8197921c33.png)
The amount of bytes written respects the selected region (if any selection is performed). Any bytes past selection won't be overwritten.
In case, when bytes string is entered in the form of '\x00\x00', this is detected by checking only the first two bytes, so any mistakes in the input won't be corrected.
Incorrect input will result in zeros being written.
If the odd number of bytes is entered, the last one will be ignored.

2021-12-07 04:51 UTC, XVilka requested changes

2021-12-07 04:51 UTC, XVilka commented on src/widgets/HexWidget.cpp
> +    if (ok && bytes_size) {
Probably better to invert the condition and just quickly return if none of these are valid.

2021-12-08 00:01 UTC, XVilka approved these changes

2022-02-05 06:57 UTC, ITAYC0HEN commented on src/widgets/HexWidget.h
> +	void w_writeBytes();
```suggestion
    void w_increaseDecrease();
    void w_writeBytes();
```

2022-03-15 14:44 UTC, XVilka commented
@AlexThesys could you please rebase the PR on top of the latest `dev`? It should fix problematic CI jobs.

2022-03-15 17:25 UTC, AlexThesys commented
Yes, sure. Done.

2022-03-16 16:36 UTC, merged