Use rizin api
rizinorg/cutter pull request #2856
Opened 2021-12-17 19:36 UTC by imbillow

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Switch to use Rizin API directly,

- [x] cmdRawAt "CC"
- [x] cmdRawAt "wa"

**Test plan (required)**

**Closing issues**

2021-12-18 11:09 UTC, thestr4ng3r requested changes

2021-12-18 11:09 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +#include "librz/rz_core.h"
Rizin includes should be just like `#include <rz_core.h>`. But these should already be included here, did your IDE maybe add that?

2021-12-18 11:09 UTC, thestr4ng3r commented on src/core/Cutter.h
> +    void fnAt(std::function<void()> fn, RVA address)
Nice idea! It should be private though and I think something like `applyAtSeek()` might be a better name.
Keep in mind that in general having to apply a temporary seek to do something is bad API design from rizin side, in this case it would be better if `rz_core_hack()` could take an address argument. But with `RzArch` maybe replacing this in the future, it might not be worth refactoring that so your solution here is good.

2021-12-19 09:37 UTC, imbillow commented on src/core/Cutter.cpp
> +#include "librz/rz_core.h"
That's it.

2021-12-19 09:50 UTC, thestr4ng3r approved these changes

2021-12-19 10:00 UTC, merged