Use rz api
rizinorg/cutter pull request #2861
Opened 2021-12-20 19:37 UTC by imbillow

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

- [x] "fr" renameFlag
- [x] "f-" delFlag
- [x] "f" addFlag
- [x] "fsj" getAllFlagspaces
- [x] "fj" getAllFlags
- [x] "afn" renameFunction
- [x] "af-" delFunction
- [x] "af" createFunctionAt

**Test plan (required)**

**Closing issues**

2021-12-21 00:27 UTC, XVilka requested changes

2021-12-21 00:27 UTC, XVilka commented on src/core/Cutter.cpp
> +    if (size <= 0) {
Better to make an API function on the Rizin first. I think the code is there already just not as an API.

2021-12-21 00:27 UTC, XVilka commented on src/core/Cutter.cpp
> +    rz_meta_del(core->analysis, RZ_META_TYPE_DATA, addr, 1);
Same

2021-12-21 00:27 UTC, XVilka commented on src/core/Cutter.cpp
> +    RzSpaces *spaces = &core->flags->spaces;
Probably like with flags, better to make an API function that returns RzList of flagspaces and use it here

2021-12-21 00:43 UTC, XVilka commented
After that you might need to update the Rizin and import this commit too https://github.com/rizinorg/cutter/pull/2855/commits/3ecc3b74a294db77fe3eab6027de98d77a36a022
cc @ret2libc

2021-12-21 03:31 UTC, imbillow commented
But cutter now uses rizin 0.3.1, maybe we have to update rizin to the dev branch first

2021-12-21 03:34 UTC, XVilka commented
@imbillow precisely. I recommend to do that PR separately, plus extract that commit I mentioned. It would be a prerequisite of this one.

2021-12-23 12:52 UTC, XVilka commented on src/core/Cutter.cpp
> +    RzSpaces *spaces = &core->flags->spaces;
Please address this, and I think it's good

2021-12-23 13:05 UTC, thestr4ng3r approved these changes

2021-12-23 13:08 UTC, wargio reviewed
LGTM, but needs to be tested

2021-12-23 13:53 UTC, ret2libc commented on src/core/Cutter.cpp
> +    rz_analysis_fcn_del(core->analysis, addr);
It seems this is not necessary because the `rz_core_analysis_undefined` function already does the other two calls.
I know that you have just copied the existing code from `af-` command handler, but that is likely wrong as well :(

```C
RZ_API void rz_core_analysis_undefine(RzCore *core, ut64 off) {
	RzAnalysisFunction *f = rz_analysis_get_fcn_in(core->analysis, off, -1);
	if (f) {
		if (!strncmp(f->name, "fcn.", 4)) {
			rz_flag_unset_name(core->flags, f->name);
		}
		rz_meta_del(core->analysis, RZ_META_TYPE_ANY, rz_analysis_function_min_addr(f), rz_analysis_function_linear_size(f));
	}
	rz_analysis_fcn_del_locs(core->analysis, off);
	rz_analysis_fcn_del(core->analysis, off);
}
```

2021-12-23 13:53 UTC, ret2libc commented on src/core/Cutter.cpp
> +    RzSpaces *spaces = &core->flags->spaces;
I think instead we can just use `rz_flag_space_foreach`.  No need for a new API.

2021-12-23 13:53 UTC, ret2libc commented on src/core/Cutter.cpp
>  QList<FlagDescription> CutterCore::getAllFlags(QString flagspace)
I'm not sure this function was correct in the first place.

It seems the purpose of this is to get all the flags in a flagspace and to do that we could use `rz_flag_foreach_space_glob` or `rz_flag_foreach_space`.

Another way to do the same could be to use `rz_flag_space_push (flagspace)` , `rz_flag_all_list` and then `rz_flag_space_pop`.

2021-12-23 14:27 UTC, XVilka commented on src/core/Cutter.cpp
>  QList<FlagDescription> CutterCore::getAllFlags(QString flagspace)
I think `rz_flag_foreach_space()` is preferable since `push`/`pop` imply the state change, which is not really a good thing for the API.

2022-01-03 11:44 UTC, XVilka commented on src/core/Cutter.cpp
> +    rz_analysis_fcn_del(core->analysis, addr);
I suggest then first to fix the `af-` code in Rizin as well, otherwise, we forget.

2022-01-17 06:44 UTC, imbillow commented on src/core/Cutter.cpp
>  QList<FlagDescription> CutterCore::getAllFlags(QString flagspace)
But here is just to get all the flagspaces, not the flags in all the flagspaces

2022-01-17 10:50 UTC, imbillow commented
but when i open a binary file using cutter it will gives error.

```
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

2022-01-17 11:26 UTC, ret2libc commented on src/core/Cutter.cpp
>  QList<FlagDescription> CutterCore::getAllFlags(QString flagspace)
I think this function gets the flags within a flag space, not the flagspaces, so `rz_flag_foreach_space` should work.

2022-01-17 12:59 UTC, imbillow commented
```
❯ ./cmake-build-debug/Rizin-prefix/bin/rizin ~/Downloads/ls
 -- Use the '[' and ']' keys in visual mode to adjust the screen width
[0x00005bc0]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[fish: Job 1, './cmake-build-debug/Rizin-prefi…' terminated by signal SIGSEGV (Address boundary error)

❯ ./cmake-build-debug/Rizin-prefix/bin/rizin -version
rizin 0.4.0-git @ linux-x86-64
commit: 20777b6e0b06a35d10f43a89801e187c9daae77d, build: 2022-01-17__20:52:57
```

```
❯ ./build/binrz/rizin/rizin ~/Downloads/ls
WARNING: No calling convention defined for this file, analysis may be inaccurate.
[0x00005bc0]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Applied 0 FLIRT signatures via sigdb

❯ ./build/binrz/rizin/rizin -version
rizin 0.4.0-git @ linux-x86-64
commit: 20777b6e0b06a35d10f43a89801e187c9daae77d, build: 2022-01-17__20:45:20
```

It's very strange that the rizin compiled in cutter will crash, but the rizin compiled by myself is fine.

2022-01-17 14:07 UTC, wargio commented
it is possible that is a bug that we have fixed on dev but not on stable. are you using rizin 0.3.4 with that cutter ?

2022-01-17 15:23 UTC, imbillow commented
I did a clean build again but still the same result.

2022-01-17 16:33 UTC, wargio commented
run rizin via `RZ_DEBUG=1 ./cmake-build-debug/Rizin-prefix/bin/rizin ~/Downloads/ls`

2022-01-17 16:53 UTC, imbillow commented
```
❯ RZ_DEBUG=1 ./cmake-build-debug/Rizin-prefix/bin/rizin ~/Downloads/ls
 -- Step through your seek history with the commands 'u' (undo) and 'U' (redo)
[0x00005bc0]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[Backtrace 10 stack frames.for all functions (aaft)
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_util.so.0.4.0-git(rz_sys_backtrace+0x28)[0x7f38874bac2b]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_util.so.0.4.0-git(+0x8ae6b)[0x7f38874bae6b]
/usr/lib/libc.so.6(+0x3cda0)[0x7f3887248da0]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(rz_core_analysis_type_match+0x780)[0x7f38859eee2d]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(+0xa47bb)[0x7f3885a087bb]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(rz_core_analysis_everything+0x997)[0x7f3885a070c1]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(+0x19a685)[0x7f3885afe685]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(+0x19c5cc)[0x7f3885b005cc]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(+0x203997)[0x7f3885b67997]
/home/aya/source/cutter/cmake-build-debug/Rizin-prefix/bin/../lib/librz_core.so.0.4.0-git(rz_cmd_call_parsed_args+0x57)[0x7f3885b67a51]
```

2022-01-18 22:56 UTC, imbillow commented
I did find some bugs.

2022-01-19 02:06 UTC, imbillow commented on src/core/Cutter.cpp
> +    return flags;
@ret2libc Maybe it's enough now.
I'm use `rz_flag_space_foreach` in `getAllFlagspaces`, and use `rz_flag_foreach_space` in `getAllFlags`

2022-01-19 02:15 UTC, imbillow commented
https://github.com/rizinorg/rizin/pull/2221

2022-01-19 09:28 UTC, ret2libc commented on src/core/Cutter.cpp
> +    return flags;
seems alright :+1:

2022-01-27 01:35 UTC, XVilka commented
@imbillow please update Rizin submodule again. I guess this PR will be ready for the final review after that.

2022-01-27 04:20 UTC, XVilka approved these changes
LGTM, apart from the style changes, not sure if they are necessary cc @thestr4ng3r

2022-01-27 04:28 UTC, imbillow commented
Ah, there is a problem, my editor doesn't seem to use clang-format

2022-01-27 09:05 UTC, thestr4ng3r approved these changes

2022-01-27 09:06 UTC, merged