Show a nice folder structure in Visual Studio
rizinorg/cutter pull request #2890
Opened 2022-02-03 00:27 UTC by mrexodia

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

Just makes Visual Studio look nice:

![image](https://user-images.githubusercontent.com/2458265/152260573-67b99c39-3a7c-4944-a6dd-af6a1c1668e8.png)

2022-03-10 18:27 UTC, thestr4ng3r requested changes
Sorry for the delay. The overall approach looks good to me.

2022-03-10 18:27 UTC, thestr4ng3r commented on src/CMakeLists.txt
> +add_executable(Cutter ${ALL_SOURCES})
I think you will need to remove `${BINDINGS_SOURCE}` above and re-add it here to fix this:
```
CMake Error at src/CMakeLists.txt:445 (source_group):
  source_group ROOT: /home/runner/work/cutter/cutter/src is not a prefix of
  file:
  /home/runner/work/cutter/cutter/build/src/bindings/CutterBindings/cutterbindings_module_wrapper.cpp
```

2022-09-19 07:30 UTC, ITAYC0HEN commented on src/CMakeLists.txt
> +add_executable(Cutter ${ALL_SOURCES})
ping

2022-10-23 11:15 UTC, mrexodia commented on src/CMakeLists.txt
> +add_executable(Cutter ${ALL_SOURCES})
Sorry for the late reply, should be updated now.

2022-10-23 11:37 UTC, thestr4ng3r approved these changes

2022-10-23 11:40 UTC, merged