Use rizin instead of Qt to parse JSON
rizinorg/cutter pull request #2902
Opened 2022-03-10 09:46 UTC by akihikodaki

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [X] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [X] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Qt truncates integers to 52-bit, corrupting e.g. memory addresses. Use rizin's JSON parser, which can parse integers whose size is up to 64 bits.

**Test plan (required)**

1. Install Kernel Debug Kit 12.2 build 21D49. For details, see: https://developer.apple.com/documentation/apple-silicon/debugging-a-custom-kernel-extension2. 
2. Open `/Library/Developer/KDKs/KDK_12.2_21D49.kdk/System/Library/Kernels/kernel.development.t8101`. 
3. See it can disassemble 0xfffffe0007cc7290.4. 

**Closing issues**

2022-03-10 12:02 UTC, akihikodaki commented
569591648141f7b9fc62eae067b24e7c25efb9eb: Updated the header file list, probably fixing the AppVeyor failure.

2022-03-10 13:22 UTC, akihikodaki commented
00afff3609ae54dc352803c78b735c9eb5c67af2: Replaced `std::shared_ptr` with `QSharedPointer`, expecting the build failures on the CI will be fixed.

2022-03-10 16:45 UTC, akihikodaki commented
4984e0c4f619eb2c4ae3d91c411b2dfac427fc9a: Removed `find_if` due to lack of implementations on some platforms tested by the CI. Now the CI is fixed.

2022-03-10 18:24 UTC, thestr4ng3r requested changes
I am actually surprised the bitness issue from qt json was not discovered earlier since it is quite serious.

Be aware though that the long-term goal is to completely get rid of any json/command-based queries in Cutter and use more type-safe and stable C api instead. This is tracked in https://github.com/rizinorg/cutter/issues/2666. So when specific issues are discovered in something that still uses json, it is often better to just rewrite it from scratch with API (optionally also creating this API in rizin first if it does not yet exist). However in this case, the 64-bit issue affects basically all code that uses json and in some places like `pdJ`, it will still take longer until we can build a proper API for it, so I think your `CutterJson` approach is good for now!

2022-03-10 18:24 UTC, thestr4ng3r commented on src/common/ColorThemeWorker.cpp
> +        for (CutterJson element : rzTheme) {
```suggestion
        for (CutterJson element : value) {
```

Color themes are broken otherwise

2022-03-10 18:24 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +    if (refItem.addr == RVA_INVALID) {
Are you sure these checks are equivalent?

2022-03-10 18:24 UTC, thestr4ng3r commented on src/core/Cutter.h
> +struct CUTTER_EXPORT CutterAddrRefs
```suggestion
struct CUTTER_EXPORT AddrRefs
```

No need to prefix these structures with `Cutter`, unless there is a clash. For the `CutterJson` class however I do think it makes sense, to disambiguate it from `RzJson` and the Qt one.

2022-03-10 18:24 UTC, thestr4ng3r commented on src/core/Cutter.h
> +struct CUTTER_EXPORT CutterRegisterRef
same here

2022-03-10 18:24 UTC, thestr4ng3r commented on src/core/CutterJson.h
> +    ut64 toUt64() const { return value && value->type == RZ_JSON_INTEGER ? value->num.u_value : 0; }
A bit much spacing here. I would remove the empty lines between single-line methods, assuming clang-format does not complain then.

2022-03-10 18:24 UTC, thestr4ng3r commented on src/core/CutterJson.cpp
> +    }
`last` will be null at this point. This also breaks scrolling down in the disassembly widget (it only moves by 1 byte at a time instead of the instruction size then)

2022-03-10 19:28 UTC, akihikodaki commented on src/core/CutterJson.cpp
> +    }
Fixed with commit b9b778c4e3dac615e0e2944679eabeccec885354.

2022-03-10 19:28 UTC, akihikodaki commented on src/core/CutterJson.h
> +    ut64 toUt64() const { return value && value->type == RZ_JSON_INTEGER ? value->num.u_value : 0; }
Fixed with commit b9b778c4e3dac615e0e2944679eabeccec885354.

2022-03-10 19:29 UTC, akihikodaki commented on src/core/Cutter.h
> +struct CUTTER_EXPORT CutterRegisterRef
Changed with commit b9b778c4e3dac615e0e2944679eabeccec885354.

2022-03-10 19:29 UTC, akihikodaki commented on src/core/Cutter.h
> +struct CUTTER_EXPORT CutterAddrRefs
Changed with commit b9b778c4e3dac615e0e2944679eabeccec885354.

2022-03-10 19:34 UTC, akihikodaki commented on src/core/Cutter.cpp
> +    if (refItem.addr == RVA_INVALID) {
Not exactly equivalent. It would produce string `-> ` when no associated description found where it did not produce a string in the case before this change. However, the behavior emitting a string ending with `-> ` was already present in case the last linked `ref` does not have an associated description.

2022-03-10 19:36 UTC, akihikodaki commented on src/common/ColorThemeWorker.cpp
> +        for (CutterJson element : rzTheme) {
Fixed with commit b9b778c4e3dac615e0e2944679eabeccec885354.

2022-03-11 22:23 UTC, yossizap approved these changes
Code LGTM and tested in Windows. Thank you for the contribution :+1:

2022-03-14 07:49 UTC, XVilka approved these changes

2022-03-14 08:04 UTC, thestr4ng3r approved these changes

2022-03-14 08:04 UTC, merged