Rizin api
rizinorg/cutter pull request #2913
Opened 2022-03-25 06:01 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2022-03-28 18:19 UTC, thestr4ng3r commented
Please rebase on top of dev, the KSyntaxHighlighting changes are already there.

2022-03-29 07:50 UTC, imbillow commented
> Please rebase on top of dev, the KSyntaxHighlighting changes are already there.

ok

2022-03-31 12:08 UTC, XVilka commented
@imbillow please rebase

2022-03-31 12:36 UTC, b1llow commented
> @imbillow please rebase

ok

2022-03-31 13:46 UTC, XVilka approved these changes

2022-03-31 18:19 UTC, thestr4ng3r requested changes

2022-03-31 18:19 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +QVector<RzDebugPid *> CutterCore::getProcessThreads(int pid = -1)
This is either leaking or potentialls uaf-ing all the returned `RzDebugPid *`s, dependending on the list's free function, because that gets lost and the caller may not hold the core lock.
I would just put a `RzCoreLocked core(Core());` at all the call sites and use `rz_debug_pids()/rz_list_free()` directly.
Then this wrapper and `CutterRzListToQVector()` can be removed completely.

2022-03-31 18:19 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +        QString res = ((RizinCmdTask *)task.data())->getResult();
This cast is dangerous. Better use `qobject_cast()`.

2022-04-02 07:44 UTC, thestr4ng3r approved these changes

2022-04-02 07:44 UTC, merged