Created adding comments option inside Hexdump.
rizinorg/cutter pull request #2927
Opened 2022-04-07 18:30 UTC by Islam231bi

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This pull request adds the feature of adding comments for certain addresses inside the Hexdump widget. The implementation is nearly the same as adding comments in disassembly window. The pull request solves this issue #1070 as now adding, editing, and deleting comments in Hexdump menu is available. 

**Implementation:**
1 - Added (actionComment) action to the context menu.
`actionComment = new QAction(tr("Add Comment"), this);`
2 - Added (actionDeleteComment) action to context menu.
`actionDeleteComment = new QAction(tr("Delete Comment"), this); `
3 - Connected the created actions to the slots

`
connect(actionComment, &QAction::triggered, this, &HexWidget::on_actionAddComment_triggered);
`
`
connect(actionDeleteComment, &QAction::triggered, this, &HexWidget::on_actionDeleteComment_triggered);
`

4 - Used the same called and implemented functions in disassembly context menu inside the created slots.
5 - Check every time right click is done on the same part where comment is made to see whether there is a comment or not:
-if there is a comment then hide ("Add comment") and display ("Edit comment") and ("delete comment") instead.
This is implemeted through adding the following code inside (contextMenuEvent) function inside "HexWidget.cpp")

```
QString comment = Core()->getCommentAt(cursor.address);
    if (comment.isNull() || comment.isEmpty()) {
        actionDeleteComment->setVisible(false);
        actionComment->setText(tr("Add Comment"));
    } else {
        actionDeleteComment->setVisible(true);
        actionComment->setText(tr("Edit Comment"));
    }
```

**Test plan (required)**

I uploaded the video on drive:
https://drive.google.com/file/d/1xwL1g-4_yPxsDztIfiGd2HmfacFSQuji/view?usp=sharing

**Closing issues**

closes #1070

2022-04-12 13:11 UTC, XVilka requested changes
The code looks fine, but please remove the MP4 file from the repository.

2022-04-12 15:00 UTC, Islam231bi commented
> The code looks fine, but please remove the MP4 file from the repository.

Great I will do that.

2022-04-12 17:42 UTC, Islam231bi commented
Changes requested done @XVilka

2022-04-13 04:50 UTC, ITAYC0HEN approved these changes
Hey! And thank you for another nice contribution :)
This PR looks good to me, Merging 👍

2022-04-13 04:50 UTC, merged

2022-04-13 11:13 UTC, Islam231bi commented
Thanks a lot. It is a great experience contributing to the organization. I learned a lot

2022-04-13 11:13 UTC, Islam231bi commented
> Hey! And thank you for another nice contribution :) This PR looks good to me, Merging +1

Thanks a lot. It is a great experience contributing to the organization. I learned a lot.