Solved the bug of missing NX and PIC bits in Dashboard.
rizinorg/cutter pull request #2930
Opened 2022-04-13 14:49 UTC by Islam231bi

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This PR solves the problem of missing NX bit and PIC protections. The solution is to use rizin API directly.
Implementation:
1 - Remove using `setBool(this->ui->nxEdit, item, "nx");` and `setBool(this->ui->nxEdit, item, "pic");` 
2- Using the API directly by calling `RzBinInfo *binInfo = rz_bin_get_info(core->bin);` as this function returns a struct containing the correct values of NX bit and PIC bit: `has_nx` and `has_pi`
3 - calling the function `setNxPIC` that sets the linedit with the correct values:
```
void Dashboard::setNxPIC(RzBinInfo *binInfo)
{
    //setting text
    int nx = binInfo->has_nx;
    int pic = binInfo->has_pi;
    setPlainText(ui->nxEdit, tr(intToText(nx)));
    setPlainText(ui->picEdit, tr(intToText(pic)));
}
```
**This solution follows the trend of using the API directly inside the cutter #2666. This solution can be generalized to all the boolean values inside the dashboard**

**Test plan (required)**

1- open new file using cutter 
2- check the values of NX bit and PIC bit
3- you can confirm the correctness of the values using the command `$ rz-bin -I filename` or using `$ checksec --file=filename`

**Closing issues**

closes #2895

2022-04-13 15:14 UTC, wargio requested changes
I do not think this is the right way to fix this. i would try to understand why the nx, pic fields are not in the json object here used.

2022-04-13 15:16 UTC, wargio commented on src/widgets/Dashboard.cpp
> +    }
side note: this is dead code since it is impossible to reach this section. 
to enter the `if (value) {` the number has to be non-zero and for `else if (!value) {` it has to be zero, therefore you cover all the possible numbers for `int` type.

2022-04-13 15:35 UTC, Islam231bi commented
> I do not think this is the right way to fix this. i would try to understand why the nx, pic fields are not in the json object here used.

I tried to trace the error causing the bug but failed. so I presented this as an alternative solution for using the API directly. Here the function `rz_bin_get_info` returns a struct with the desired values. therefore, I accessed the values from this struct directly. I didn't need JSON to parse the values as I can use them directly.

2022-04-13 15:37 UTC, bassuniz commented on src/widgets/Dashboard.cpp
> +    }
Yes. Thank you for pointing this out. I just wanted to test the output quickly but forgot to change it.

2022-04-13 15:46 UTC, wargio commented
let me give you a different option, since we want to remove these hacks to get values from rizin and since you indeed have decided to use the best solution for this issue, i suggest then to convert all the values there to use the rizin C api so you can fix 2 issues with one PR.

2022-04-13 15:51 UTC, Islam231bi commented
> let me give you a different option, since we want to remove these hacks to get values from rizin and since you indeed have decided to use the best solution for this issue, i suggest then to convert all the values there to use the rizin C api so you can fix 2 issues with one PR.

Great, I will look into that.

2022-04-13 17:30 UTC, XVilka requested changes
Agree with @wargio - it's better to get all data using the API, not just those values.

2022-04-13 17:30 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +
Unnecessary change

2022-04-13 17:51 UTC, Islam231bi commented
> Agree with @wargio - it's better to get all data using the API, not just those values.

great I will do that.

2022-04-29 08:42 UTC, wargio commented on src/widgets/Dashboard.cpp
> +//    setBool(this->ui->picEdit, item, "pic");
```suggestion
```

2022-05-01 07:46 UTC, XVilka requested changes
Now it's the right approach.

2022-05-01 07:46 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    //setting boolean values
Please don't forget space between `//` and comment

2022-05-01 07:46 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +
Unnecessary change

2022-05-06 13:00 UTC, XVilka requested changes

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    setPlainText(this->ui->classEdit,binInfo->bclass);
Please be consistent with formatting and put space after comma.

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    // Using API directly to get values in dashboard
Unnecessary comment

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    // Setting text values from the API
Unnecessary comment.

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +
Unnecessary empty line

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> + * @brief Setting boolean values text according to parsed value from API
Too generic description, it's only for the binary information.

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +char* Dashboard::intToText(int value){
Can be removed.

2022-05-06 13:00 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    setPlainText(this->ui->strippedEdit,QVariant(stripped_value).toString());
Also formatting.

2022-05-08 14:35 UTC, XVilka requested changes

2022-05-08 14:35 UTC, XVilka commented on src/widgets/Dashboard.cpp
> +    return value ? "True" : "False";
Have you tried to use QVariant here?

2022-05-08 14:35 UTC, XVilka commented on src/widgets/Dashboard.h
> +    void setBoolvalues(RzBinInfo *binInfo);
To be consistent with other names it should be `setBoolValues()`. But the name is bad and too generic. It should be something indicating that it works only with the `RzBinInfo`, something like `setRzBinInfo()` or similar.

2022-05-08 15:04 UTC, Islam231bi commented on src/widgets/Dashboard.cpp
> +    return value ? "True" : "False";
Yes, but it returned "true" or "false" with lower case letters. I thought it should be uppercase.

2022-05-13 14:22 UTC, XVilka approved these changes

2022-05-30 16:31 UTC, thestr4ng3r approved these changes

2022-05-30 17:34 UTC, merged