Convert apis
rizinorg/cutter pull request #2948
Opened 2022-05-22 14:36 UTC by imbillow

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

Partially addresses #2666

2022-05-23 13:11 UTC, XVilka approved these changes
Looks good enough from the porting commands to the API point of view. However, the Cutter code doesn't handle errors at all. For example, these debug steps or reopening functions can easily fail and it's not handled at all. Of course, it wasn't handled even before, when commands were used. But this is outside of scope of this work and should be done separately. I will create a new issue to track that.

2022-05-23 13:37 UTC, ret2libc commented on src/core/Cutter.cpp
>      }
This seems slightly different from the old behaviour. Is that on purpose?

2022-05-23 13:49 UTC, b1llow commented on src/core/Cutter.cpp
>      }
Yes.

2022-05-23 20:30 UTC, pelijah commented on src/core/Cutter.cpp
> +    applyAtSeek(
`applyAtSeek` is redudant here since you use API.

2022-05-25 07:10 UTC, ret2libc commented on src/widgets/HexWidget.cpp
> +
let me add an API for this.

2022-05-25 07:21 UTC, ret2libc commented on src/widgets/HexWidget.cpp
> +
https://github.com/rizinorg/rizin/pull/2633

2022-05-26 01:25 UTC, XVilka approved these changes

2022-05-26 12:23 UTC, ret2libc approved these changes

2022-05-27 10:40 UTC, thestr4ng3r requested changes
overall looks good

2022-05-27 10:40 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +            auto *map = static_cast<RzIOMap *>(*it);
```suggestion
            auto *map = reinterpret_cast<RzIOMap *>(*it);
```

or even more elegantly:
```c++
for (auto map : CutterPVector<RzIOMap>(maps)) {
    // ...
```

2022-05-27 10:40 UTC, thestr4ng3r commented on src/widgets/HexWidget.cpp
> +    rz_core_write_at(core, getLocationAddress(), buf, len);
Better limit the scope of `RzCoreLocked` further, like:
```c++
// ...
{
    RzCoreLocked core(Core());
    auto *buf = (uint8_t *)calloc(len, sizeof(uint8_t));
    rz_core_write_at(core, getLocationAddress(), buf, len);
    free(buf);
}
refresh();
```
same applies to the cases below.

2022-05-28 08:06 UTC, thestr4ng3r approved these changes

2022-05-28 08:09 UTC, merged