Allow building Python bindings with Qt6
rizinorg/cutter pull request #2952
Opened 2022-05-29 08:43 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

When Qt6 is selected it was impossible to build the Python bindings.

**Test plan (required)**

CI is green

2022-05-29 08:45 UTC, XVilka commented
On Fedora 36 I get this though:
```
$ cmake -B build -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON -DCUTTER_ENABLE_GRAPHVIZ=ON -DCUTTER_QT6=ON
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:67 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/xvilka/rizin/cutter/build/CMakeFiles/CMakeOutput.log".
```

2022-11-02 14:13 UTC, wingdeans approved these changes
indentation

2022-11-02 15:56 UTC, wargio commented on CMakeLists.txt
> +		endif()
Looks like you changed the indentation from spaces to tabs.

2022-11-02 16:26 UTC, wargio approved these changes

2022-11-02 19:13 UTC, karliss requested changes

2022-11-02 19:13 UTC, karliss commented on CMakeLists.txt
> +				set(Shiboken2_VERSION_REQUIRED "${CMAKE_MATCH_1}")
On what system does this work? At least on Arch its called Shiboken6 and Pyside6 not Shiboken2 .

2022-11-02 19:19 UTC, karliss commented on CMakeLists.txt
> +				set(Shiboken2_VERSION_REQUIRED "${CMAKE_MATCH_1}")
Some of the official qt docs also refer to it as shiboken6 https://doc.qt.io/qtforpython-6.2/index.html

2022-11-02 19:42 UTC, karliss commented on CMakeLists.txt
> +				set(Shiboken2_VERSION_REQUIRED "${CMAKE_MATCH_1}")
More details from my testing on Arch.
I had to find_package Shiboken6Tools in addition to Shiboken6, because the definition for Shiboken6::shiboken6 executable has been moved there from.
```
        find_package(Shiboken6 "${Shiboken2_VERSION_REQUIRED}" REQUIRED)
        find_package(Shiboken6Tools "${Shiboken2_VERSION_REQUIRED}" REQUIRED)
        find_package(PySide6 "${Shiboken2_VERSION_REQUIRED}" REQUIRED)
```
Of course I also had to update all other uses of Shiboken2/Pyside2 in Cutter cmake files from 2 to 6. 

After that it got stuck while shiboken(Clang) was trying to parse Cutter headers because it failed to find some other Cutter headers. Probably include directory flags somehow get messed up. Didn't yet investigate how that happens and why it wasn't problem with Qt5/Shiboken2.

2023-02-13 06:41 UTC, wargio commented on src/CMakeLists.txt
> +		if (CUTTER_QT6)
mixed identation

2023-02-13 09:05 UTC, wargio approved these changes

2023-02-16 03:26 UTC, wargio commented
From my Arch machine
```
cutter (qt6_python) $ cmake -B qt6build -DCUTTER_QT6=ON -DCUTTER_ENABLE_SIGDB=ON -DCUTTER_PACKAGE_RZ_GHIDRA=ON -DCUTTER_PACKAGE_RZ_LIBSWIFT=ON -DCUTTER_PACKAGE_RZ_LIBYARA=ON -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON && make -C qt6build
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.5.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Found PythonInterp: /usr/bin/python (found version "3.10.9") 
-- Found PythonLibs: /usr/lib/libpython3.10.so (found suitable version "3.10.9", minimum required is "3.5") 
-- Shiboken6Config: Using default python: .abi3
-- Found PythonInterp: /usr/bin/python (found suitable version "3.10.9", minimum required is "3") 
-- Found PythonLibs: /usr/lib/libpython3.10.so (found suitable version "3.10.9", minimum required is "3") 
-- PYTHON_LIMITED_LIBRARIES: 
-- SHIBOKEN_PYTHON_INCLUDE_DIRS computed to value: '/usr/include/python3.10'
-- SHIBOKEN_PYTHON_LIBRARIES computed to value: ''
-- libshiboken built for None
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'libgvc'
--   Found libgvc, version 7.1.0
-- Found Graphviz: /usr/include/graphviz  
-- 
-- Building Cutter version 2.1.2-qt6_python-6e7cb58
-- Options:
-- - Bundled rizin: ON
-- - Bundled sigdb: ON
-- - Python: ON
-- - Python Bindings: ON
-- - KSyntaxHighlighting: ON
-- - Graphviz: TRUE
-- - Downloads dependencies: OFF
-- - Enable Packaging: OFF
-- - Package Dependencies: OFF
-- - Package RzGhidra: ON
-- - Package RzLibSwift: ON
-- - Package RzLibYara: ON
-- - Package JSDec: OFF
-- - QT6: ON
-- 
-- Configuring done
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "Cutter".

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

2023-02-16 04:46 UTC, XVilka commented on src/bindings/bindings.xml
> +        PythonToCppFunc pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(SbkPySide6_QtCoreTypeConverters[SBK_QSTRING_IDX], pyResult);
Not sure how to make this either `PySide6` or `PySide2` depending on the CMake variables.

Anyway, with these changes I was able to build everything successfully on Alpine Linux 3.17 Qt6/PySide6

2023-02-16 05:06 UTC, XVilka commented
@wargio your error looks similar to https://bugs.kde.org/show_bug.cgi?id=442296

2023-02-16 06:36 UTC, milahu commented on src/bindings/bindings.xml
> +        PythonToCppFunc pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(SbkPySide6_QtCoreTypeConverters[SBK_QSTRING_IDX], pyResult);
> Not sure how to make this either `PySide6` or `PySide2` depending on the CMake variables.

bindings.xml.in -> bindings.xml

same as bindings.txt.in -> bindings.txt

```cmake
configure_file("${BINDINGS_SRC_DIR}/bindings.txt.in" "${BINDINGS_BUILD_DIR}/bindings.txt")
```

2023-02-16 10:52 UTC, wargio commented
> @wargio your error looks similar to https://bugs.kde.org/show_bug.cgi?id=442296

yes it is indeed my issue but i don't know how to fix this

2023-02-17 09:57 UTC, milahu commented on src/common/PythonManager.cpp
>      if (!append) {
line 140 breaks with pyside6

```cc
    PySide::runCleanupFunctions();
```

```
/build/source/src/common/PythonManager.cpp: In member function 'void PythonManager::initialize()':
/build/source/src/common/PythonManager.cpp:79:23: warning: 'void PyEval_InitThreads()' is deprecated [-Wdeprecated-declarations]
   79 |     PyEval_InitThreads();
      |     ~~~~~~~~~~~~~~~~~~^~
In file included from /nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/include/python3.10/Python.h:130,
                 from /build/source/src/common/PythonAPI.h:5,
                 from /build/source/src/common/PythonManager.cpp:3:
/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/include/python3.10/ceval.h:122:37: note: declared here
  122 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
/build/source/src/common/PythonManager.cpp: In member function 'void PythonManager::shutdown()':
/build/source/src/common/PythonManager.cpp:140:13: error: 'runCleanupFunctions' is not a member of 'PySide'
  140 |     PySide::runCleanupFunctions();
      |             ^~~~~~~~~~~~~~~~~~~
```

2023-02-17 10:05 UTC, milahu commented on src/common/PythonManager.cpp
>      if (!append) {
in [13d4520d46e8fad8890ef1d718b8c2b30a2c6267](https://code.qt.io/cgit/pyside/pyside-setup.git/commit/?id=13d4520d46e8fad8890ef1d718b8c2b30a2c6267)
runCleanupFunctions was moved from `pyside.h` to `pysidecleanup.h`
but `#include "pysidecleanup.h"` was not added to `pyside.h`

```diff
--- a/sources/pyside6/libpyside/pyside.cpp
+++ b/sources/pyside6/libpyside/pyside.cpp
@@ -38,6 +38,11 @@
 ****************************************************************************/
 
 #include "pyside.h"
+#include "pysideinit.h"
+#include "pysidecleanup.h"
+#include "pysideqapp.h"
+#include "pysideqobject.h"
+#include "pysideutils.h"
 #include "pyside_numpy.h"
 #include "pyside_p.h"
 #include "signalmanager.h"
diff --git a/sources/pyside6/libpyside/pyside.h b/sources/pyside6/libpyside/pyside.h
index 39fbef3cc..9e0f6d1a6 100644
--- a/sources/pyside6/libpyside/pyside.h
+++ b/sources/pyside6/libpyside/pyside.h
@@ -44,8 +44,10 @@
 
 #include <pysidemacros.h>
 
-#include <QtCore/QMetaType>
-#include <QtCore/QHash>
+#include "pysideinit.h"
+#include "pysideqapp.h"
+#include "pysideqobject.h"
+#include "pysideutils.h"
 
 namespace QQmlPrivate
 {
```

2023-02-17 10:06 UTC, XVilka commented on src/common/PythonManager.cpp
>      if (!append) {
Strange, it should be handled already by inclusion of pyside_cleanup.h, whose presence is detected by CMake

2023-02-17 10:11 UTC, milahu commented on src/common/PythonManager.cpp
>      if (!append) {
should be handled by line 16

```cc
#ifdef HAVE_PYSIDECLEANUP
#    include <pysidecleanup.h>
#endif
```

2023-02-17 10:24 UTC, milahu commented on src/common/PythonManager.cpp
>      if (!append) {
nevermind. something is wrong with my env

```cmake
            # Check the presence of "pysidecleanup.h"
            include(CheckIncludeFileCXX)
            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
            message("debug: HAVE_PYSIDECLEANUP = ${HAVE_PYSIDECLEANUP}")
            message(FATAL_ERROR "FIXME this should be true")
```

```
-- Looking for C++ include pysidecleanup.h
-- Looking for C++ include pysidecleanup.h - not found
debug: HAVE_PYSIDECLEANUP = 
CMake Error at CMakeLists.txt:129 (message):
  FIXME this should be true
```

2023-02-17 10:35 UTC, XVilka commented on src/common/PythonManager.cpp
>      if (!append) {
Maybe setting some of these variables before calling this macros could help? https://cmake.org/cmake/help/latest/module/CheckIncludeFileCXX.html

2023-02-17 11:03 UTC, milahu commented on CMakeLists.txt
> +            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
this fails because

/build/source/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: pysidecleanup.h: No such file or directory

to make it work, i had to add both include paths (shiboken + pyside) to CMAKE_REQUIRED_INCLUDES

```cmake
            find_package(Shiboken6 "${Shiboken6_VERSION_REQUIRED}" REQUIRED)
            get_target_property(LIBSHIBOKEN_INCLUDE_DIRS Shiboken6::libshiboken INTERFACE_INCLUDE_DIRECTORIES)
            find_package(Shiboken6Tools "${Shiboken6_VERSION_REQUIRED}" REQUIRED)
            find_package(PySide6 "${Shiboken6_VERSION_REQUIRED}" REQUIRED)
            get_target_property(PYSIDE_INCLUDE_DIR PySide6::pyside6 INTERFACE_INCLUDE_DIRECTORIES)
            # Check the presence of "pysidecleanup.h"
            include(CheckIncludeFileCXX)
            set(CMAKE_REQUIRED_INCLUDES "${PYSIDE_INCLUDE_DIR};${LIBSHIBOKEN_INCLUDE_DIRS}")
            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
```

nit:

```diff
- PYSIDE_INCLUDE_DIR
+ PYSIDE_INCLUDE_DIRS
```

because can be multiple dirs ...

2023-02-17 11:27 UTC, milahu commented on CMakeLists.txt
> +            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
now this works

```
-- Looking for C++ include pysidecleanup.h - found
```

but the build still fails with

> ```/build/source/src/common/PythonManager.cpp:140:13: error: 'runCleanupFunctions' is not a member of 'PySide'```

debug

```c
#ifdef HAVE_PYSIDECLEANUP
#pragma message "HAVE_PYSIDECLEANUP=1: including pysidecleanup.h"
#    include <pysidecleanup.h>
#else
#pragma message "HAVE_PYSIDECLEANUP=0: not including pysidecleanup.h"
#endif
```

> /build/source/src/common/PythonManager.cpp:20:17: note: '#pragma message: HAVE_PYSIDECLEANUP=0: not including pysidecleanup.h'

fix

```cmake
            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
            add_compile_definitions("HAVE_PYSIDECLEANUP=${HAVE_PYSIDECLEANUP}")
```

2023-02-17 12:09 UTC, milahu commented on CMakeLists.txt
> +        if (CUTTER_QT6)
first impression with qt6 and breeze-dark theme

text in the "Type flag name or address here" input is not readable (black on black)

![Screenshot_20230217_130250](https://user-images.githubusercontent.com/12958815/219649650-872f666d-52bf-406c-be00-93aee9688525.png)

compare: cutter 2.1.2 with qt5

![Screenshot_20230217_130240](https://user-images.githubusercontent.com/12958815/219650001-b30ebe52-127b-4304-ba95-b16224912119.png)

2023-02-17 13:08 UTC, XVilka commented on CMakeLists.txt
> +            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
Done, thank you for pointing this out!

2023-02-17 13:10 UTC, XVilka commented on CMakeLists.txt
> +        if (CUTTER_QT6)
@milahu could you please git pull, remove old `build` directory and retry? Also, what platform/distribution/version do you use?

2023-02-17 13:41 UTC, milahu commented on CMakeLists.txt
> +            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
this line is missing

```
            get_target_property(LIBSHIBOKEN_INCLUDE_DIRS Shiboken6::libshiboken INTERFACE_INCLUDE_DIRECTORIES)
```

2023-02-17 13:45 UTC, milahu commented on CMakeLists.txt
> +        if (CUTTER_QT6)
> what platform/distribution/version do you use?

nixos linux
cutter 235b75f3ed1e2f1310bef889256188579777eced + this PR

https://github.com/milahu/nixpkgs/blob/cutter-unstable-2023-02-15/pkgs/development/tools/analysis/rizin/cutter.nix

2023-02-17 14:02 UTC, XVilka commented on CMakeLists.txt
> +            CHECK_INCLUDE_FILE_CXX("pysidecleanup.h" HAVE_PYSIDECLEANUP)
Added, thank you! Also renamed `PYSIDE_INCLUDE_DIR` -> `PYSIDE_INCLUDE_DIRS`.

2023-02-17 14:47 UTC, milahu commented on CMakeLists.txt
> +            ${PYSIDE_INCLUDE_DIRS}/QtWidgets)
```cmake
        foreach(_dir IN LISTS PYSIDE_INCLUDE_DIRS)
            include_directories(${_dir}
                ${_dir}/QtCore
                ${_dir}/QtGui
                ${_dir}/QtWidgets)
        endforeach()
```

2023-02-17 17:10 UTC, milahu commented on CMakeLists.txt
> +        if (CUTTER_QT6)
similar issue: in debugger, the toolbar buttons are not visible

![Screenshot_20230217_180844](https://user-images.githubusercontent.com/12958815/219718535-5a354d4e-48b0-47eb-b74b-91693c9c2e3e.png)

2023-02-17 19:21 UTC, milahu commented on CMakeLists.txt
> +        if (CUTTER_QT6)
resolved

black text is a qt bug https://bugreports.qt.io/browse/QTBUG-86195

missing icons are result of my broken build. works with a clean build

2023-02-18 01:29 UTC, XVilka commented
I believe this is already an improvement since it allows building Python + Qt6 at least on *some* systems without breaking Qt5. Support for other systems could be added separately.

2023-02-18 15:40 UTC, wargio commented
i think you are missing also this https://github.com/rizinorg/cutter/blob/dev/cmake/FindPySide2.cmake but for pyside6

2023-02-18 18:21 UTC, milahu commented on CMakeLists.txt
> +        list(GET PYSIDE_INCLUDE_DIRS 0 PYSIDE_INCLUDE_DIRS)
remove this line

2023-02-18 18:27 UTC, milahu commented
currently pyside is added with `PYSIDE_LIBRARY` and `PYSIDE_INCLUDE_DIRS`
(build works ... did someone test the python bindings?)

but yeah, [FindPySide6.cmake](https://github.com/search?q=filename%3AFindPySide6.cmake) could make it shorter

2023-02-23 07:04 UTC, milahu commented on cmake/FindPySide2.cmake
> +    find_path(PYSIDE_INCLUDE_DIRS
nit: this is singular = PYSIDE_INCLUDE_DIR

2023-02-23 07:06 UTC, milahu commented on src/common/PythonManager.cpp
> +#endif
please add comment: this is needed for pyside6

2023-05-11 08:44 UTC, wargio approved these changes

2023-05-11 11:35 UTC, wargio commented
it crashes with the latest changes from dev related to the history.

2023-05-20 05:05 UTC, merged

2023-05-20 05:06 UTC, XVilka commented
I merged since it already works for some platforms so already an improvement