Convert to rizin APIs
rizinorg/cutter pull request #2973
Opened 2022-06-20 01:41 UTC by imbillow

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

Partially addresses https://github.com/rizinorg/cutter/issues/2666

2022-06-21 13:22 UTC, XVilka approved these changes
This will also fix https://github.com/rizinorg/cutter/issues/2687#issuecomment-1161736943 but cannot be a part of 2.1.0 because of the amount changes neeeded

2022-06-21 13:32 UTC, XVilka commented
Strange error on Windows:
```

CPack: - Install project: Cutter []
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:36 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_core-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:40 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_config-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:44 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_cons-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:48 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_io-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:52 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_util-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:56 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_flag-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:60 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_asm-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:64 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_debug-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:68 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_hash-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:72 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_bin-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:76 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_lang-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:80 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_il-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:84 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_analysis-0.4.dll":
  File exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:88 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_parse-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:92 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_bp-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:96 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_egg-0.4.dll": File
  exists.
CMake Error at D:/a/cutter/cutter/build/cmake_install.cmake:100 (file):
  file INSTALL cannot find "D:/a/cutter/cutter/build/rz_reg-0.4.dll": File
  exists.
```
cc @ret2libc @thestr4ng3r

2022-06-23 14:14 UTC, XVilka commented
@imbillow could you please rebase on top of the latest `dev` in Cutter and import latest commit from `dev` in Rizin?

2022-06-23 14:34 UTC, imbillow commented
> @imbillow could you please rebase on top of the latest `dev` in Cutter and import the latest commit from `dev` in Rizin?

OK

2022-06-25 03:58 UTC, XVilka commented
I wonder why CPack tries to find the 0.4.0 DLL while the latest `dev` version was changed to 0.5.0:
```
CPack: - Install project: Cutter []
CMake Error at C:/projects/cutter/build/cmake_install.cmake:36 (file):
  file INSTALL cannot find "C:/projects/cutter/build/rz_core-0.4.dll": File
  exists
```

2022-06-25 05:41 UTC, imbillow commented
> I wonder why CPack tries to find the 0.4.0 DLL while the latest `dev` version was changed to 0.5.0:
> 
> ```
> CPack: - Install project: Cutter []
> CMake Error at C:/projects/cutter/build/cmake_install.cmake:36 (file):
>   file INSTALL cannot find "C:/projects/cutter/build/rz_core-0.4.dll": File
>   exists
> ```

I found it

https://github.com/rizinorg/cutter/blob/f99ffc3dbde8c437f45f04d1a3e57584b712234f/cmake/BundledRizin.cmake#L57-L59

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
why this?

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        linkItemL->setText(1, "");
why

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        linkNameItemL->setText(1, "");
why

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemR->setText(1, "");
why

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemR->setText(1, "");
well, same for all `""` in this file

2022-06-25 08:24 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
>  void VersionInfoDialog::fillVersionInfo()
did you test whether this dialog still works well for all type of files after this big change?

2022-06-25 08:38 UTC, imbillow commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
Because the current version of rizin does not output there informations, maybe it was there before?

2022-06-25 08:53 UTC, imbillow commented on src/dialogs/VersionInfoDialog.cpp
>  void VersionInfoDialog::fillVersionInfo()
It's OK.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/24983369/175766043-c9e6343e-2f97-4022-b7a8-30ce0644fa23.png">
<img width="602" alt="image" src="https://user-images.githubusercontent.com/24983369/175766063-beea18f2-acc4-4014-bbed-50dc83fe4621.png">

2022-06-28 07:38 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
If possible I would keep these things and actually implement later them on rizin side. Does it crash if you don't replace these?

2022-06-29 16:48 UTC, imbillow commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
https://github.com/rizinorg/rizin/commit/33d4d081bf0a1d829041bae1675c29f95ce9dfe9#diff-3f97fa549a4b7752e60c646c781a7c013401b28b9ddc18efc0a0a5cc3d713d79

2022-06-29 17:54 UTC, imbillow commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
Maybe we can remove these items.

2022-06-30 07:21 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
> +        secNameItemL->setText(1, "");
I see... those removal of the version info probably went unnoticed. I don't think there was a good reason to remove information.

Anyway, ok for now.

2022-07-01 12:28 UTC, XVilka approved these changes

2022-07-01 12:35 UTC, ret2libc commented on src/dialogs/VersionInfoDialog.cpp
>  void VersionInfoDialog::fillVersionInfo()
Could you check again and provide a snapshot if this is still working well please?

2022-07-02 09:43 UTC, thestr4ng3r requested changes
For macho and blft for example I get this saying just "TextLabel". But I haven't checked if it's a regression:
![Bildschirmfoto 2022-07-02 um 11 40 30](https://user-images.githubusercontent.com/1460997/176995296-a6a8c15a-4079-4c63-a031-476d71906ce7.png)

2022-07-02 09:43 UTC, thestr4ng3r commented on src/dialogs/VersionInfoDialog.cpp
> +    if (strncmp("elf", info->rclass, 3) == 0) {
`info->rclass` may be null

2022-07-02 09:43 UTC, thestr4ng3r commented on src/dialogs/VersionInfoDialog.cpp
> +    else if (strncmp("pe", info->rclass, 2) == 0) {
same here

2022-07-02 11:44 UTC, imbillow commented on src/dialogs/VersionInfoDialog.cpp
>  void VersionInfoDialog::fillVersionInfo()
![image](https://user-images.githubusercontent.com/24983369/176999258-78bfc2ff-b108-4292-a896-2d02542578e9.png)
![image](https://user-images.githubusercontent.com/24983369/176999318-c22ab957-56d4-4acb-87e9-846becf071f7.png)

macho

![image](https://user-images.githubusercontent.com/24983369/176999349-00e0da29-b562-41c2-87d4-e6bb4614651c.png)

blft

![image](https://user-images.githubusercontent.com/24983369/176999385-8ce6aa53-939a-420c-be73-6809b820ce41.png)

2022-07-02 13:47 UTC, thestr4ng3r approved these changes

2022-07-02 13:49 UTC, merged