Convert cmds to rizin APIs
rizinorg/cutter pull request #2996
Opened 2022-07-09 11:36 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

* `pdj` `pdJ` -> rizin APIs
* deleted `pd--` -> `pd`
* update rizin to latest dev

**Test plan (required)**

**Closing issues**

2022-07-09 14:34 UTC, thestr4ng3r requested changes
There seems to be always a block of disassembled data on top of the disassembly that never changes when scrolling:
https://user-images.githubusercontent.com/1460997/178110263-6d09531c-3715-4fe6-82ba-cda5dd83ba23.mov

2022-07-10 03:45 UTC, imbillow commented
> The code being disassembled does not seem to change when scrolling through the disasm:
> 
> 
> 
> https://user-images.githubusercontent.com/1460997/178110311-2dc30d50-456b-4c4f-b3aa-7eb9c5259bf2.mov
> 
> 
> 
> 
> 
> 
> 
> 

I see it shouldn't have this problem now.

2022-07-10 16:21 UTC, XVilka requested changes

2022-07-10 16:21 UTC, XVilka commented on src/dialogs/XrefsDialog.cpp
> +    QString disas = Core()->cmd("pd 40 @" + QString::number(addr - 20));
Is it possible to convert this call as well?

2022-07-10 19:41 UTC, imbillow commented on src/dialogs/XrefsDialog.cpp
> +    QString disas = Core()->cmd("pd 40 @" + QString::number(addr - 20));
I updated with a solution.

2022-07-10 23:11 UTC, imbillow commented
```
fatal: destination path '/private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-3165369561/rizinorg/cutter/rizin' already exists and is not an empty directory.
fatal: clone of 'https://github.com/rizinorg/rizin' into submodule path '/private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-3165369561/rizinorg/cutter/rizin' failed
Failed to clone 'rizin'. Retry scheduled
Cloning into '/private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-3165369561/rizinorg/cutter/src/translations'...
fatal: destination path '/private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-3165369561/rizinorg/cutter/rizin' already exists and is not an empty directory.
fatal: clone of 'https://github.com/rizinorg/rizin' into submodule path '/private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-3165369561/rizinorg/cutter/rizin' failed
Failed to clone 'rizin' a second time, aborting
exit status 1
```

2022-07-13 14:17 UTC, XVilka commented
@imbillow please update to the latest Rizin: https://github.com/rizinorg/rizin/commit/b79201b49a0d687c854b6e2f0c88fc8a7f2afa61

2022-07-13 22:02 UTC, wargio commented
```
CutterJson.h:73:37: error: no matching function for call to 'rz_json_as_string'
    QString toJson() const { return rz_json_as_string(value); }
```

2022-07-14 13:07 UTC, wargio approved these changes

2022-07-14 14:43 UTC, XVilka approved these changes

2022-08-01 15:56 UTC, thestr4ng3r approved these changes

2022-08-01 15:57 UTC, merged