Convert `agJ` to rizin APIs
rizinorg/cutter pull request #3005
Opened 2022-08-01 11:25 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2022-08-01 14:29 UTC, XVilka requested changes
```
:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2332: 'struct': missing tag name
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2556: '*__timezone(void)': overloaded function differs only by return type from 'long *__timezone(void)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(74): note: see declaration of '__timezone'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2371: '__timezone': redefinition; different basic types
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(74): note: see declaration of '__timezone'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2491: '__timezone': definition of dllimport function not allowed
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2332: 'struct': missing tag name
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2143: syntax error: missing ',' before '*'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2059: syntax error: '*'
ninja: build stopped: subcommand failed.
Command exited with code 1
```

2022-08-01 14:29 UTC, XVilka commented on src/widgets/DisassemblerGraphView.cpp
> +                                                                                         -1),
Formatting looks broken here

2022-08-01 15:02 UTC, imbillow commented
Maybe it's because of redefinition to `__timezone`, but it's `timezone` in `rz_time.h`, which is confusing

2022-08-09 15:55 UTC, XVilka approved these changes

2022-08-10 14:06 UTC, XVilka requested changes

2022-08-10 14:06 UTC, XVilka commented on src/widgets/DisassemblerGraphView.cpp
> +    QString fcn_name = "Empty";
The suggestion by @karliss applies here as well: https://github.com/rizinorg/cutter/pull/3012#discussion_r942455726

2022-08-10 14:06 UTC, XVilka commented on src/widgets/DisassemblerGraphView.cpp
> +        RzAnalysisSwitchOp *switch_op = bbi->switch_op;
Same here

2022-08-10 14:06 UTC, XVilka commented on src/widgets/DisassemblerGraphView.cpp
> +        auto vec_visitor = CutterPVector<RzAnalysisDisasmText>(vec.get());
And here

2022-08-10 14:06 UTC, XVilka commented on src/core/Cutter.cpp
> +    std::unique_ptr<RzPVector, decltype(rz_pvector_free) *> vec {
@karliss, you are the C++ expert, is it possible to simplify this block?

2022-08-10 17:21 UTC, XVilka approved these changes

2022-08-11 06:35 UTC, karliss commented on src/core/Cutter.cpp
> +    std::unique_ptr<RzPVector, decltype(rz_pvector_free) *> vec {
I have a couple of ideas for some rizin C++ helpers which could make the cutter code interacting with it slightly cleaner, but that's more of a job for separate issue.

2022-08-11 06:38 UTC, karliss commented on src/core/Cutter.cpp
> +    std::unique_ptr<RzPVector, decltype(rz_pvector_free) *> vec {
Also my opinion that most Rizin functions which force caller to temporary change seek is bad API and indicator that those functions should probably have offset argument.

2022-08-11 06:40 UTC, karliss commented
Will probably fix #2800 (although I am not sure about underlying cause of printing invalid json which would still be good to fix in rizin). Need to recheck after this is PR is merged.

2022-08-11 10:04 UTC, XVilka commented on src/core/Cutter.cpp
> +    std::unique_ptr<RzPVector, decltype(rz_pvector_free) *> vec {
Agree, we should open an issue about that in Rizin, probably worth fixing before 0.5.0

2022-08-11 10:05 UTC, merged