Convert `pdsf` to API
rizinorg/cutter pull request #3010
Opened 2022-08-09 18:25 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

`CutterCore->opcodes` is only used in `Highlighter`, and `Highlighter` has not been used. Even there is no `?O` handler in rizin, so remove it.

Convert `pdsf` to API.

**Test plan (required)**

**Closing issues**

2022-08-10 13:36 UTC, XVilka requested changes
The rest looks good.

2022-08-10 13:36 UTC, XVilka commented on src/core/MainWindow.cpp
> +    auto size = static_cast<int>(Core()->num("$s"));
Hmm, I wonder if using the API/struct member here would be more appropriate. @ret2libc @wargio thoughts?

2022-08-10 17:20 UTC, XVilka approved these changes
Please rebase to fix the Rizin submodule conflict

2022-08-10 17:40 UTC, imbillow commented
OK

2022-08-11 00:17 UTC, XVilka approved these changes

2022-08-11 05:44 UTC, karliss commented on src/core/MainWindow.cpp
> +        return;
This is useless. Default new operator in c++ never returns null.

2022-08-11 06:13 UTC, karliss commented on src/core/MainWindow.cpp
> +    auto buffer = std::unique_ptr<ut8[]> { new ut8[size] };
I would consider using `std::vector<ut8> buffer(size)` instead of `unique_ptr` for something like this. Performance difference shouldn't matter in this situation but unique_ptr of array in my opinion results in more clunky and harder to read code.

2022-08-11 06:19 UTC, karliss approved these changes
None of my comments are critical. Can be merged with or without them.

2022-08-11 10:14 UTC, XVilka commented
@imbillow please address these comments and we can merge this.

2022-08-11 10:23 UTC, wargio commented on src/core/MainWindow.cpp
> +        return;
partially true, it does return nullptr when the exceptions are disabled, but yeah i agree with you that this is an unnecessary check.

2022-08-11 12:45 UTC, XVilka approved these changes

2022-08-11 12:46 UTC, merged