Convert cmd `.`
rizinorg/cutter pull request #3017
Opened 2022-08-11 15:21 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2022-08-11 17:05 UTC, karliss commented on src/core/Cutter.cpp
> +    task->joinTask();
I am not too familiar with the task infrastructure @thestr4ng3r  made, but this seems redundant. If `functionTask` is immediately starting the task and waiting for it to finish, you might as well do core lock directly and the thing you want to do.

2022-08-11 17:22 UTC, imbillow commented on src/core/Cutter.cpp
> +    task->joinTask();
https://github.com/rizinorg/cutter/blob/617c79f97653c52f7d4d36fcb4e5f0a86c94723c/src/core/Cutter.cpp#L556-L562

I imitated what I wrote here, and as you say, maybe there is no need for a Task that is not async at all

2022-08-11 17:35 UTC, XVilka commented on src/core/Cutter.cpp
> +    task->joinTask();
Yes, I think @karliss is right, in this case no need for the task, but I am not very familiar with this feature as well, better to wait what @thestr4ng3r has to say about this.

2022-08-11 17:45 UTC, thestr4ng3r commented on src/core/Cutter.cpp
> +    task->joinTask();
> If functionTask is immediately starting the task and waiting for it to finish, you might as well do core lock directly and do the thing you want to do.

Not exactly. The core can only be held locked by one thread at a time. But it is possible to do this start+join pattern concurrently multiple times and the running tasks will be scheduled in an interlocked fashion. Also it is possible to break such a running task.

2022-08-12 01:55 UTC, XVilka approved these changes

2022-08-12 07:03 UTC, karliss requested changes

2022-08-12 07:03 UTC, karliss commented on src/core/Cutter.cpp
> +    RzList *vars = rz_analysis_var_all_list(Core()->core()->analysis, fcn);
The values `RZAnalysisVar` are owned by function and not self contained so to ensure that some other task doesn't modify them core lock should be held while processing the list returned by `rz_analysis_var_all_list`.
 
Similar reasoning applies function structure obtained with `functionIn` so  meaning that lock should be started at the start of function.

2022-08-12 20:11 UTC, imbillow commented
```
/home/runner/work/cutter/cutter/build/dist/rz-ghidra-prefix/src/rz-ghidra/src/RizinScope.cpp:10:10: fatal error: rz_build_version.h: No such file or directory
 #include <rz_build_version.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2022-08-12 20:20 UTC, karliss commented
> ```
> /home/runner/work/cutter/cutter/build/dist/rz-ghidra-prefix/src/rz-ghidra/src/RizinScope.cpp:10:10: fatal error: rz_build_version.h: No such file or directory
>  #include <rz_build_version.h>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

That's probably caused by https://github.com/rizinorg/rz-ghidra/pull/294

2022-08-13 10:29 UTC, XVilka commented
@imbillow @karliss, just update Rizin to the latest commit, it should fix the problem.

2022-08-13 11:30 UTC, XVilka commented
@imbillow also Cutter seems need an update too:
```
/home/runner/work/cutter/cutter/src/dialogs/AboutDialog.cpp:1:10: fatal error: rz_version.h: No such file or directory
    1 | #include "rz_version.h"
      |          ^~~~~~~~~~~~~~
```

2022-08-13 12:48 UTC, XVilka approved these changes

2022-08-14 09:08 UTC, karliss approved these changes

2022-08-14 09:10 UTC, merged