Introduce some helpers to deal with rizin C API more cleanly.
rizinorg/cutter pull request #3020
Opened 2022-08-12 12:47 UTC by karliss

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Note that these changes are somewhat subjective so I would like to hear what others think whether it actually looks more readable to you. There is a bit of tradeoff between noise and being more explicit.

* Move some of the rizin C++ helpers from CutterCommon to RizinCpp and introduce a few new ones.
* make `QString fromOwnedCharPtr(char*)` available everywhere
* add `fromOwned(T*, void(*deleter)(T*)) -> std::unique_ptr` 
* overloads of `fromOwned(x)` for most common rizin containers like RzList and RzPVector which don't require manually specifying the free function

* refactor `CutterCore::tempSeek` implementation so that it doesn't abuse `unique_ptr`
* Replace  `applyAtSeek` and `returnAtSeek` with the existing `CutterCore::tempSeek`

those functions have a couple of downsides

1) Converting lambda to std::function has some overhead. It probably doesn't matter too much but there is a solution which doesn't require it.
2) (my subjective opinion) all the extra tokens  for declaring block of code as lambda adds noise making it more  difficult to read compared to regular block with temporary seek object at start.
3) in some of the cases core lock was done inside the lambda, which means that in theory the seek could change between  `applyAtSeek` reading seek position and calling the lambda

**Test plan (required)**

**Closing issues**

2022-08-12 13:25 UTC, XVilka requested changes
Code looks fine. Maybe in the future we could even make them even more generic and provide by Rizin itself, in case someone would want to write their own software in C++ that uses Rizin library.

BTW, are you aware of the https://github.com/rizinorg/rz-bindgen? 

cc @wingdeans

2022-08-12 13:25 UTC, XVilka commented on src/core/RizinCpp.h
> + * Various utilities for easier and sefer interactions with Rizin
"safer"

2022-08-12 13:25 UTC, XVilka commented on src/core/RizinCpp.h
> + * from c++ code.
"C++"

2022-08-12 13:25 UTC, XVilka commented on src/core/RizinCpp.h
> +#define CutterRzListForeach(list, it, type, x)                                                     \
Maybe also makes sense to unify naming of the functions in this file - "RzHelper" prefix, or "rzHelper" or something like that, because some called "CutterRz...", some - "fromOwned", not sure if it's a right way.

2022-08-12 13:25 UTC, XVilka commented on src/core/RizinCpp.h
> +// Rizin list iteration macros
Maybe convert this into Doxygen?

2022-08-12 14:57 UTC, imbillow commented
You are a cpp expert！

2022-08-12 16:20 UTC, thestr4ng3r approved these changes

2022-08-12 16:20 UTC, thestr4ng3r commented on src/core/RizinCpp.h
> +#define CutterRzListForeach(list, it, type, x)                                                     \
Just as a comment, this and `CutterRzVectorForeach` should probably be deprecated in favor of C++11 foreach over `CutterPVector` and `CutterRzList`.

2022-08-12 17:06 UTC, karliss commented on src/core/RizinCpp.h
> +#define CutterRzListForeach(list, it, type, x)                                                     \
I agree. Part of the stuff like it was already there I just moved it to separate file.  Didn't want to do all that in one go.  CutterRzVectorForeach is used only in few places, but RzList one a  lot more.

2022-08-12 18:50 UTC, karliss commented on src/core/Cutter.h
> +        SeekReturn(SeekReturn &&) = default;
This is wrong. After move the returner which was moved away shouldn't try to return in destructor.

2022-08-13 01:36 UTC, wingdeans approved these changes

2022-08-13 01:36 UTC, wingdeans commented on src/core/Cutter.cpp
> +        auto restoreSeek = this->seekTemp(offset);
```suggestion
        auto restoreSeek = seekTemp(offset);
```
For consistency

2022-08-13 08:03 UTC, imbillow approved these changes
LGTM

2022-08-13 08:03 UTC, imbillow commented on src/core/Cutter.cpp
> +    {
Is it reasonable to remove this scope here?

2022-08-13 08:11 UTC, imbillow commented on src/core/Cutter.h
> +    SeekReturn seekTemp(RVA address)
Since `(apply|return)AtSeeks` can be replaced by `seekTemp`, the former can be removed.

2022-08-13 08:14 UTC, karliss commented on src/core/Cutter.cpp
> +    {
Probably yes.  The code afterwards doesn't seem to do anything which could be impacted by it.  Will do that during a cleanup pass, hopefully this evening or tomorrow. I am sorry if I am delaying or interfering with  your changes.

2022-08-13 08:17 UTC, karliss commented on src/core/Cutter.h
> +    SeekReturn seekTemp(RVA address)
Isn't this PR already doing that? They look red to me in the diff. Or is there a variant that I missed?

2022-08-13 08:33 UTC, imbillow commented on src/core/Cutter.h
> +    SeekReturn seekTemp(RVA address)
emm... forgot it.

2022-08-13 09:25 UTC, wargio commented on src/core/RizinCpp.h
> +    rz_mem_free(str);
just `free` is probably better.

2022-08-13 18:52 UTC, thestr4ng3r commented on src/core/RizinCpp.h
> +    rz_mem_free(str);
If the string comes from rizin, it must be `rz_mem_free` and not `free`.

2022-08-13 19:53 UTC, karliss commented on src/core/RizinCpp.h
> +// Rizin list iteration macros
Since they are going to be removed left as is for now.

2022-08-13 20:12 UTC, merged