convert `?E` to API
rizinorg/cutter pull request #3025
Opened 2022-08-15 19:54 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

2022-08-16 00:01 UTC, XVilka approved these changes

2022-08-16 05:49 UTC, karliss requested changes

2022-08-16 05:49 UTC, karliss commented on src/plugins/sample-cpp/CutterSamplePlugin.cpp
> +        RzCoreLocked core(Core());
It wouldn't hurt moving the lock before modifying config.

2022-08-16 05:49 UTC, karliss commented on src/plugins/sample-cpp/CutterSamplePlugin.cpp
>      // this is especially good for user-controlled input
Both the fortune and `char*` string return by rz_core_clippy probably need to be freed to avoid memory leak.  Check the signature and if not specified in header implementation whether it returns owned string.

2022-08-16 16:25 UTC, XVilka commented on src/plugins/sample-cpp/CutterSamplePlugin.cpp
>      // this is especially good for user-controlled input
Probably also it's better to remove that comment about `cmdRaw` and don't encourage users to do the wrong thing.

2022-08-16 18:37 UTC, karliss commented on src/plugins/sample-cpp/CutterSamplePlugin.cpp
>      // this is especially good for user-controlled input
I am not sure if using `cmd` commands in plugins are always the wrong thing. Especially if it's a quick and dirty python plugin. The  commands are still an interface for interacting with rizin and one that user might be more familiar than the C api.

2022-08-16 19:06 UTC, imbillow commented on src/plugins/sample-cpp/CutterSamplePlugin.cpp
>      // this is especially good for user-controlled input
When I use powershell I feel like it is a shell built around the APIs, but rizin seems to be in the opposite direction

2022-08-17 18:29 UTC, karliss approved these changes

2022-08-17 22:52 UTC, merged