[WIP] Editting support in hex editor
rizinorg/cutter pull request #3026
Opened 2022-08-16 13:13 UTC by karliss

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

Closes #2931

2022-08-16 16:23 UTC, XVilka requested changes

2022-08-16 16:23 UTC, XVilka commented on src/widgets/HexWidget.cpp
> +    ComitEditedWord(true);
`Commit`, I suppose.

2022-08-16 17:37 UTC, karliss commented on src/widgets/HexWidget.cpp
> +    ComitEditedWord(true);
Yes, I noticed that while writing but couldn't be bothered renaming at that point because there were a bunch of more important things to think about.

I wouldn't recommend wasting time looking typos other polishing details at this point. It's still very very early and rough state. I made the PR public mostly to make it easier following progress and give the general idea of approach I am going for.

2022-08-17 16:13 UTC, XVilka commented on src/widgets/HexWidget.cpp
> +    ComitEditedWord(true);
It's not something I actively search for, just saw it immediately while looking at the code.

2022-08-21 22:19 UTC, wargio approved these changes

2022-08-21 22:19 UTC, wargio commented
tested on linux

2022-08-21 22:26 UTC, ret2libc commented
tried quickly on macos.. the "Editing with keyboard" feature was a bit surprising at the very beginning. I was not sure how to exit that insert mode and I realized only few seconds later that it was a "boolean" setting rather than a one-time insertion. Overall, I don't think it is such a big deal.

2022-08-22 03:35 UTC, XVilka requested changes
Doesn't build with QT6 (`cmake -B build -DCUTTER_QT6=ON -DCUTTER_ENABLE_SIGDB=ON` ) on MacOS 12.5.1 on ARM64:
```
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:583:35: error: no matching function for call to 'min'
                    editWordPos = std::min(editWordPos, editWord.length());
                                  ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long long')
min(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'int'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:59:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:30:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:619:31: error: no matching function for call to 'min'
                editWordPos = std::min(wordOffset, editWord.length() - 1);
                              ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long long')
min(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'int'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:59:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:30:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:648:23: error: no matching function for call to 'max'
        int padding = std::max(0, itemCharLen - editWord.length());
                      ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long long')
max(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'int'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:59:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:30:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:650:23: error: no matching function for call to 'min'
        editWordPos = std::min(editWordPos, editWord.length());
                      ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long long')
min(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'int'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:59:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:30:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:813:18: error: conversion from 'int' to 'QChar' is ambiguous
        if (c <= 0x1f || c == 0x7f) {
                 ^~~~
/opt/homebrew/include/QtCore/qchar.h:112:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(ushort rc) noexcept : ucs(rc) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:114:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(short rc) noexcept : ucs(char16_t(rc)) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:119:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(char16_t ch) noexcept : ucs(ch) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:126:45: note: candidate constructor
    QT_ASCII_CAST_WARN constexpr Q_IMPLICIT QChar(char c) noexcept : ucs(uchar(c)) { }
                                            ^
/opt/homebrew/include/QtCore/qchar.h:619:61: note: passing argument to parameter 'c2' here
    friend constexpr inline bool operator<=(QChar c1, QChar c2) noexcept { return !operator< (c2, c1); }
                                                            ^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:813:31: error: conversion from 'int' to 'QChar' is ambiguous
        if (c <= 0x1f || c == 0x7f) {
                              ^~~~
/opt/homebrew/include/QtCore/qchar.h:112:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(ushort rc) noexcept : ucs(rc) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:114:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(short rc) noexcept : ucs(char16_t(rc)) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:119:26: note: candidate constructor
    constexpr Q_IMPLICIT QChar(char16_t ch) noexcept : ucs(ch) {}
                         ^
/opt/homebrew/include/QtCore/qchar.h:126:45: note: candidate constructor
    QT_ASCII_CAST_WARN constexpr Q_IMPLICIT QChar(char c) noexcept : ucs(uchar(c)) { }
                                            ^
/opt/homebrew/include/QtCore/qchar.h:613:61: note: passing argument to parameter 'c2' here
    friend constexpr inline bool operator==(QChar c1, QChar c2) noexcept { return c1.ucs == c2.ucs; }
                                                            ^
/Users/user/Rizin/cutter/src/widgets/HexWidget.cpp:1090:27: error: no matching function for call to 'min'
            editWordPos = std::min(editWord.length(), editWordPos + 1);
                          ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long long' vs. 'int')
min(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'long long'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/min.h:59:1: note: candidate function template not vi [...]

2022-08-22 05:14 UTC, GustavoLCR commented
Here's a review. It's probably better to put some of these in their own separate issues/PRs instead of being addressed in this one.

## Editing
* Float edit
  - Doesn't accept dot/comma from numpad (bug)
  - Only accepts dot as decimal separator (should accept a comma as well)
  - Doesn't support inputting fractions (nice to have)
* Ctrl-c Ctrl-v between ascii view and hex view doesn't work. I expect the underlying bytes to be pasted, but the hex or ascii representation should be put in the clipboard
* Selecting a big range and Ctrl-c Ctrl-v is slow
* Show last edit in red. If edit was done with `edit with keyboard`, edited bytes should be red until the cursor is moved without a write
* A keyboard shortcut to enter/exit `Edit with keyboard` would be nice

## Navigation
* Show a blinking cursor only if `Edit with keyboard` is enabled, use box with inverted colors as a cursor otherwise
* Hide mouse cursor when editing/navigating via keyboard and its inside widget, restore it if mouse moves
* Clicking on a float/decimal may put the cursor in the next item, instead of the current one
* When item size >= 2, selecting bytes via the ascii column, the reflection of the selection on the item view seems to under/overshoot, and sometimes the box will be in the middle of a character

## Dialogs
* Duplicate from offset
  - Preview is not very good, only shows utf8
  - Doesn't take selection size as default nbytes
* Dialogs should show offset of operation on title
* Dialogs should temporarily update/create selection, to indicate how many bytes they will affect
* Dialogs should be non-modal, to allow scrolling and copy-pasting from the hex widget to it
* For write string, length and string, zero-terminated string, wide string, base64 and hex:
  - When a range is selected, show indicator of the amount of bytes that the string will fill (like 9/17), make it red if string overfills that range, have a checkbox to fill the rest with zeros if string doesn't completely fill it
* Increment/decrement should default to current item size instead of always byte sized
* There's no preview for base64 encode/decode

# General
* No HTML copy support
* No undo write support
* Only copies hex representation intead of current item format

2022-08-22 15:08 UTC, karliss commented
@GustavoLCR  I guess I should have been clearer what people are supposed to look at. It would also have helped if you read  the limitations section of the issue description.  Advanced copy and paste is clearly stated as outside the scope of this PR. See also my ideas in https://github.com/rizinorg/cutter/issues/1524#issuecomment-1222460436 .


> Selecting a big range and Ctrl-c Ctrl-v is slow

How big are we talking about? Few hundred bytes, few megabytes or hundreds of megabytes?

> A keyboard shortcut to enter/exit Edit with keyboard would be nice

Maybe would be nice.  But just to be sure you are not supposed to enter/exit keyboard editing mode before each modification. The way I was expecting during some session you don't turn it on at all (depending on what you do). In sessions where you need it, you turn it on once you need  it work for 10 minutes and maybe then turn it off. You don't need to turn it on/off for each number you are editing.

> Dialogs

This is almost completely unrelated to changes in this PR.  "Edit/Write" actions have been there for a long time, this PR didn't add them. Only connection is that both of them are related to hexdump widget.

> No undo write support
Does rizin has anything like that? I don't think it should be done at Cutter level. If there was something like that I would expect it work consistently no mater how the memory modification was done. And there are many different ways to modify memory for example "invert jump command". Maybe even single undo history with non memory based modifcations like undoing erasure/renaming of flags and other analysis structures.

2022-08-22 15:24 UTC, karliss commented
> When item size >= 2, selecting bytes via the ascii column, the reflection of the selection on the item view seems to under/overshoot, and sometimes the box will be in the middle of a character

Writing hasn't changed this in any way it's the same how it has been when there was only reading.  When the selection isn't word aligned it's only rough approximation. For most cases there there is no meaningful selection especially for decimal output because digits in >2byte numbers don't map one to one with bytes. Even for hex output mode depending on endianness   you don't get a consecutive range.  One idea I head to make it clearer that selection in word side is currently approximate is to draw the starting and lines with jagged edge. It could also be possible to do something with shaded coloring but that's messier and hard to do it robustly without breaking in some color schemes. 

See also the second point in the "Limitations" section and note about extending "hexpairs" to 4 and 8 bytes if you want 4 byte grouping while maintaining selection at byte level.

2022-08-22 17:00 UTC, karliss commented
Here is an example of jagged edges to better communicate when byte selection within text can't be precisely displayed in number area.

![image](https://user-images.githubusercontent.com/7101031/185976203-6424aba5-fb36-4e2d-a434-2c2b811c3178.png)
![image](https://user-images.githubusercontent.com/7101031/185976490-15388016-b57f-470d-91b0-08a826479400.png)
![image](https://user-images.githubusercontent.com/7101031/185976878-c8e522b4-a3b6-4356-bde3-5bd5a91569b7.png)

2022-08-23 01:26 UTC, XVilka commented
I opened a local copy of /bin/ls on MacOS in the write mode in Cutter with analysis disabled, switched to the Hexdump widget, then, coming from the Rizin experience, pressed `i` expecting the insert mode enabled but nothing happened. Moreover, it would be nice to have `hjkl` navigation available (even if with "vi" option somewhere in preferences), similar to Rizin.
It also prints this message in the console upon pressing `i` - not sure if it's a bug:
```
2022-08-23 09:25:29.854 cutter[30214:1429347] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
```

2022-08-23 07:59 UTC, karliss commented
Didn't observe it on my mac. 
> TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

Search results have few hits with software using various UI toolkits and languages (python+tkinter, java, rust+??) with almost no useful information.  Anyway it seems to be some kind of message from macOS keyboard handling lib. Some of links also suggested that triggering it (at least in some cases) might be related to having some non english keyboard layouts.

2022-08-23 08:00 UTC, karliss commented
BUG: after starting selection and then reducing it to empty range. Primary cursor looks good but shadow cursor disappears until you move the primary cursor.

2022-08-23 09:54 UTC, ITAYC0HEN commented
Very excited for this addition! The feature worked very well for me on the first try.
Few notes:

1. Add a keyboard shortcut to toggle `insert`\`edit` mode.
2. I think I've noticed an issue with the sync of the text and hex views while deleting a nibble and a byte.
The following gif (keyboard presses are shown) present multiple issues:
  a. when deleting a nibble, I expect the textual representation of the byte to be reflected in the text view. For example, 0x4b ('K') should become '@' when deleting the  `b` nibble with `0`. In fact, it stays 'K' until further interactions (see next points).
  b. When deleting a byte (e.g 0x4b), I expect it to be reflected in the text view as a '.' (nullbyte). It only becomes '.' when performing other interactions, e.g pressing <kbd>Del</kbd> for the third time (which deletes the next nibble), or selecting with the mouse
  
![DEMOֹHEXEDITֹKEYS](https://user-images.githubusercontent.com/20182642/186127273-bc5ebdb1-e7d1-42d4-a5dc-5d6598db121e.gif)

3.  Quoting xvilka; 
> pressed i expecting the insert mode enabled but nothing happened. Moreover, it would be nice to have hjkl navigation available
I am not in favor of a single key shortcut (e.g <kbd>i</kbd>) because it can confuse someone that will type something that begins with 'i'. For example, if I'd like to write 'itay' I'll most likely type 'tay'. I suggest a keyboard shortcut with a modifier.
Regarding, hjkl, same concept, I don't think it is required for Cutter users.

2022-08-23 12:08 UTC, karliss commented
I don't like calling it "insert" edit mode since when compared to text editors it behaves opposite of insert mode, it doesn't insert characters it overwrites them. "Edit with keyboard" isn't really much better name. Any other ideas how to call it. Maybe switching the direction and calling it "read only" mode when you can't edit. Although then there is a  potential confusion with readonly/cache/write state of whole file.

2022-08-23 12:26 UTC, karliss commented
>  think I've noticed an issue with the sync of the text and hex views while deleting a nibble 

Not really a bug. It's somewhat functioning as "intended", it makes more sense for multiword decimal and floating number where you have to finish editing a word by pressing enter (or moving cursor with the mouse to different word). But  In understand how one is more likely to expect nibble change to apply instantly. I was thinking that I should probably flush current word after each nibble modification, but somehow ended up not doing it then. Will fix it now.

Somewhat off topic, but rizin (at least the system version I currently have) has a quirk where if you write first nibble, move the cursor and then write the second nibble it will write the whole byte in second position.

2022-08-23 15:33 UTC, XVilka commented
> I don't like calling it "insert" edit mode 

"replace" mode then.

2022-08-23 16:44 UTC, ITAYC0HEN commented
> I don't like calling it "insert" edit mode

I don't have a position regarding naming. I edited my comment (lack of space made it look weird). I just used " `insert` \ `edit` mode" as a reference to the feature, not as its suggested name

2022-09-06 03:01 UTC, ITAYC0HEN approved these changes

2022-09-06 15:46 UTC, merged

2022-09-06 15:49 UTC, karliss commented
For now merged the current state of PR so that it doesn't get into state where it becomes unmergable.  Rest of the things can be further improved in separate PRs.