Use git branch and revision in version string
rizinorg/cutter pull request #3109
Opened 2023-02-07 03:46 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Show git branch name and short revision (hash) when available

**Test plan (required)**

<img width="932" alt="Screenshot 2023-02-07 at 11 43 46" src="https://user-images.githubusercontent.com/203261/217143240-ef80799e-53ab-4f0a-b477-9a28e45ad0aa.png">

**Closing issues**

Closes https://github.com/rizinorg/cutter/issues/3089

2023-02-07 04:34 UTC, wargio commented
i'm ok with this, but let check the others.
@thestr4ng3r @kazarmy @ITAYC0HEN

2023-02-07 11:01 UTC, kazarmy commented on CMakeLists.txt
> +    string(SUBSTRING "${GIT_REV}" 1 7 GIT_REV)
Why is it `1 7` and not `0 7`?

2023-02-07 12:30 UTC, XVilka commented on CMakeLists.txt
> +    string(SUBSTRING "${GIT_REV}" 1 7 GIT_REV)
@kazarmy because the first character is `'`, if use 0 7 it would have been `'2dc362` instead

2023-02-07 12:37 UTC, kazarmy commented on CMakeLists.txt
> +    string(SUBSTRING "${GIT_REV}" 1 7 GIT_REV)
Oh my version of `git log` doesn't show this `'` so could be an issue but anyway the output is easy to check

2023-02-07 12:42 UTC, kazarmy requested changes
The indentation's a bit off. Other than that, lgtm.

2023-02-07 12:43 UTC, kazarmy commented on CMakeLists.txt
> +	set(CUTTER_VERSION_FULL "${CUTTER_VERSION}-${GIT_BRANCH}-${GIT_REV}")
```suggestion
    set(CUTTER_VERSION_FULL "${CUTTER_VERSION}")
else()
    execute_process(
        COMMAND git rev-parse --abbrev-ref HEAD
        OUTPUT_VARIABLE GIT_BRANCH)
    string(STRIP "${GIT_REV}" GIT_REV)
    string(SUBSTRING "${GIT_REV}" 0 7 GIT_REV)
    string(STRIP "${GIT_BRANCH}" GIT_BRANCH)
    set(CUTTER_VERSION_FULL "${CUTTER_VERSION}-${GIT_BRANCH}-${GIT_REV}")
```

2023-02-07 12:44 UTC, kazarmy requested changes
The indentation's a bit off. Other than that, lgtm.

2023-02-07 13:13 UTC, kazarmy approved these changes

2023-02-07 15:00 UTC, wargio approved these changes

2023-02-07 17:04 UTC, merged

2023-02-08 11:34 UTC, kazarmy commented
Just realized that `GIT_BRANCH` and `GIT_REV` don't update on _every_ build ala `gittip` in Rizin, but then we don't encourage users to run Cutter from git.