Get rid of stale jump arrows in disassembly widget.
rizinorg/cutter pull request #3175
Opened 2023-05-08 08:25 UTC by beauby

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This commit forces the jump arrows to be recomputed upon `paintEvent`, thus avoiding to draw stale arrows (e.g. after a jump instruction was edited).

**Test plan (required)**

Cf. #3114

**Closing issues**

closes #3114

2023-05-08 08:36 UTC, beauby commented
Might also close #2854

2023-05-08 13:21 UTC, karliss commented
If I remember correctly. Not clearing the list was intentional to better support following cases:

* You look at the start of arrow and select the corresponding assembly line. Arrow gets hilighted. You start scrolling down to see the other end. The hilighted line will remain visible as long as intersects current view even when both ends are visible. 

* Keeping the arrows visible while they are still in screen also has the benefit of minimizing the arrow reordering which makes it easier to visually keep track of what goes where. It's hard to track arrows if their order keeps changing. 


A better solution while keeping the two cases above would be to only wipe the arrows after actions that might modify the assembly. Doesn't have to be exact. It's fine if there are some false positives and it removes lines after modification which didn't change the jumps, for example replacing some mov with nop. But scrolling up and down shouldn't remove them, beside the existing code which removes arrows that go outside the screen.

2023-05-09 14:24 UTC, beauby commented
@karliss Thanks for the context. I updated the PR to only clear the arrow starting at that offset when an instruction is edited.

2023-05-10 03:35 UTC, XVilka approved these changes

2023-05-11 07:32 UTC, karliss requested changes

2023-05-11 07:32 UTC, karliss commented on src/widgets/DisassemblyWidget.cpp
> +    std::remove_if(std::begin(arrows), std::end(arrows),
That's not how `std::remove_if` should be used. `std::remove` group of functions are made to work with any iterator it doesn't actually know anything about std::vector or other container so they can't actually remove the elements. It only reorders them and returns an iterator pointing to the start of range that you need to remove using `std::vector` API.

https://en.cppreference.com/w/cpp/algorithm/remove see the docs for more information.

2023-05-11 10:05 UTC, beauby commented on src/widgets/DisassemblyWidget.cpp
> +    std::remove_if(std::begin(arrows), std::end(arrows),
Thanks, this is now fixed.

2023-05-13 05:36 UTC, wargio approved these changes
I have tested the patch. it works correctly (at least on linux)

2023-05-14 04:59 UTC, merged