Keep scroll history in decompiler widget.
rizinorg/cutter pull request #3177
Opened 2023-05-10 14:06 UTC by beauby

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This commit adds a `scrollHistory` on top of the rizin-managed
history, that keeps track of the scroll position within decompiled
functions. It basically does for the decompiler widget what #3171 
does for the disassembly widget.

**Test plan (required)**

1. Navigate through various functions in the decompiler widget.
2. Go back in history.
3. Notice that the scroll position is conserved.

**Closing issues**

2023-05-11 02:10 UTC, beauby commented
Rebased.

2023-05-12 02:40 UTC, XVilka approved these changes

2023-05-12 03:56 UTC, XVilka commented
Please address https://github.com/rizinorg/cutter/issues/3181 first

2023-05-12 13:42 UTC, XVilka commented
Rebase please

2023-05-12 14:21 UTC, beauby commented
Rebased.

2023-05-12 14:45 UTC, XVilka requested changes
It doesn't build:
```
[ 46%] Building CXX object src/CMakeFiles/Cutter.dir/widgets/GraphView.cpp.o
[ 46%] Building CXX object src/CMakeFiles/Cutter.dir/dialogs/preferences/PreferencesDialog.cpp.o
/Users/runner/work/cutter/cutter/src/widgets/DecompilerWidget.cpp:421:13: error: use of undeclared identifier 'scrollHistorySize'
        if (scrollHistorySize() > historyPos + 1) {
            ^
1 error generated.
make[2]: *** [src/CMakeFiles/Cutter.dir/widgets/DecompilerWidget.cpp.o] Error 1
```

2023-05-12 17:04 UTC, XVilka approved these changes

2023-05-12 21:57 UTC, merged