Add Tools > BaseFind
rizinorg/cutter pull request #3198
Opened 2023-06-23 10:31 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Adds Basefind to cutter (requires https://github.com/rizinorg/rizin/pull/3598).

![image](https://github.com/rizinorg/cutter/assets/561184/9a40251f-3f4c-4700-98a2-0f8556602dd6)

![image](https://github.com/rizinorg/cutter/assets/561184/e81cedf7-4806-42b6-a94d-c0d4275dbbde)

![image](https://github.com/rizinorg/cutter/assets/561184/b4097df3-4cd5-44bb-b3e9-577fba316068)

2023-06-23 12:13 UTC, XVilka requested changes
The feature itself works, but when I choose "Set base address at ..." the functions window and disassembly didn't update, it seems. Even Dashboard didn't update:

<img width="1512" alt="Screenshot 2023-06-23 at 20 12 21" src="https://github.com/rizinorg/cutter/assets/203261/16867fa2-2d97-4388-87a6-644346321a89">

Opened `rizin-testbins/firmware/stm32f103-dapboot-v1.20-bluepill.bin`

2023-06-23 12:13 UTC, XVilka commented on src/core/Basefind.cpp
> +#include "Basefind.h"
Copyright?

2023-06-23 12:13 UTC, XVilka commented on src/core/Cutter.cpp
> +    return rz_core_bin_rebase(core, base_address);
Does it work now?

2023-06-23 12:13 UTC, XVilka commented on src/core/MainWindow.cpp
> +            dialog.selectedNameFilter() != instructionsInComments
Why this change?

2023-06-23 12:13 UTC, XVilka commented on src/tools/basefind/BaseFindDialog.h
> +class BaseFindDialog;
broken indentation?

2023-06-23 12:29 UTC, wargio commented on src/core/MainWindow.cpp
> +            dialog.selectedNameFilter() != instructionsInComments
that is clang format. let me revert it.

2023-06-23 12:30 UTC, wargio commented on src/tools/basefind/BaseFindDialog.h
> +class BaseFindDialog;
i always run clang format before compiling, so it is "well formatted"

2023-06-23 12:31 UTC, wargio commented on src/core/MainWindow.cpp
> +            dialog.selectedNameFilter() != instructionsInComments
looks like correct for clang-format.

2023-06-23 12:31 UTC, wargio commented on src/core/Cutter.cpp
> +    return rz_core_bin_rebase(core, base_address);
the other scenario is to open to a new window.

2023-06-23 12:32 UTC, wargio commented on src/core/Basefind.cpp
> +#include "Basefind.h"
the other files doesn't have it.

2023-06-23 16:28 UTC, XVilka approved these changes

2023-06-23 17:40 UTC, ITAYC0HEN commented
nice! Update the docs where appropriate:
For example: https://github.com/rizinorg/cutter/blob/dev/docs/source/user-docs/command-line.rst

2023-06-23 17:41 UTC, ITAYC0HEN requested changes

2023-06-23 17:41 UTC, ITAYC0HEN commented on src/CutterApplication.cpp
> +    QCommandLineOption archOption({ "a", "arch" }, QObject::tr("Sets a specific arch name"),
```suggestion
    QCommandLineOption archOption({ "a", "arch" }, QObject::tr("Sets a specific architecture name"),
```

2023-06-23 17:41 UTC, ITAYC0HEN commented on src/CutterApplication.cpp
> +    QCommandLineOption bitsOption({ "b", "bits" }, QObject::tr("Sets a specific arch bits"),
```suggestion
    QCommandLineOption bitsOption({ "b", "bits" }, QObject::tr("Sets a specific architecture bits"),
```

2023-06-23 17:41 UTC, ITAYC0HEN commented on src/CutterApplication.cpp
> +    QCommandLineOption cpuOption({ "c", "cpu" }, QObject::tr("Sets a specific cpu"),
```suggestion
    QCommandLineOption cpuOption({ "c", "cpu" }, QObject::tr("Sets a specific CPU"),
```

2023-06-23 17:41 UTC, ITAYC0HEN commented on src/CutterApplication.cpp
> +    QCommandLineOption osOption({ "o", "os" }, QObject::tr("Sets a specific os"),
```suggestion
    QCommandLineOption osOption({ "o", "os" }, QObject::tr("Sets a specific operating system"),
```

2023-06-23 17:43 UTC, ITAYC0HEN requested changes

2023-06-23 17:43 UTC, ITAYC0HEN commented on src/tools/basefind/BaseFindDialog.ui
> +        <string>Pointer Size</string>
```suggestion
        <string>Pointer Size:</string>
```

2023-06-23 17:43 UTC, ITAYC0HEN commented on src/tools/basefind/BaseFindDialog.ui
> +        <string>Start Address</string>
```suggestion
        <string>Start Address:</string>
```

2023-06-23 17:44 UTC, ITAYC0HEN commented
Is "reopening" cutter a mandatory for the changes to take place? Is there currently no way to force the rebasing without re-opening?

2023-06-24 14:34 UTC, wargio commented
> Is "reopening" cutter a mandatory for the changes to take place? Is there currently no way to force the rebasing without re-opening?

unfortunately for now yes.

2023-06-25 02:53 UTC, XVilka commented
> The feature itself works, but when I choose "Set base address at ..." the functions window and disassembly didn't update, it seems. Even Dashboard didn't update:
> 
> <img alt="Screenshot 2023-06-23 at 20 12 21" width="1512" src="https://user-images.githubusercontent.com/203261/248264259-16867fa2-2d97-4388-87a6-644346321a89.png">
> Opened `rizin-testbins/firmware/stm32f103-dapboot-v1.20-bluepill.bin`

If I use "Reopen Cutter with with map address at 0x8000000" menu option (same file), it's even worse:

<img width="1512" alt="Screenshot 2023-06-25 at 10 52 40" src="https://github.com/rizinorg/cutter/assets/203261/30f374da-e65c-4dd3-95e0-f31fac2df864">

<img width="1512" alt="Screenshot 2023-06-25 at 10 53 17" src="https://github.com/rizinorg/cutter/assets/203261/c268b015-f205-4cfa-a919-88a0bde8948c">

2023-06-25 02:57 UTC, XVilka approved these changes

2023-06-25 03:42 UTC, merged