Show disassembly var tooltips
rizinorg/cutter pull request #3206
Opened 2023-07-16 15:43 UTC by frmdstryr

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This adds tooltips when hovering over a register or variable to the disassembly and disassembly graph views as requested in https://github.com/rizinorg/cutter/issues/2532

**Test plan (required)**

Enable the setting "Show known variable values when hovering" in the preferences. Start a debug or emulation session and hover over various registers / variables and check the tooltip.

**Closing issues**

Does not implement everything in https://github.com/rizinorg/cutter/issues/2532 but it is a start. 

Any feedback/suggestions on improving the tooltips is welcome. Thank you!

2023-07-16 16:11 UTC, XVilka requested changes

2023-07-16 16:11 UTC, XVilka commented on src/common/DisassemblyPreview.cpp
> +                    auto msg = Core()->cmdRawAt(QString("afvd %1").arg(var.name), offset);
Please don't use commands. We removed them in the favor of the API:  https://github.com/rizinorg/cutter/issues/2666

2023-07-16 16:11 UTC, XVilka commented on src/common/DisassemblyPreview.cpp
> +                auto value = Core()->cmdRawAt(QString("px %1 @ 0x%2").arg(size, addr), offset);
Same

2023-07-16 16:11 UTC, XVilka commented on src/common/Configuration.cpp
> +                                                     { "asm.varTooltips", false },
These are configuration variables that exist also in Rizin, it should be controlled differently

2023-07-19 19:05 UTC, frmdstryr commented on src/common/DisassemblyPreview.cpp
> +                    auto msg = Core()->cmdRawAt(QString("afvd %1").arg(var.name), offset);
It looks like `rz_core_analysis_var_display` is in the private api or is there another way to get the value?

2023-07-20 02:14 UTC, wargio commented on src/common/DisassemblyPreview.cpp
> +                    auto msg = Core()->cmdRawAt(QString("afvd %1").arg(var.name), offset);
just do this:
```c
RzStrBuf *sb = rz_strbuf_new(NULL);
RzAnalysisFunction *fcn = analysis_get_function_in(core->analysis, offset);
if (!fcn) {
	return rz_strbuf_drain(sb);
}
void **it;
rz_pvector_foreach (&fcn->vars, it) {
	RzAnalysisVar *p = *it;
	char *r = rz_core_analysis_var_display(core, p, add_name);
	rz_strbuf_append(sb, r);
	free(r);
}
return rz_strbuf_drain(sb);
```

2023-07-20 02:23 UTC, XVilka commented on src/common/DisassemblyPreview.cpp
> +                    auto msg = Core()->cmdRawAt(QString("afvd %1").arg(var.name), offset);
You can send a PR to Rizin changing the visibility and update the Rizin submodule. Probably also makes sense to rename it from `_display()` to `_as_string()`

2023-07-20 03:20 UTC, wargio commented on src/common/DisassemblyPreview.cpp
> +                    auto msg = Core()->cmdRawAt(QString("afvd %1").arg(var.name), offset);
i agree.

2023-07-21 13:48 UTC, frmdstryr commented
It seems to work fine for registers but stack variables do not seem to be correct. 

![Screenshot_20230721_084938](https://github.com/rizinorg/cutter/assets/380158/24495e76-0d89-4454-8861-a6a82bb91508)

The `rz_analysis_var_addr` used inside `rz_core_analysis_var_display` does not return the proper address. After a little more digging `rz_reg_getv` is returning 0 for rbp insead of the actual value, since the stackoff is negative it overflows to a garbage address. 

Any ideas as to what is going on? Edit: This is when debugging.

2023-07-21 16:51 UTC, frmdstryr commented
Potentially fixed by https://github.com/frmdstryr/rizin/tree/make-rz_core_analysis_var_display-work-when-debugging

2023-07-22 09:02 UTC, wargio commented
please update also the rizin submodule

2023-07-29 04:38 UTC, XVilka commented
@frmdstryr please update Rizin, and make it green

2023-07-30 03:39 UTC, wargio approved these changes

2023-07-30 08:37 UTC, XVilka approved these changes

2023-07-30 08:37 UTC, merged

2023-07-30 08:38 UTC, XVilka commented
@frmdstryr thank you!