DisAsm: double-click and tripple-click should select text at cursor.
rizinorg/cutter pull request #3252
Opened 2023-10-20 14:53 UTC by Kaldesyvon

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

I have implemented new feature for disassembly view. You can now double click to select word and triple click to select whole line, like most editor have this feature nowadays. It is now easier to select text and copy it. This does not eliminate feature to jump to address. You can do it by holding down Ctrl key and double click on address.

**Test plan (required)**

To test it just open disassembly view and double click or triple click on line. You can copy text with Ctrl + C. Also test double click on address or name of function that `call` instruction calls. You are able to select it now. Hold down Ctrl and double click on address or function name and you will be redirected to that address.

**Closing issues**

closes=#3097

2023-10-27 13:06 UTC, ITAYC0HEN commented
Hey @Kaldesyvon and welcome to Cutter :) Thank you for this contribution!
Personally, I am not in favor of double-clicking to select a word, as it changes the standard of double-clicking to jump to an address. What I suggest, which might already be implemented, is to take advantage of the fact that a single left click highlights a token, and implement an additional feature - that ctrl+c will copy this selected token\word.
This is common behavior in different RE software.

What do others think?

2023-10-27 15:25 UTC, ret2libc commented
> Hey @Kaldesyvon and welcome to Cutter :) Thank you for this contribution! Personally, I am not in favor of double-clicking to select a word, as it changes the standard of double-clicking to jump to an address. What I suggest, which might already be implemented, is to take advantage of the fact that a single left click highlights a token, and implement an additional feature - that ctrl+c will copy this selected token\word. This is common behavior in different RE software.
> 
> What do others think?

I do agree with @ITAYC0HEN .

2023-10-31 16:30 UTC, XVilka approved these changes

2023-10-31 16:30 UTC, XVilka requested changes
Sorry, pressed the wrong button. Yes, lets go with the solution @ITAYC0HEN suggested.

2023-11-01 08:44 UTC, Kaldesyvon commented
Thank you for responses, but I have two more questions:
1. Should I still consider triple click to select line? 
2. Should I add functionality to select multiple words/tokens by holding mouse button and moving cursor to other offset?

2023-11-01 10:59 UTC, karliss commented
> 2. Should I add functionality to select multiple words/tokens by holding mouse button and moving cursor to other offset?

I would leave he default text field selection behavior as is. Not being able to select the exact range I want seems more annoying, than the minor convenience of selecting whole words when that's what I want.


There is potential room for improving the selection behavior to support mainting selection after scrolling and even selecting wider range than being displayed. But that's a lot more complicated task that should be done in a separate issue.

2026-09-03 19:33 UTC, wargio commented
i'm closing this as the PR is too old and has too many conflicts

2026-09-03 19:33 UTC, closed without merging