Optimize inserts using reserve() and micro optimizations
rizinorg/cutter pull request #3257
Opened 2023-10-31 16:54 UTC by GermanAizek

**Detailed description**
@XVilka this will also be needed since project focus on speedup big binary file analysis, later I will look for more similar places where I can apply similar methods speed exec optimization.

2023-10-31 20:21 UTC, karliss requested changes

2023-10-31 20:21 UTC, karliss commented on src/widgets/HeapBinsGraphView.cpp
> -        GraphLayout::GraphBlock gbChunk;
Unless you have profiling results proving that this is performance critical to reuse this block, I recommend keeping the declaration where it was. Reusing it without clearly reinitializing everything has risk of getting some old values from previous iterations, if not now, then as rest of code changes. `std::move` at the end isn't reliable way for ensuring the state of reused block afterwards.

2023-10-31 20:21 UTC, karliss commented on src/widgets/HeapBinsGraphView.cpp
> -        GraphLayout::GraphBlock gbChunk;
Same ideas as previous comment about block reuse.

2023-10-31 20:21 UTC, karliss commented on src/widgets/HeapBinsGraphView.cpp
> +    gbChunk.edges.reserve(chunks.size() * 2);
Now this is a pesimization not an optimization. No block will have that many edges.  

And since you are both reusing the block and later moving it away, the reserving here is  at best useless, and in the worst case if move doesn't succeed you will have overall reserved O(n^2) memory for a list.

Knowing that there are always two edges might as well do something like
```
gbChunk.edges = { 
    GraphEdge(chunks[i].fd), 
    GraphEdge(chunks[i].bk) 
};
```

2023-10-31 20:21 UTC, karliss commented on src/widgets/DisassemblerGraphView.cpp
> +        db.instrs.reserve(vecVisitor.end() - iter);
Since iter is begin, wouldn't it be clearer to query the vector  size directly?  The first idea I get `end - iter` that there is something more complicated going on, when what you actually need is vector size.

2023-10-31 20:31 UTC, karliss commented
If you actually want to improve the performance of big binary file analysis please do some profiling first. Blindly applying microptimizations in places that are not part of bottleneck, just makes the code harder to maintain with low chance giving perceivable improvement. I would guess that most of these changes are not anywhere near being the bottleneck. Feel free to prove me wrong with actual numbers.

Since you already made the changes, assuming you fix the things I asked, I won't reject this. But that is not good approach for making meaningful optimization.

2023-11-01 09:29 UTC, GermanAizek commented
> If you actually want to improve the performance of big binary file analysis please do some profiling first. Blindly applying microptimizations in places that are not part of bottleneck, just makes the code harder to maintain with low chance giving perceivable improvement. I would guess that most of these changes are not anywhere near being the bottleneck. Feel free to prove me wrong with actual numbers.
> 
> Since you already made the changes, assuming you fix the things I asked, I won't reject this. But that is not good approach for making meaningful optimization.

Hello, your project is a really good replacement IDA Pro, and I am ready sacrifice time for profiling and showing more detailed information with benchmarks tests for each use reserve() function, a week is enough for me.

2023-11-01 11:51 UTC, XVilka commented
@GermanAizek as Cutter uses [Rizin](https://rizin.re) as the backend, high chances that most of the performance bottlenecks would come from it. If you really want to help to speed up the project, I recommend checking the "optimization" label in the corresponding repository: https://github.com/rizinorg/rizin/labels/optimization

Moreover, if you have a concrete cases in mind, profiling Rizin on them would provide better, more narrow window into the places what could be improved, in file format parsing or various analysis steps.

2023-11-01 13:35 UTC, GermanAizek commented
@XVilka As soon as I'm done with this PR, I'll look at label in rizin.

2023-11-03 09:09 UTC, GermanAizek commented on src/widgets/HeapBinsGraphView.cpp
> -        GraphLayout::GraphBlock gbChunk;
@karliss, will this code fix this situation?
```cpp
    // add the blocks for the chunks
    GraphLayout::GraphBlock gbChunk;
    gbChunk.edges.reserve(chunks.size() * 2);
    for (int i = 0; i < chunks.size(); i++) {
        gbChunk.entry = chunks[i].addr;
        gbChunk.edges.emplace_back(chunks[i].fd);
        gbChunk.edges.emplace_back(chunks[i].bk);

        // if last chunk and there is message then show it in the chunk
        if (i == chunks.size() - 1 && heapBin->message) {
            chunks[i].content += "\n" + QString(heapBin->message);
        }

        addBlock(gbChunk, chunks[i].content, chunks[i].addr);
        memset(&gbChunk, 0, sizeof(gbChunk));
    }
```

2023-11-03 09:09 UTC, GermanAizek commented on src/widgets/HeapBinsGraphView.cpp
> -        GraphLayout::GraphBlock gbChunk;
@karliss, same question as above.

2023-11-03 09:13 UTC, GermanAizek commented on src/widgets/DisassemblerGraphView.cpp
> +        db.instrs.reserve(vecVisitor.end() - iter);
yes, you're absolutely right, for some reason I tried find size through iterators.

2023-11-11 12:50 UTC, closed without merging