Additionals translate strings
rizinorg/cutter pull request #3289
Opened 2024-01-29 15:08 UTC by XVilka

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Imported from https://github.com/rizinorg/cutter/issues/3187#issuecomment-1914876984

**Test plan (required)**

CI is green

**Closing issues**

Partially addresses https://github.com/rizinorg/cutter/issues/3187

2024-01-29 18:59 UTC, karliss requested changes

2024-01-29 18:59 UTC, karliss commented on src/dialogs/preferences/AnalysisOptionsWidget.cpp
> +    { "io.maps.x", QObject::tr("All executable maps") },
Need to verify it, but I have a feeling that this isn't going to work properly. It's not going to change after changing language. And even if you perform a restart after language change, the language initialization isn't necesarily going to happen before the initialization of static constants like this.

If I remember correctly qt had a TR() macro which marked string for translation so that translation software finds it while scanning source files. And afterwards you call the real translate in the place that updates UI values from this variable.

2025-04-28 17:27 UTC, notxvilka commented
@karliss do you want to import some of these changes?

2025-04-28 17:39 UTC, karliss commented
Yeah, was planning to work on a couple of translation related issues now after the release #3187  included.  Will go through this again and either get it refreshed or pick some of them depending on whats cleaner.

2025-04-29 05:36 UTC, karliss commented
Too much stuff completely wrong.

2025-04-29 05:36 UTC, closed without merging