Update GitHub Action versions
rizinorg/cutter pull request #3296
Opened 2024-02-15 06:22 UTC by XVilka

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Test plan (required)**

CI is green

2024-02-15 06:32 UTC, XVilka commented
Blocked by the use of Ubuntu 18.04 which can't run Node 20: `/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)`

2024-07-08 20:29 UTC, karliss commented
I have a working solution in the qt6 update branch. If I don't get it to the state where it's ready for review by the end of week. I will consider splitting it up, so that more urgent parts of it can be merged first.

2024-08-10 21:57 UTC, karliss requested changes
Two more actions need to be upated. Probably the ones which got introduced during QT6 changes. You can see them if you open summary for CI status.
![image](https://github.com/user-attachments/assets/a22da6c0-ac3d-4238-8a5d-e614d2928a1f)

2024-08-11 11:43 UTC, karliss approved these changes

2024-08-11 13:44 UTC, merged