WIP Added option to add new flags from hexdump #2932
rizinorg/cutter pull request #3297
Opened 2024-02-16 00:19 UTC by Rohan-Sagar

**Your checklist for this pull request**
- [ X ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ X ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ X ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

- Problem:
    - Currently, users can add new flags from the disassembly widget using the right-click menu and a keyboard shortcut. However, this functionality is missing in the hexdump widget.
- Proposed solution:
    - To address this issue, we propose the following solution:
        - Add Action for Adding New Flag:
            - Introduce a new action in the right-click menu of the hexdump widget for adding a new flag. This action will provide users with a convenient option to add flags directly from the hexdump view.
        - Synchronize with Disassembly Widget:
            - Ensure that the keyboard shortcut for adding flags from the hexdump widget is synchronized with the shortcut used in the disassembly widget. This consistency will enhance the user experience and streamline flag management across different views.
        - Implementation Details:
            - Add a QAction object (actionFlag) within the HexWidget class to represent the action for adding a new flag.
            - Add a QAction object (actionDeleteFlag) within the HexWidget class to represent the action for deleting a flag.
            - Implement the onActionAddFlagTriggered() slot to handle user-triggered events for adding flags within the HexWidget class.
            - Implement the onActionDeleteFlagTriggered() slot to handle user-triggered events for deleting flags within the HexWidget class.
            - Update the context menu event handling (contextMenuEvent()) in the HexWidget class to include the new action for adding flags.
            - Introduce the parentForDialog() function in the HexWidget class to provide the parent widget for dialogs spawned within the hexdump view.

**Test plan (required)**

Functionality Test:
- Open the application and navigate to the hexdump view.
- Right-click in the hexdump widget to bring up the context menu.
- Select the option to add a new flag. Verify that a dialog box or input field appears with the correct address, allowing you to enter a flag name and size.
- Enter a valid flag name and size, then confirm the action.
- Verify that the new flag is correctly added to the list of flags and is visible in the hexdump widget or disassembly widget.

Keyboard Shortcut Synchronization Test:
- While in the hexdump view, use the keyboard shortcut (key bind N) for adding a new flag (ensure this is the same shortcut used in the disassembly widget).
- Confirm that the action for adding a new flag is triggered, similar to the right-click context menu action.
- Follow the same steps as in the functionality test to add a flag and verify its addition.

Cross-Widget Synchronization Test:

- After adding a new flag in the hexdump widget, switch to the disassembly view.
- Verify that the newly added flag is also reflected in the disassembly widget and any other relevant parts of the application where flags are displayed.

![Screenshot 2024-02-15 at 7 02 39 PM](https://github.com/rizinorg/cutter/assets/90643076/e2ea623b-57c9-4929-bcce-ec374c560625)
![Screenshot 2024-02-15 at 7 03 07 PM](https://github.com/rizinorg/cutter/assets/90643076/ca3aeeb1-c7da-48aa-a6e9-46ca9933fa9f)
![Screenshot 2024-02-15 at 7 03 26 PM](https://github.com/rizinorg/cutter/assets/90643076/5d3afbda-89ce-44a4-932a-b189ebc573fd)
![Screenshot 2024-02-15 at 7 03 40 PM](https://github.com/rizinorg/cutter/assets/90643076/79706cfd-26e9-407c-aa9b-d7278ff67131)
![Screenshot 2024-02-15 at 7 03 53 PM](https://github.com/rizinorg/cutter/assets/90643076/d7e29740-3c89-44ce-bc77-908f0efd5fc2)
![Screenshot 2024-02-15 at 7 04 11 PM](https://github.com/rizinorg/cutter/assets/90643076/22fa6817-35e4-487b-b6fb-9dcaaffc5890)

**Closing issues**

2024-02-16 08:03 UTC, karliss commented
So is this ready for review or is it still WIP (work in progress)? Note if the PR is still work in progress, but you just wanted to give a heads up early,  and there are things you want to change before review, you can use the Github draft feature.

2024-02-16 13:53 UTC, Rohan-Sagar commented
> So is this ready for review or is it still WIP (work in progress)? Note if the PR is still work in progress, but you just wanted to give a heads up early, and there are things you want to change before review, you can use the Github draft feature.

Thank you for the notice. I've marked the pull request as a draft to indicate that it's ready for review, but there may still be some changes. Once all adjustments are made, I'll mark it as ready for review again.

2024-02-23 21:29 UTC, karliss requested changes

2024-02-23 21:29 UTC, karliss commented on .vscode/settings.json
> +    "cmake.sourceDirectory": "${workspaceFolder}",
Please do not commit changes unrelated to the problem you are working on.

2024-02-23 21:29 UTC, karliss commented on src/dialogs/CommentsDialog.cpp
> -
Please remove changes from files you didn't modify.

2024-02-23 21:29 UTC, karliss commented on src/dialogs/FlagDialog.cpp
> -
Please remove changes from files you didn't modify.

2024-02-23 21:29 UTC, karliss commented on src/menus/DisassemblyContextMenu.cpp
> -
Please remove changes from files you didn't modify.

2024-02-23 21:29 UTC, karliss commented on src/widgets/HexWidget.cpp
> +QWidget *HexWidget::parentForDialog()
Is this used for anything?

2024-02-23 21:29 UTC, karliss commented on src/widgets/HexWidget.cpp
> +    QString flag = Core()->flagAt(cursor.address);
Why are you using two different functions for checking if there is a flag at this address?

2024-02-23 21:29 UTC, karliss commented on src/widgets/HexWidget.cpp
> +    RzFlagItem *flagItem = rz_flag_get_i(Core()->core()->flags, cursor.address);
Be very careful if you are holding onto objects returned and owned by rizin. `Core()->core()` returns `RzCoreLocked` you need which is some kind of lock object for interacting with rizin-core stuff.  So the intended use is something like this:

```
{
    auto coreLock = Core()->core();
    RZFlagItem *flagItem = rz_flag_get_i(coreLock->flags, cursor.address);
    //do stuff with flag 
    // coreLock needs to live at leas as long as you are still touching pointers you obtained from it directly or through rizin API, with exception being situations where Rizin API returns a fully selfcontained object owned by called of function
}
```

2024-03-19 02:15 UTC, Rohan-Sagar commented on src/widgets/HexWidget.cpp
> +    RzFlagItem *flagItem = rz_flag_get_i(Core()->core()->flags, cursor.address);
Implemented the suggested change to use a local coreLock variable for holding the RzCoreLocked object, ensuring it remains alive as long as needed and safeguarding against accessing freed memory.

Thank you for the feedback!

2024-04-24 17:50 UTC, karliss commented
@Rohan-Sagar Are you planning to finish cleaning up this PR ?

2024-05-01 21:55 UTC, Rohan-Sagar commented
@karliss I’m getting this issue in the continuous-integration check:

Dependency libzstd skipped: feature use_sys_libzstd disabled
Downloading zstd source from https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
A fallback URL could be specified using source_fallback_url key in the wrap file
..\..\..\..\rizin\meson.build:621:2: ERROR: could not get https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz is the internet available?

Any idea what could be going wrong?

2025-05-02 13:47 UTC, notxvilka commented
Solved by https://github.com/rizinorg/cutter/pull/3450

2025-05-02 13:47 UTC, closed without merging