Update Rizin to the latest dev
rizinorg/cutter pull request #3298
Opened 2024-02-19 12:17 UTC by XVilka

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Use the new API of Rizin

**Test plan (required)**

**Closing issues**

2024-02-19 15:15 UTC, wargio commented on src/core/Cutter.cpp
> +			: nullptr;
this leaks abiter

2024-02-19 15:23 UTC, XVilka commented on src/core/Cutter.cpp
> +    auto ab = reinterpret_cast<RzAnalysisBytes *>(rz_iterator_next(abiter.get()));
I just noticed my mistake here - it should be the end of the iterator. We need a new API in Rizin - `rz_iterator_last()` or something like that?

2024-02-20 03:31 UTC, wargio requested changes

2024-02-20 03:31 UTC, wargio commented on src/core/Cutter.cpp
> +    auto ab = reinterpret_cast<RzAnalysisBytes *>(rz_iterator_next(abiter.get()));
yes. we do need this.

2024-02-20 14:38 UTC, XVilka commented on src/core/Cutter.cpp
> +    auto ab = reinterpret_cast<RzAnalysisBytes *>(rz_iterator_next(abiter.get()));
Added a new API here: https://github.com/rizinorg/rizin/pull/4278

2024-02-21 14:04 UTC, imbillow approved these changes

2024-02-21 16:54 UTC, merged