Add Copy to Clipboard for VersionInfo dialog
rizinorg/cutter pull request #3318
Opened 2024-03-12 14:43 UTC by r3yc0n1c

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Adds a Copy, Close button in the VersionInfo Dialog to copy the formatted info to Clipboard.
Also adds translations support.

**Test plan (required)**

- Click on the "Version Info" button in the Dashboard.
- Click on "Copy" to copy the formatted version details
- Try pasting it somewhere
- Click on "Close" to close the dialog

**Closing issues**

Closes #3103 

**Screenshots**
![cutter_copy](https://github.com/rizinorg/cutter/assets/57730879/7e3a1856-61c3-493c-9641-8b1dec7e878c)
![cutter_copy_1](https://github.com/rizinorg/cutter/assets/57730879/71d5beac-17be-4abf-b380-2bb5c01fbdf8)
![cutter_copy_2](https://github.com/rizinorg/cutter/assets/57730879/83d496a1-5481-4152-9fac-2dd67a3c448a)

2024-03-13 00:07 UTC, wargio approved these changes

2024-03-13 08:55 UTC, karliss commented
For this window I would prefer if selection and copying was functioning normally.  No need to add a separate button, otherwise you could end up adding a copy button in every possible UI screen which will be cluttered a mess.

Allowing multiline selection should be trivial. Not sure about copying part, but that should also be solvable.

2024-03-13 12:35 UTC, wargio commented
the issue itself had a `copy all` request.

2024-03-13 15:45 UTC, r3yc0n1c commented
I get your point @karliss. This issue was a request for a `Copy All` function but we can definately go for the trivial selection in a new issue. Shall I create one?

2024-03-13 16:09 UTC, karliss commented
First of all feature request by random user shouldn't be taken as truth for what the best solution to their problem is, considering rest of program is.

And even if you consider what that issue author said for me it doesn't seem obvious that custom "copy all" button is what he asked. 

> Personally i'd prefer a less fancy rendering, but providing for select-all and copy-all, like the extra details region of the About window does

The way I interpret it "less fancy rendering" means non broken selection/multiline copy which functions just like you would expect multiline selection to work. The about window he mentioned as preferred solution doesn't even have "copy-all". It simply has regular label with selectable text. And all the context menu actions like  "Select all" and "Copy" are the default actions available to any text field with same configuration.

Also rest of the issue describes the problem as having selection behavior lacking ability to select multiple lines and copying them.

> 1. There is no context menu 
> 2. the grids pretend to select full row, but when a hotkey is used, only a single column value is copied, not the whole selection.
> 3. No multi-row selection to copy 'all of them'
> 4. No multi-column selection either

I have no idea where did you both saw that it requested "Copy all" button.

2024-03-13 17:23 UTC, karliss requested changes

2024-03-13 17:23 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +void VersionInfoDialog::on_buttonBox_rejected()
Do not use automatic named based signal connection. See the cutter development guidelines on connecting signals https://cutter.re/docs/contributing/code/development-guidelines.html#connecting-qt-signals

Same applies for on_copyVersionInfoButton_clicked . 

In this case you could have directly connected the buttonBox signal to corresponding dialog slot. 

This becomes irrelevant if you implement this issue like I suggested.

2024-03-13 17:48 UTC, karliss commented
Note enabling multiline selection isn't any complicated than what's already written in this PR. It's a matter of setting appropriate QTReeWidget::selectionMode, you can even do it in the UI file.

As for copying you can do something like this:
```
auto action = ui->rightTreeWidget->addAction("Copy", QKeySequence::Copy, this, [this]() {
    CopyWidgetSelection(leftTreeWidget);
});
action->setShortcutContext(Qt::ShortcutContext::WidgetWithChildrenShortcut);

CopyTreeWidgetSelection(QTreeWidget *treeWidget) {
    // almost the same code you already have, but for single treeWidget
    // ... 
    while (*itl) {
        if ((*itl)->isSelected()) {
            // your existing code for preparing copy content
        }
    }
    // no need to show a popup telling, that Ctrl+C isn't broken
    // ...
}
```

That way there is no need for additional header inserted in copied text to distinguish between left and right side, code for left and right side gets reused. No need for additional popup confirming that copying succeeded since Ctrl+C  (or equivalent platform specific shortcut) working everywhere is the expected normal behavior.

2024-03-13 17:53 UTC, karliss requested changes

2024-03-13 17:53 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +        QString row = (*itl)->text(keyColumnIndex) + " : " + (*itl)->text(valueColumnIndex) + "\n";
Doesn't this cause duplicate ":" the text for many keys already contain ":"?

2024-03-13 17:53 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
If you are going to make constants like this make them actual constants and share them with code filling in data. 

Replacing magic numbers with constants only works if all code interacting with single object uses the same constant definitions.

2024-03-14 02:25 UTC, wargio commented
> First of all feature request by random user shouldn't be taken as truth for what the best solution to their problem is, considering rest of program is.
> 
> And even if you consider what that issue author said for me it doesn't seem obvious that custom "copy all" button is what he asked.

That is true, my bad.

@r3yc0n1c please follow the directives that @karliss has proposed, it will vastly improve the feature!

2024-03-14 12:01 UTC, r3yc0n1c commented
Got it... I'll update this ASAP!
Thanks!

2024-03-17 11:50 UTC, r3yc0n1c commented
hi, I've been experimenting with different approaches for this implementation. Here's the recent update: https://github.com/rizinorg/cutter/compare/dev...r3yc0n1c:cutter:exp-copy-feat-versioninfo

I'm facing - only 1st item is selected/sometimes 'QAction::event: Ambiguous shortcut overload: Ctrl+C' error... could you please review this?

2024-03-17 12:21 UTC, karliss commented
A couple of potential issues all from the fact that you are creating a new action each time a context menu is opened:
* how is the action with shortcut supposed to work if you only create it when opening a context menu
* you are creating new action associated with VersionInfo Dialog each time context menu is opened. That can not only bloat memory usage, but is also probably one of reasons why you are getting warning about ambiguous shortcut. This is C++ you have to think about lifetime of objects. Qt introduces it's own mechanisms for managing this, but it doesn't change the fact that you have to think about object lifetimes

The actions should be created during initialization of window. That way the keyboard shortcuts can work before context menu is opened. Afterwards if necessary you can add the existing action to a context menu if necessary. Although in this case you could set the contextMenuPolicy to ` Qt::ActionsContextMenu`, thus avoiding code for manually filling custom context menu. One more aspect to this approach is that you would have to create a separate but similar action for each treewidget, also make sure parent of action is the treewidget not the dialog. That will avoid the need for, in my opinion hacky,   check of which tree widget has focus, it's also necessary for `Qt::ActionsContextMenu` to work. 


In general (but not this specific situation) you can create the actions for context menu in the contextMenuEvent callback, and a lot of places in Cutter do that, but there are a few things you need to take into. If you create the actions for context menu in the callback, they should be associated with the temporary menu object instead of the dialog. That way they will be destroyed together with temporary menu, instead of accumulating each time you open the context menu. 
Doing it that way is not very suitable for actions with shortcuts. This approach is more suitable for dynamic actions which don't have a shortcut and the amount of which depends on the thing you clicked.

2024-03-18 06:55 UTC, r3yc0n1c commented
Hello @karliss I've made the changes following your heads-up, and it's working fine locally. Could you please check this once - https://github.com/rizinorg/cutter/commit/219f27d75cbfb6c48a8da45e56f1192605dab0aa

Thanks!

2024-03-18 07:47 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
resolved it in the new update

2024-03-18 19:56 UTC, karliss requested changes

2024-03-18 19:56 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +}
There is no point creating an empoty menu and overriding contextMenuEvent if it's not used for anything.

2024-03-18 19:56 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    for (QTreeWidgetItem *x : t->selectedItems()) {
The example I gave you with `QTreeWidgetItemIterator` + `IsSelected` check instead of t->selectededItems was not without a reason.

For ELF files the this window contains actual tree structure. For which `t->selectededItems` produces non ideal order.  

![image](https://github.com/rizinorg/cutter/assets/7101031/6e3bc10a-6200-40f1-8dcd-428688e46bca)

```
0x000016d0 = Name: GLIBC_2.28	Flags: none	Version: 13	
0x000016e0 = Name: GLIBC_2.38	Flags: none	Version: 12	
0x000016f0 = Name: GLIBC_2.14	Flags: none	Version: 11	
0x00001700 = Name: GLIBC_2.33	Flags: none	Version: 10	
0x00001710 = Name: GLIBC_2.16	Flags: none	Version: 9	
0x00001720 = Name: GLIBC_2.4	Flags: none	Version: 8	
0x00001730 = Name: GLIBC_2.17	Flags: none	Version: 7	
0x00001740 = Name: GLIBC_2.26	Flags: none	Version: 6	
0x00001750 = Name: GLIBC_2.34	Flags: none	Version: 5	
0x00001760 = Name: GLIBC_2.3.4	Flags: none	Version: 4	
0x00001770 = Name: GLIBC_2.2.5	Flags: none	Version: 3	
0x00001780 = Name: GLIBC_2.3	Flags: none	Version: 2	
Address: = 0x000016c0
Offset: = 0x000016c0
Entries: = 
0x000016c0 = Version: 1	File: libc.so.6
```

2024-03-18 19:58 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
This is still relevant. The code which fills in the data should use the same column constants as this code.

2024-03-18 21:46 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    for (QTreeWidgetItem *x : t->selectedItems()) {
applied `QTreeWidgetItemIterator + IsSelected` as you mentioned... the item orderi is correct now.

2024-03-18 21:48 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +}
removed the redundant code, `ActionsContextMenu` will take care of everything we want

2024-03-19 19:14 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +}
You didn't remove the  menu completely, there is an unused declaration in header.

2024-03-19 19:38 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +}
my bad :sweat_smile:  , updated just now

2024-03-20 16:30 UTC, karliss commented
@r3yc0n1c In case you missed it, the comment for column constants is still opened.

2024-03-20 16:44 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
sorry, I think I missed these... we can just use the same constants (0 and 1) as in the data filling code, right?
```c
// row = (*it)->text(keyColumnIndex) + " = " + (*it)->text(valueColumnIndex) + "\n";
row = (*it)->text(0) + " = " + (*it)->text(1) + "\n";
```

2024-03-20 17:46 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
Not great but acceptable. Defining the column constants so that they can be used by the code that fills in data would be better.

2024-03-20 17:51 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
something like `#define KEYINDEX (0)` ?

2024-03-20 18:00 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
I'm thinking of using `#define KEYINDEX (0)` & `#define VALINDEX (1)` . Shall I update the data filling code too?

2024-03-20 20:30 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    int keyColumnIndex = 0, valueColumnIndex = 1;
This is not C, do not use macros for stuff like that.  If you have no idea what to do take a look at how rest of the widgets do it.

> Shall I update the data filling code too?

![image](https://github.com/rizinorg/cutter/assets/7101031/0b2865d7-63b0-43b0-a64a-aaa70163744b)
![image](https://github.com/rizinorg/cutter/assets/7101031/750f08bb-5c46-4406-ba4c-0e1aa9b21636)
![image](https://github.com/rizinorg/cutter/assets/7101031/6efd6f93-954b-4a3d-b3ad-65865f55fc84)

Was asking for it 3 times insufficiently clear?

2024-03-29 17:35 UTC, r3yc0n1c commented
Hi @karliss @XVilka , could you please review the changes?

2024-03-30 13:33 UTC, XVilka requested changes
I tested it on Windows, and it works. But once I close the Version window and open it again, the selection is still active. I think it should be dropped/reset upon window closure, so once you open it again, nothing is selected.

2024-03-31 20:39 UTC, karliss approved these changes
No more new objections from me. Would be good to fix the thing XVilka  said before merging.

2024-04-04 03:57 UTC, wargio commented on src/dialogs/VersionInfoDialog.cpp
> +*/
if they are not needed, please remove them

2024-04-04 15:36 UTC, karliss requested changes

2024-04-04 15:36 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    ui->leftTreeWidget->setCurrentIndex(model->index(-1, -1));
leftTreeWidget?

2024-04-04 16:03 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    ui->leftTreeWidget->setCurrentIndex(model->index(-1, -1));
could you explain it a bit?

2024-04-04 19:50 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +*/
not needed as of now... removed them

2024-04-04 22:18 UTC, karliss requested changes

2024-04-04 22:18 UTC, karliss commented on src/dialogs/VersionInfoDialog.cpp
> +    ui->leftTreeWidget->setCurrentIndex(model->index(-1, -1));
Is there a reason you are using `model->index(-1, -1)` instead of simply using default QModelIndex constructor?

2024-04-04 22:18 UTC, karliss commented on .gitmodules
> +	branch = dev
If you made changes and they didn't work you need to cleanup after your initial attempts afterwards.

Please remove any unnecessary changes to the rizin submodule, and just properly merge or rebase your branch on top of latest cutter dev which already has suitable rizin verison..

2024-04-05 16:30 UTC, r3yc0n1c commented on src/dialogs/VersionInfoDialog.cpp
> +    ui->leftTreeWidget->setCurrentIndex(model->index(-1, -1));
not really... made changes to use default QModelIndex now.

2024-04-05 16:34 UTC, XVilka commented on .gitmodules
> +	url = https://github.com/rizinorg/cutter-translations
Unnecessary change

2024-04-05 16:36 UTC, XVilka requested changes
I cannot test right now, but from the code perspective I don't have any objections.

2024-04-05 16:36 UTC, XVilka commented on rizin
Technically it's unnecessary too, but fine to keep if you put it in a different commit. Thus, it should be squashed into two commits:
1. Rizin update commit
2. VersionInfo commit

2024-04-21 15:51 UTC, XVilka approved these changes

2024-04-21 15:56 UTC, karliss requested changes

2024-04-21 15:56 UTC, karliss commented on .gitmodules
> +	url = https://github.com/rizinorg/cutter-translations
How is this considered resolved?

2025-04-15 17:29 UTC, notxvilka commented
@r3yc0n1c please rebase

2026-01-01 19:29 UTC, notxvilka commented
Superseded by https://github.com/rizinorg/cutter/pull/3534

2026-01-01 19:29 UTC, closed without merging