Update Rizin to the latest `dev`
rizinorg/cutter pull request #3319
Opened 2024-03-18 13:54 UTC by XVilka

Should fix the following errors: 
```
../src/core/Cutter.cpp: In member function 'RVA CutterCore::getLastFunctionInstruction(RVA)':
#9 23.42 ../src/core/Cutter.cpp:1298:68: error: cannot convert 'RzPVector*' {aka 'rz_pvector_t*'} to 'const RzList*' {aka 'const rz_list_t*'}
#9 23.42      RzAnalysisBlock *lastBB = (RzAnalysisBlock *)rz_list_last(fcn->bbs);
#9 23.42                                                                ~~~~~^~~
#9 23.42 In file included from /usr/include/librz/rz_diff.h:9,
#9 23.42                  from /usr/include/librz/rz_util.h:8,
#9 23.42                  from /usr/include/librz/rz_getopt.h:4,
#9 23.42                  from /usr/include/librz/rz_main.h:9,
#9 23.42                  from /usr/include/librz/rz_core.h:7,
#9 23.42                  from ../src/core/CutterCommon.h:8,
#9 23.42                  from ../src/common/TempConfig.h:5,
#9 23.42                  from ../src/core/Cutter.cpp:13:
#9 23.42 /usr/include/librz/rz_list.h:79:62: note:   initializing argument 1 of 'void* rz_list_last(const RzList*)'
#9 23.42  RZ_API RZ_BORROW void *rz_list_last(RZ_NONNULL const RzList *list);
#9 23.42                                                 ~~~~~~~~~~~~~~^~~~
#9 23.42 ../src/core/Cutter.cpp: In member function 'QVector<Chunk> CutterCore::getHeapChunks(RVA)':
#9 23.42 ../src/core/Cutter.cpp:1644:39: error: 'rz_list_get_head_data' was not declared in this scope
#9 23.42          m_arena = ((RzArenaListItem *)rz_list_get_head_data(arenas))->addr;
#9 23.42                                        ^~~~~~~~~~~~~~~~~~~~~
#9 23.42 ../src/core/Cutter.cpp:1644:39: note: suggested alternative: 'rz_list_delete_data'
#9 23.42          m_arena = ((RzArenaListItem *)rz_list_get_head_data(arenas))->addr;
#9 23.42                                        ^~~~~~~~~~~~~~~~~~~~~
#9 23.42                                        rz_list_delete_data
#9 23.42 ../src/core/Cutter.cpp: In member function 'QList<FunctionDescription> CutterCore::getAllFunctions()':
#9 23.42 ../src/core/Cutter.cpp:3064:45: error: cannot convert 'RzPVector*' {aka 'rz_pvector_t*'} to 'const RzList*' {aka 'const rz_list_t*'}
#9 23.42          function.nbbs = rz_list_length(fcn->bbs);
#9 23.42                                         ~~~~~^~~
#9 23.42 In file included from /usr/include/librz/rz_diff.h:9,
#9 23.42                  from /usr/include/librz/rz_util.h:8,
#9 23.42                  from /usr/include/librz/rz_getopt.h:4,
#9 23.42                  from /usr/include/librz/rz_main.h:9,
#9 23.42                  from /usr/include/librz/rz_core.h:7,
#9 23.42                  from ../src/core/CutterCommon.h:8,
#9 23.42                  from ../src/common/TempConfig.h:5,
#9 23.42                  from ../src/core/Cutter.cpp:13:
#9 23.42 /usr/include/librz/rz_list.h:77:53: note:   initializing argument 1 of 'unsigned int rz_list_length(const RzList*)'
#9 23.42  RZ_API ut32 rz_list_length(RZ_NONNULL const RzList *list);
#9 23.42                                        ~~~~~~~~~~~~~~^~~~
#9 23.42 ../src/core/Cutter.cpp: In member function 'QString CutterCore::getVersionInformation()':
#9 23.42 ../src/core/Cutter.cpp:4337:27: error: 'rz_analysis_version' was not declared in this scope
#9 23.42          { "rz_analysis", &rz_analysis_version },
#9 23.42                            ^~~~~~~~~~~~~~~~~~~
#9 23.42 ../src/core/Cutter.cpp:4337:27: note: suggested alternative: 'rz_analysis_var_size'
#9 23.42          { "rz_analysis", &rz_analysis_version },
#9 23.42                            ^~~~~~~~~~~~~~~~~~~
#9 23.42                            rz_analysis_var_size
#9 23.42 ../src/core/Cutter.cpp:4340:22: error: 'rz_asm_version' was not declared in this scope
#9 23.42          { "rz_asm", &rz_asm_version },
#9 23.42                       ^~~~~~~~~~~~~~
#9 23.42 ../src/core/Cutter.cpp:4340:22: note: suggested alternative: 'rz_hash_version'
#9 23.42          { "rz_asm", &rz_asm_version },
#9 23.42                       ^~~~~~~~~~~~~~
#9 23.42                       rz_hash_version
#9 23.42 ../src/core/Cutter.cpp:4353:24: error: 'rz_parse_version' was not declared in this scope
#9 23.42          { "rz_parse", &rz_parse_version },
#9 23.42                         ^~~~~~~~~~~~~~~~
#9 23.42 ../src/core/Cutter.cpp:4353:24: note: suggested alternative: 'rz_core_version'
#9 23.42          { "rz_parse", &rz_parse_version },
#9 23.42                         ^~~~~~~~~~~~~~~~
#9 23.42                         rz_core_version
#9 23.49 [33/187] Building CXX object src/CMakeFiles/Cutter.dir/Main.cpp.o
#9 24.21 [34/187] Building CXX object src/CMakeFiles/Cutter.dir/dialogs/WriteCommandsDialogs.cpp.o
#9 24.68 [35/187] Building CXX object src/CMakeFiles/Cutter.dir/widgets/OverviewView.cpp.o
#9 24.82 [36/187] Building CXX object src/CMakeFiles/Cutter.dir/widgets/DisassemblerGraphView.cpp.o
#9 24.82 FAILED: src/CMakeFiles/Cutter.dir/widgets/DisassemblerGraphView.cpp.o 
#9 24.82 /usr/bin/c++  -DCUTTER_SOURCE_BUILD -DCutter_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Isrc -I../src -Isrc/Cutter_autogen/include -I../src/core -I../src/widgets -I../src/common -I../src/plugins -I../src/menus -I../src/. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/librz -isystem /usr/include/librz/sdb -fvisibility=hidden   -Wall -Wextra -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/Cutter.dir/widgets/DisassemblerGraphView.cpp.o -MF src/CMakeFiles/Cutter.dir/widgets/DisassemblerGraphView.cpp.o.d -o src/CMakeFiles/Cutter.dir/widgets/DisassemblerGraphView.cpp.o -c ../src/widgets/DisassemblerGraphView.cpp
#9 24.82 ../src/widgets/DisassemblerGraphView.cpp: In member function 'void DisassemblerGraphView::loadCurrentGraph()':
#9 24.82 ../src/widgets/DisassemblerGraphView.cpp:228:66: error: no matching function for call to 'CutterRzList<rz_analysis_bb_t>::CutterRzList(RzPVector*&)'
#9 24.82      for (const auto &bbi : CutterRzList<RzAnalysisBlock>(fcn->bbs)) {
#9 24.82                                                                   ^
#9 24.82 In file included from ../src/core/CutterCommon.h:10,
#9 24.82                  from ../src/core/Cutter.h:4,
#9 24.82                  from ../src/widgets/GraphView.h:18,
#9 24.82                  from ../src/widgets/CutterGraphView.h:11,
#9 24.82                  from ../src/widgets/DisassemblerGraphView.h:11,
#9 24.82                  from ../src/widgets/DisassemblerGraphView.cpp:2:
#9 24.82 ../src/core/RizinCpp.h:156:14: note: candidate: 'CutterRzList<T>::CutterRzList(const RzList*) [with T = rz_analysis_bb_t; RzList = rz_list_t]'
#9 24.82      explicit CutterRzList(const RzList *l) : list(l) {}
#9 24.82               ^~~~~~~~~~~~
#9 24.82 ../src/core/RizinCpp.h:156:14: note:   no known conversion for argument 1 from 'RzPVector*' {aka 'rz_pvector_t*'} to 'const RzList*' {aka 'const rz_list_t*'}
#9 24.82 ../src/core/RizinCpp.h:110:7: note: candidate: 'constexpr CutterRzList<rz_analysis_bb_t>::CutterRzList(const CutterRzList<rz_analysis_bb_t>&)'
#9 24.82  class CutterRzList
#9 24.82        ^~~~~~~~~~~~
#9 24.82 ../src/core/RizinCpp.h:110:7: note:   no known conversion for argument 1 from 'RzPVector*' {aka 'rz_pvector_t*'} to 'const CutterRzList<rz_analysis_bb_t>&'
#9 24.82 ../src/core/RizinCpp.h:110:7: note: candidate: 'constexpr CutterRzList<rz_analysis_bb_t>::CutterRzList(CutterRzList<rz_analysis_bb_t>&&)'
#9 24.82 ../src/core/RizinCpp.h:110:7: note:   no known conversion for argument 1 from 'RzPVector*' {aka 'rz_pvector_t*'} to 'CutterRzList<rz_analysis_bb_t>&&'
#9 25.04 [37/187] Building CXX object src/CMakeFiles/Cutter.dir/common/DisassemblyPreview.cpp.o
#9 25.04 ninja: build stopped: subcommand failed.
#9 ERROR: process "/bi [...]

2024-03-18 15:21 UTC, XVilka commented
Requires jsdec to be fixed first.

2024-03-19 03:03 UTC, wargio commented on src/core/Cutter.cpp
> +        m_arena = ((RzArenaListItem *)rz_list_last(arenas))->addr;
According to the changes i did previously on rizin, this is `rz_list_first`.

2024-03-19 03:03 UTC, wargio requested changes
See comment above.

2024-03-19 03:04 UTC, wargio commented on src/core/Cutter.cpp
> +        m_arena = ((RzArenaListItem *)rz_list_last(arenas))->addr;
```suggestion
        m_arena = ((RzArenaListItem *)rz_list_first(arenas))->addr;
```

2024-03-19 09:41 UTC, wargio approved these changes
LGTM now.

2024-03-19 09:51 UTC, merged