Doc editing
rizinorg/cutter pull request #3325
Opened 2024-03-29 13:34 UTC by OfekShilon

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

It is clear a lot of work went into [the GraphGridLayout documentation](https://cutter.re/docs/api/widgets/classGraphGridLayout.html), but small grammatical and markdown glitches make it slightly harder than necessary to read. This is just some suggested editorial work, that would have helped me personally.

**Test plan (required)**

Not sure I got the meaning of

> For all edges keep the node which is above above. This helps when vertical block spacing is set bigger than double edge spacing and edge shadows relationship between two blocks.

right, editing is very welcome.

2024-03-29 13:36 UTC, OfekShilon commented
BTW the context is borrowing some graph algorithms for use in compiler-explorer: https://github.com/compiler-explorer/compiler-explorer/blob/45b743e22b37fbc8a858daddd8280eada070e807/static/graph-layout-core.ts#L29-L31

2024-03-29 20:31 UTC, karliss requested changes
Thank you for the spending the time making it cleaner. I sometimes get distracted in the middle of sentence, and I don't check what I have written previously. That's how you get nonsense like "read description of graph for definition for precise definition". No excuses for rest of the bad writing. 

There might be one more portion off comments. There are a few important part's I didn't check yet.

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +Contrary to many other layered graph-drawing algorithm this implementation doesn't perform node
```suggestion
Contrary to many other layered graph-drawing algorithms this implementation doesn't perform node
```

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +are zero-width. After nodes placement and edges rounting, the row/column of nodes is known as well as the
```suggestion
are zero-width. After node placement and edges routing, the row/column of nodes is known as well as the 
```

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +amount of edges between each rows pair. Using this information, positions are converted from grid cells to
`each rows pair` this doesn't sound right

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +configuration options can result in denser or sparser layout.
> so configuration options can result in denser or sparser layout.

To me this  sounds like "due to human perception properties, changing unrelated configuration can accidentally change layout sparsity"

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +the horizontal bounds or in the middle of its direct children. The first option results in narrower layout,
Any way to keep the vertical column part? I am open to suggestions for better wording. The difference between slightly narrower and slightly wider in many cases isn't very meaningful. But having a single (or two) vertical column  vs having not a single column is a big difference.

Sometimes I joke to myself that Binary ninja wants single column so much that their layout algorithm is: place everything in single  column, draw edge spaghetti on sides. Ghidra on the other hand looks like they were intentionally trying to draw one of the nested treeviews:
![image](https://github.com/rizinorg/cutter/assets/7101031/40893669-17b9-45b9-b37b-60d33529d6db)

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> -Rough routing creates the path of edge using up to 5 segments using grid coordinates.
Why did you remove the sentence about rough routing? It's a somewhat important detail that routing happens in two stages:
* rough -> produces grid coordinates rows and columns ignoring exact block dimensions and space taken by edges (see the previous section describing grid) 
* fine adjustments -> calculate the exact pixel positions taking into account exact block dimensions and space taken by edges

Do you think some other part makes it sufficiently clear that so far code still operates with "the grid". I guess the 5 segment part is somewhat redundant, since immediately  following text expands on the the <=5 segments.

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +Both problems are mitigated by squishing-graph. Compressing in each of the two direction is done
```suggestion
Both problems are mitigated by squishing the graph. Compressing in each of the two direction is done
```
"squishing-graph" is not a thing. It was supposed to be a action + object, not a compound noun.

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +until a constraint is satisfied and afterwards variables are grouped and modified together.
" modified until a constraint is satisfied" has a completely different meaning. That implies that it starts with an solution where constraints are not satisfied and then somehow magically chooses a value in which they are satisfied. Ok, you could easily satisfy one constraint, but that would likely break other constraints. 

What's actually happening is that:
* all the constraints are initially satisfied due to rest of algorithm producing valid layout
* variables are changed in the direction  which would improve the objective function value until it hits a constraint and changing it further would violate one of the constraints

2024-03-29 20:31 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +Since a perfect solution isn't necessary and to avoid poor performance, the current
"worst case performance" in context of algorithm complexity refers to very specific thing. It's not just generic "poor performance". I am pretty sure that there are well made general linear program solvers, that have a great performance in an average situations. General purpose linear program solvers "being slow" is not what I am claiming there. 

The problem is that there exists inputs for which the proven complexity is not acceptable. Having the optimization step take exponential time is based on input is not acceptable. Taking n^2 time is not acceptable. Whether there can be a graph which would produce worst case input for any of generic algorithms, I don't know, I haven't spent the time to prove or disprove that. But considering that there is a simple solution which avoids all the, I currently have little interest further investigating that.

2024-03-30 18:03 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +amount of edges between each rows pair. Using this information, positions are converted from grid cells to
Modifying to `each pair of rows`

2024-03-30 18:06 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +the horizontal bounds or in the middle of its direct children. The first option results in narrower layout,
Sure, my bad. Restoring

2024-03-30 18:08 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +configuration options can result in denser or sparser layout.
> > so configuration options can result in denser or sparser layout.
> 
> To me this sounds like "due to human perception properties, changing unrelated configuration can accidentally change layout sparsity"

Right, restoring.

2024-03-30 18:09 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +configuration options can result in denser or sparser layout.
Right, restoring.

2024-03-30 18:11 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> -Rough routing creates the path of edge using up to 5 segments using grid coordinates.
It's certainly important, this just reads as a duplicate of the line that follows: `The path for edges is chosen so that it consists of at most 5 segments...`

2024-03-30 18:12 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +Since a perfect solution isn't necessary and to avoid poor performance, the current
Sure, reverting.

2024-03-30 18:16 UTC, OfekShilon commented
> Thank you for the spending the time making it cleaner. I sometimes get distracted in the middle of sentence, and I don't check what I have written previously. That's how you get nonsense like "read description of graph for definition for precise definition". No excuses for rest of the bad writing.
> 
> There might be one more portion off comments. There are a few important part's I didn't check yet.

Thanks for the detailed review! All your fixes are applied and marked resolved except one: please see the unresolved comment. If you still want to keep the original - no problem, I'll just restore it.

2024-04-01 20:47 UTC, karliss requested changes

2024-04-01 20:47 UTC, karliss commented on src/widgets/GraphGridLayout.cpp
> +block-spacing is set bigger than double edge spacing and an edge shadows relationship between two blocks.
Your concerns about not getting this part right were correct.

How doe this sound to you?
> For all blocks connected by forward edge, keep the vertical distance at least as big as configured block vertical spacing.  This helps when vertical block-spacing is set bigger than double edge spacing and an edge shadows relationship between two blocks.

2024-04-02 08:30 UTC, OfekShilon commented on src/widgets/GraphGridLayout.cpp
> +block-spacing is set bigger than double edge spacing and an edge shadows relationship between two blocks.
Seems much better, thanks.

2024-04-08 20:00 UTC, merged