Update cutter-deps to QT6
rizinorg/cutter pull request #3363
Opened 2024-07-14 15:38 UTC by karliss

IMPORTANT
Do not merge before   rizinorg/cutter-deps#16 is finished and  switching cutter-deps-qt URL back to rizinorg !
IMPORTANT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Followup tasks**

* #3283 and
*  update the build documentation 

**Test plan (required)**

**Closing issues**

2024-07-14 15:44 UTC, karliss commented on scripts/fetch_deps.sh
> +DEPS_BASE_URL=https://github.com/karliss/cutter-deps/releases/download/qt6-test #TODO: replace before merging
Switch back before merging the PR.

2024-07-16 14:19 UTC, XVilka requested changes

2024-07-16 14:19 UTC, XVilka commented on .github/workflows/ci.yml
>              linux-x86_64-qt6-system-deps,
Consider renaming `linux-x86_64-qt6-system-deps` into just `linux-x86_64-system-deps` and the old one just into `linux-x86_64-qt5-system-deps` to reflect the fact that Qt6 is the default one now.

2024-07-16 14:19 UTC, XVilka commented on src/bindings/bindings.xml.in
> +        /*PythonToCppFunc pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(Sbk${PYSIDE_NAME}_QtCoreTypeConverters[SBK_QSTRING_IDX], pyResult);
Why comment and not remove instead?

2024-07-22 00:31 UTC, XVilka approved these changes

2024-07-22 10:52 UTC, XVilka commented
Tested it (basic testing procedure) on these platforms:
- macOS 14.5 ARM64
- Windows 11 (x86_64)

2024-07-22 10:59 UTC, Rot127 commented
Both AppImages work for me (qt5 and qt6). Tested on Debian 11 x86_64

2024-07-22 11:37 UTC, wargio commented
i have tested linux qt5 and qt6 and works.

2024-07-23 17:08 UTC, insaneninja117 commented
This is probably obvious to everyone already but unless a special Qt5 build is added for Windows moving forwards this will mean support for Windows 7 will be dropped with this change.

2024-07-24 00:00 UTC, XVilka commented
> This is probably obvious to everyone already but unless a special Qt5 build is added for Windows moving forwards this will mean support for Windows 7 will be dropped with this change.

2024-07-24 00:01 UTC, XVilka commented
Sorry, pressed the wrong button

2024-07-24 05:47 UTC, Rot127 commented on scripts/fetch_deps.sh
> +DEPS_BASE_URL=https://github.com/karliss/cutter-deps/releases/download/qt6-test #TODO: replace before merging
Reminder :)

2024-07-24 05:48 UTC, Rot127 approved these changes
Only revert the link to the Rizin repo please.

2024-07-24 16:01 UTC, wargio approved these changes

2024-07-25 10:40 UTC, XVilka approved these changes

2024-07-26 18:53 UTC, merged