ci macos-x86_64: Upgrade to the macos-14-large image
rizinorg/cutter pull request #3387
Opened 2024-10-20 05:17 UTC by kazarmy

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

The GitHub macos-12 image is in the [process of being removed](https://github.com/actions/runner-images/issues/10721) so this pr replaces it with the macos-14-large image.

**Test plan (required)**

The replacement is appropriate.

**Closing issues**

...

2024-10-20 05:46 UTC, kazarmy commented
Redness is unrelated

2024-10-20 06:08 UTC, karliss requested changes
In my opinion `macos-13` would be better. 

Both for running the build on oldest available mac, and to avoid the "large" GHA instances.

2024-10-20 06:14 UTC, kazarmy commented
> In my opinion `macos-13` would be better.
> 
> Both for running the build on oldest reasonably available mac, and to avoid the "large" GHA instances.

Ok 78a99984d2976f37131c8eb8fedcd239d7ea2972

2024-10-20 06:24 UTC, karliss approved these changes

2024-10-20 06:46 UTC, karliss commented
As for the hdiutil failures. I guess it's worth trying the second workaround described here.

https://github.com/actions/runner-images/issues/7522#issuecomment-1566746364

2024-10-20 07:27 UTC, kazarmy commented
Ok 29931e74637d5d0bc6e6db426ba4cd5887736e86

2024-10-20 10:02 UTC, karliss commented
That's separate problem, but the M1 macos failure can be fixed by adding 
```
                -DPython3_FIND_STRATEGY="LOCATION" \
                -DPython_FIND_STRATEGY="LOCATION" \
```

2024-10-20 15:06 UTC, kazarmy commented
> That's separate problem, but the M1 macos failure can be fixed by adding
> 
> ```
>                 -DPython3_FIND_STRATEGY="LOCATION" \
>                 -DPython_FIND_STRATEGY="LOCATION" \
> ```

There's no guarantee that the first Python version found won't be 3.13.

Btw, the `macos-14-arm64` runner image swung from 20241007.259 (Python 3.12) to 20241014.301 (Python 3.13) and back to 20241007.259 (Python 3.12) in the course of a few hours.

2024-10-20 15:40 UTC, karliss commented
> There's no guarantee that the first Python version found won't be 3.13.

I would hope that having explicit "Python_ROOT_DIR" hint has higher priority in the search order compared to whatever default search folders are.

2024-10-20 15:47 UTC, karliss requested changes
<

2024-10-20 15:47 UTC, karliss commented on .github/workflows/ci.yml
> +        echo killing XProtectBehaviorService; sudo pkill -9 XProtect >/dev/null || true;
Maybe add a comment that the whole XProtect killing thing are attempts to avoid  to random hdiutil failures.  So that later on when cleaning up build scripts it can be removed without too much head scratching of why it was ever added.

2024-10-20 16:21 UTC, kazarmy commented on .github/workflows/ci.yml
> +        echo killing XProtectBehaviorService; sudo pkill -9 XProtect >/dev/null || true;
Ok e78c29cb7d8a8ddea09777627fc858945fe25068

2024-10-20 16:35 UTC, karliss approved these changes

2024-10-21 02:59 UTC, wargio approved these changes

2024-10-21 03:01 UTC, wargio commented
WTF. why ` libquickjs| Compiler for C supports arguments /experimental:c11atomics: NO` is not supported? is required for qjs

2024-10-21 08:41 UTC, wargio commented
@kazarmy i merged my fix on jsdec repo (with also a test for msvc 2019)

2024-10-21 08:42 UTC, wargio commented on .github/workflows/ci.yml
> +        brew install kadwanev/brew/retry
maybe move this eariler since you are installing a dependency.

2024-10-21 08:44 UTC, wargio commented on .github/workflows/ci.yml
> +        retry 'rm -rf ../jsdec ../libswift ../rz_libyara ../rz-silhouette; make package'
why this is done on some plugins and not all the plugins? is this related to some redness where they do not compile? if yes, add a comment explaining why this is here.

2024-10-21 09:38 UTC, kazarmy commented on .github/workflows/ci.yml
> +        retry 'rm -rf ../jsdec ../libswift ../rz_libyara ../rz-silhouette; make package'
it's due to (https://github.com/rizinorg/cutter/actions/runs/11425970615/job/31788307472#step:7:9706):

![rimraf-reason](https://github.com/user-attachments/assets/05e5bd11-654b-4ea4-9a4f-dbe29102cb9b)

the other plugins were rimrafed because the build is so slow and it would have taken too long to check the plugins one-by-one

2024-10-21 09:46 UTC, kazarmy commented on .github/workflows/ci.yml
> +        brew install kadwanev/brew/retry
ok 0d5b7db42c2a5e236eb309bd8d17a7c11e561ed2

2024-10-21 09:47 UTC, kazarmy commented on .github/workflows/ci.yml
> +        retry 'rm -rf ../jsdec ../libswift ../rz_libyara ../rz-silhouette; make package'
>  if yes, add a comment explaining why this is here.

ok 97b93a51cfd138e28335459cf734c13621bda9e2

2024-10-21 12:47 UTC, karliss requested changes

2024-10-21 12:47 UTC, karliss commented on .github/workflows/ci.yml
> +                -DPython3_FIND_VIRTUALENV=ONLY \
What exactly are you trying to do here? Which of the half dozen different python uses were you trying to influence here?

Note that python virtual env used for installing meson is not the same thing as python used for pyside stuff. The later needs to be same stuff which is included in cutter deps and was used for compiling pyside. And based on log doesn't seem like it even had any effect.

2024-10-21 13:28 UTC, kazarmy commented on .github/workflows/ci.yml
> +                -DPython3_FIND_VIRTUALENV=ONLY \
> That's separate problem, but the M1 macos failure can be fixed by adding
> 
> ```
>                 -DPython3_FIND_STRATEGY="LOCATION" \
>                 -DPython_FIND_STRATEGY="LOCATION" \
> ```

Ok the above works 3a1ff3af1e7da2b1558f994db654677feba3e0cb

![python-python3-3 12 4](https://github.com/user-attachments/assets/39bc8c04-ff58-44f2-84f2-581a803e1225)
(https://github.com/rizinorg/cutter/actions/runs/11440905994/job/31827773144?pr=3387#step:8:107)

2024-10-21 13:32 UTC, karliss commented on .github/workflows/ci.yml
> +                -DPython3_FIND_VIRTUALENV=ONLY \
Is there a point keeping macos venv stuff now?

2024-10-21 13:37 UTC, kazarmy commented on .github/workflows/ci.yml
> +                -DPython3_FIND_VIRTUALENV=ONLY \
I don't know, but I can try and see what happens 7cf9e2a85c5edfbe5ded37c2b63c4bf7e9247ee4 8f4f89f357ce90c42652a677ef900f7b1d7bd4ae

2024-10-21 13:49 UTC, kazarmy commented on .github/workflows/ci.yml
> +                -DPython3_FIND_VIRTUALENV=ONLY \
Still works:

![python-python3-3 12 4 (2)](https://github.com/user-attachments/assets/68d9a790-0d0e-4121-be24-6d25fba8a8a9)
(https://github.com/rizinorg/cutter/actions/runs/11441340672/job/31829201505?pr=3387#step:7:107)

2024-10-21 15:35 UTC, karliss approved these changes

2024-10-21 15:41 UTC, merged